### ISSUE TITLE
同一方法如何根据入参不同mock返回不同结果，如果参数相同又如何返回不同结果，实现不同场景的覆盖？

### ISSUE THREAD

**Issue by GodwinHub** [alibaba/testable-mock#100]
1.对于同一方法不同入参返回不同结果的情况，我目前是在mock方法中写if else/case逻辑判断语句来返回不同结果，请问有什么其他办法实现这种mock吗?

    @MockMethod(targetClass = Config.class)
    private int getIntProperty(String var1, Boolean var2) {
        int result = 0;
        if (var1.equals("switch_check_one")) {
            result = 1;
        } else if (var1.equals("switch_check_two")) {
            result = 2;
        }
        return result;
    }

2.如果同一方法入参也相同，如何实现每一次跑测试用例返回不同结果？
类似于这种，从Apollo获取开关

    @MockMethod(targetClass = Config.class)
    private Boolean getBooleanProperty(String var1, Boolean var2) {
        boolean result = true;
        if (var1.equals("switch_check")) {
            result = false;
        }
        return result;
    }

入参相同，在测试方法中调用两次被测类，如何实现第一次调用时getBooleanProperty方法针对入参为switch_check返回true，第二次调用执行被测类时还是这个入参返回false？

**Comment by linfan** [comment]
1 参数不同的情况，在Mock方法里加判断是没问题的。`TestableMock`在设计思路上是让每个业务类自己提供自己的统一Mock方法，如果有特殊情况需要做区分，通常做法是直接在Mock方法里进行分支判断。

2 参数相同的情况，可以参考文档这个部分，使用`MOCK_CONTEXT`进行区分
https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock?id=_5-在mock方法中区分调用来源
