### ISSUE TITLE
Mock接口不生效问题

### ISSUE THREAD

**Issue by forxfoo** [alibaba/testable-mock#101]
如下代码块，mock DAO 一直不生效。 dao 是接口，有具体实现类。
参照常见问题里面`3. 父类变量指向子类对象时，如何实现Mock方法？`。用法应该是没问题，但一直 mock 没生效，求大神帮忙看看。

testableMock 版本： `0.5.0`

```java
//被测试类
public class GenericService<T> {
    @Autowired
    private BaseDao<T> dao;

   //待单元测试
    public void method1(T obj) {
       // 其他操作
         dao.update(obj);
         //其他操作
    }
}

public interface BaseDao<T> {
     boolean update(T obj);
}

public class XXDaoImpl implements BaseDao<XX> {
    boolean update(XX xx) {}
}
```

```java
public class GenericServiceTest {
    public static class Mock {
      
        //这里一直没生效
        @MockMethod
        public boolean update(BaseDao self, Object obj) {
            return true;
        }
    }

//测试GenericService.method1， mock被测试类的 dao 不生效
   @Test
   public void testMethod1() {
       GenericService service = new GenericService()
        PrivateAccessor.set(service, "dao", new XXDaoImpl()); 
        //mock dao 没生效 如上注释的。 会进入到具体实现类 XXDaoImpl
         service.method1(new XX());
   }
}
```

**Comment by forxfoo** [comment]
@linfan

**Comment by linfan** [comment]
在测试用例里的调用不会被Mock，只有业务代码才需要用Mock哈。见文档里的”特别说明“：
https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock?id=特别说明

**Comment by forxfoo** [comment]
那有没办法 mock 上面代码的 dao

**Comment by forxfoo** [comment]
> 在测试用例里的调用不会被Mock，只有业务代码才需要用Mock哈。见文档里的”特别说明“：
> [https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock?id=特别说明](https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock?id=%E7%89%B9%E5%88%AB%E8%AF%B4%E6%98%8E)

service 层调用 dao层 ， 然后测试 service 层，把 dao mock 是很常见的场景呀。   
是我上面的示例代码写的有问题吗？

**Comment by linfan** [comment]
我看错了，你这儿需要Mock的调用确实是在业务代码里的。

这个代码里，要Mock的方法签名是`void update(T obj)`，Mock放到定义的签名是`boolean update(BaseDao self, Object obj)`，模板`T`替换成`Object`没有问题，但返回值类型没匹配。一个是`void`，一个是`boolean`。看下是不是这个原因？

**Comment by forxfoo** [comment]
> 我看错了，你这儿需要Mock的调用确实是在业务代码里的。
> 
> 这个代码里，要Mock的方法签名是`void update(T obj)`，Mock放到定义的签名是`boolean update(BaseDao self, Object obj)`，模板`T`替换成`Object`没有问题，但返回值类型没匹配。一个是`void`，一个是`boolean`。看下是不是这个原因？

不好意思哈，是我样例代码贴错了，实际都是`boolean`返回值。 上面代码我已修改了。

然后单元测试 mock 的 dao 没生效，会进入`PrivateAccessor.set(service, "dao", new XXDaoImpl());` XXDaoImpl 里面。

**Comment by linfan** [comment]
我试着按你的代码验了一下，结果是能够进入Mock方法的。不过你的代码里测试用例里的调用是`service.update(new XX());`，前面`GenericService`里定义的是`method1()`，我假设这里也应该是`update()`，然后调用的地方没有参数。

以下是我修正后的测试代码，看下和你的情况是否一致？

```java
public class GenericService {

    //@Autowired
    private BaseDao dao;

    //待单元测试
    public boolean update() {
        // 其他操作
        return dao.update(new Xx());
        //其他操作
    }

}
```

```java
public interface BaseDao<T> {
    boolean update(T obj);
}
```

```java
public class XxDaoImpl implements BaseDao<Xx> {
    @Override
    public boolean update(Xx xx) {
        return false;
    }
}
```

```java
public class Xx {
}
```


```java
public class GenericServiceTest {

    public static class Mock {
        //这里一直没生效
        @MockMethod
        public boolean update(BaseDao self, Object obj) {
            return true;
        }
    }

    //测试GenericService.method1， mock被测试类的 dao 不生效
    @Test
    public void testMethod1() {
        GenericService service = new GenericService();
        PrivateAccessor.set(service, "dao", new XxDaoImpl());
        //mock dao 没生效 如上注释的。 会进入到具体实现类 XXDaoImpl
        assertTrue(service.update());
    }

}
```

**Comment by forxfoo** [comment]
> ```java
> update
> ```

哈哈哈，疏忽了，太尴尬了，业务代码没有具体帖出来，还好老大你火眼金睛。 主要就是 mock dao 没成功。 
你测试有通过，我再试试看。

**Comment by forxfoo** [comment]
sad!  dao 还是进入到实际实例化(`XXDaoImpl`)了。

我先用`Mockito`来 mock 了，两者配合起来还可以。

**Comment by linfan** [comment]
先加`@MockDiagnose`注解对比一下Mock方法和目标行调用的方法签名哈，说不定自己就发现原因了，我这儿验证是没问题的
