### ISSUE TITLE
结合mybatislus通用mapper使用不能mock baseMapper

### ISSUE THREAD

**Issue by JOHHHNNN** [alibaba/testable-mock#102]
> 
public interface IService<T> {
    T getById(Serializable id);
}
>
----------------------------------------------------------------------------------
>
public class ServiceImpl<M extends BaseMapper<T>, T> implements IService<T> {
@Autowired
    protected M baseMapper;   
@Override
    public T getById(Serializable id) {
        return baseMapper.selectById(id);
    }
}
>
----------------------------------------------------------------------------------
>
public interface BaseMapper<T> {
T selectById(Serializable id);//由mybatis（plus）实现
}
>
----------------------------------------------------------------------------------
>
@Service
public class MenuResourceServiceImpl extends ServiceImpl<MenuResourceMapper, MenuResource>
        implements IMenuResourceService {
@Override
    public MenuResourceDTO getMenuDetailed(final Integer id) throws BizzException {
        final MenuResource menuResource = getById(id); //ServiceImpl#getById
        ......
        return convert(menuResource, MenuResourceDTO.class);
    }
}
>
----------------------------------------------------------------------------------
>
public interface MenuResourceMapper extends BaseMapper<MenuResource> {
}
>
----------------------------------------------------------------------------------
>
public interface IMenuResourceService extends IService<MenuResource> {
 MenuResourceDTO getMenuDetailed(Integer id) throws BizzException;
}
>
----------------------------------------------------------------------------------
>
public class MenuResourceServiceImplTest extends BaseTest{
    @Autowired
    private IMenuResourceService mIMenuResourceService;
    public static class Mock{
        // 我试了两种方式都不可以
        @MockMethod
        <T> T selectById(BaseMapper baseMapper,Serializable id){
            return (T)new MenuResource().setId(1).setMenuName("menu1");
        }
        @MockMethod
        <T> T selectById(MenuResourceMapper baseMapper,Serializable id){
            return (T)new MenuResource().setId(1).setMenuName("menu1");
        }
    }
    @Test
    public void getMenuDetailed() throws BizzException {
        final MenuResourceDTO menuDetailed = mIMenuResourceService.getMenuDetailed(1);
        System.out.println(menuDetailed);
    }
}
>
结果都是到数据库去做了查询
![image](https://user-images.githubusercontent.com/20449199/108869442-2cfaac00-7632-11eb-989a-94b284383c6b.png)
如果我换种方式写法，是可以的，但是ServiceIml中有很多封装，我希望直接调用Service中方法而不是去调用mapper中的方法来操作数据库。
>
@Override
    public MenuResourceDTO getMenuDetailed(final Integer id) throws BizzException {
        final MenuResource menuResource = baseMapper.selectById(id);
        ......
        return convert(menuResource, MenuResourceDTO.class);
    }
或
>
>
@Resource
    private MenuResourceMapper mMenuResourceMapper;
@Override
    public MenuResourceDTO getMenuDetailed(final Integer id) throws BizzException {
        final MenuResource menuResource = mMenuResourceMapper.selectById(id);
        ......
        return convert(menuResource, MenuResourceDTO.class);
    }
>
这问题困惑了我一段时间了，求大佬能帮忙看看。我的环境：
spring-boot-starter-parent：1.5.17.RELEASE
testable.version：0.5.0
mybatis-plus-boot-starter.version：3.0.5

**Comment by linfan** [comment]
从前面的代码我试着理解一下，你要测试的方法是`getMenuDetailed`

```java
@Override
public MenuResourceDTO getMenuDetailed(final Integer id) throws BizzException {
    final MenuResource menuResource = getById(id); // ServiceImpl#getById
    ...
    return convert(menuResource, MenuResourceDTO.class);
}
```

这里面有一个来自父类的`getById()`调用，希望在测试的时候将它替换掉。

需要理解的一个事情是，`TestableMock`替换的是实际的方法调用，而不是方法定义，因此要定义的方法应该是`getById()`，完整签名是`T getById(Serializable id)`，它的所属是被测类`MenuResourceServiceImpl`，因此在Mock容器类里定义如下方法即可实现测试时的调用替换：

```
@MockMethod(targetClass = MenuResourceServiceImpl.class)
<T> T getById(Serializable id) {
    return (T)new MenuResource().setId(1).setMenuName("menu1");
}
```

或者把Mock方法的所属类放在方法的首参数，下面这种写法也可以：

```
@MockMethod
<T> T getById(MenuResourceServiceImpl self, Serializable id) {
    return (T)new MenuResource().setId(1).setMenuName("menu1");
}
```

**Comment by JOHHHNNN** [comment]
多谢大佬 我又测试了一把 解决了我的问题  是我自己陷入了误区 之后有同学需要使用mybatisplus的 可以参照这里 再次感谢大佬
