### ISSUE TITLE
Android gradle 项目

### ISSUE THREAD

**Issue by LiuZhiDaa** [alibaba/testable-mock#103]
借用了#45的方案仍无法解决，此mock是否支持移动端单测？

A problem occurred evaluating project ':sdk'.
> Could not find method test() for arguments [build_ev2j2h473g7lytjpvmh8qsxi4$_run_closure6@74ae33a3] on project ':sdk' of type org.gradle.api.Project.

**Comment by linfan** [comment]
见 Issue #43 的例子，Android项目里没有 test{} 配置块，应该用 android.testOptions{} 配置单元测试参数

**Comment by LiuZhiDaa** [comment]
好的，感谢 完美解决
