### ISSUE TITLE
IDE 插件支持

### ISSUE THREAD

**Issue by yongyijian** [alibaba/testable-mock#104]
IDE 的插件什么时候可以支持一下
目前开发使用起来有大量重复的生成逻辑感觉可以复用

**Comment by linfan** [comment]
有三件事是IDE插件能做的：

- 生成Mock容器类。类似于IDE快速给当前业务类生成一个空的单元测试类一样，免去自己在目录树找到位置再手工输入文件名和敲基本固定的类结构代码。
- 复制方法签名。其实就是辅助生成Mock方法，不过这个功能其实可有可无，手工拷贝一下方法签名并不太麻烦。
- 提示Mock的实际作用目标。类似IntelliJ对Spring切面的支持，快速提示切面命中了哪些方法。替代用`@MockDiagnose`打印出来人工比对。

目前IDE插件开发还没提上正式议程，如果有社区开发者愿意帮忙提前实现这部分功能，大大的欢迎🥰

**Comment by keunsy** [comment]
> 有三件事是IDE插件能做的：
> 
> * 生成Mock容器类。类似于IDE快速给当前业务类生成一个空的单元测试类一样，免去自己在目录树找到位置再手工输入文件名和敲基本固定的类结构代码。
> * 复制方法签名。其实就是辅助生成Mock方法，不过这个功能其实可有可无，手工拷贝一下方法签名并不太麻烦。
> * 提示Mock的实际作用目标。类似IntelliJ对Spring切面的支持，快速提示切面命中了哪些方法。替代用`@MockDiagnose`打印出来人工比对。
> 
> 目前IDE插件开发还没提上正式议程，如果有社区开发者愿意帮忙提前实现这部分功能，大大的欢迎🥰



> 有三件事是IDE插件能做的：
> 
> * 生成Mock容器类。类似于IDE快速给当前业务类生成一个空的单元测试类一样，免去自己在目录树找到位置再手工输入文件名和敲基本固定的类结构代码。
> * 复制方法签名。其实就是辅助生成Mock方法，不过这个功能其实可有可无，手工拷贝一下方法签名并不太麻烦。
> * 提示Mock的实际作用目标。类似IntelliJ对Spring切面的支持，快速提示切面命中了哪些方法。替代用`@MockDiagnose`打印出来人工比对。
> 
> 目前IDE插件开发还没提上正式议程，如果有社区开发者愿意帮忙提前实现这部分功能，大大的欢迎🥰

你好啊，目前利用TestMe插件扩展了一个自动生成测试类的功能，主要利用MOCK_CONTEXT实现CASE不同取值，请问有没有其他针对CASE的设计，实现上可以更优雅些？

**Comment by zcbbpo** [comment]
@linfan 
是像这样的吗
![s3](https://user-images.githubusercontent.com/54526829/147529299-0db89b80-72d8-4db6-8536-86fb72b39a1e.GIF)

**Comment by linfan** [comment]
@zcbbpo 666，考虑发布到IntelliJ插件市场不？

**Comment by zcbbpo** [comment]
@linfan 还有一些bug需要处理，改好后我再发出来吧。
这个插件还需要一些其他的什么功能嘛

**Comment by linfan** [comment]
已经比较接近预期的效果了。

从上面录的Demo来看，应该还可以在两个地方稍作改进：
1. 生成测试类的时候，只需要添加好TestableMock相关注解的import，同时生成一个空的Mock内部类就可以了，不用给各个成员方法自动生成Mock方法（多数情况下要被Mock的并不是成员方法）
2. 添加一个 “拷贝当前方法的Mock定义” 功能，比如要Mock某一个调用，先从IDE上跟进到要调用的方法定义里，右键拷贝这个方法的Mock定义（实际上就是复制该方法的签名，加上@MockInvoke注解和一个空的方法体），然后就可以直接粘贴到Mock类里，免去手工拷贝方法签名的过程

期待插件~~

**Comment by zcbbpo** [comment]
https://github.com/zcbbpo/testable-idea

**Comment by linfan** [comment]
非常感谢！👍 
我这周就把插件信息更新到文档，一起维护起来

**Comment by linfan** [comment]
文档已更新 https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-intellij-plugin
这个issue可以关闭了，关于插件的其他问题移步到新仓库讨论
