### ISSUE TITLE
Mock方法与被Mock方法包不一致,Mock不生效

### ISSUE THREAD

**Issue by gjf450005950** [alibaba/testable-mock#106]
场景：项目依赖一个生成文档的工具类(smart-doc),某些功能需要自定义修改，官方未及时提供自定义扩展的方式，所以使用testable替换部分实现。

Mock：
````java
@MockDiagnose(ENABLE)
public class DocBuilderTemplateMock {

  /**
   * 使用Mock方式覆盖 字典实现
   *
   * @param config
   * @param javaProjectBuilder
   */
  @MockMethod(targetClass = com.power.doc.builder.DocBuilderTemplate.class)
  public List<ApiDocDict> buildDictionary(ApiConfig config, JavaProjectBuilder javaProjectBuilder) {
    System.out.println("Mock生效");
    List<ApiDocDict> apiDocDictList = new ArrayList<>();
    return apiDocDictList;
  }
}
````

```java
package top.oweb.doc;

/**
 * 生成接口文档.
 */
@MockDiagnose(ENABLE)
@MockWith(DocBuilderTemplateMock.class) // 测试类由于丢失与Mock容器的关联，需要@MockWith注解
public class BuilderControllersApi {

  /**
   * 构建或更新接口文档.
   */
  @Test
  public void builder() {
    ApiConfig config = new ApiConfig();
    HtmlApiDocBuilder.buildApiDoc(config);  //内部调用DocBuilderTemplate.buildDictionary方法
  }
}

```

- [x] 如果把DocBuilderTemplateMock类放到com.power.doc.builder包下会生效
- [ ] 如果把DocBuilderTemplateMock类放到top.oweb.doc包下不生效，MockMethod.targetClass 目标类包未生效

**Comment by linfan** [comment]
最后的问题是什么没有看明白哈，究竟是“会生效”还是“不生效”呢？

**Comment by gjf450005950** [comment]
> 最后的问题是什么没有看明白哈，究竟是“会生效”还是“不生效”呢？

放到top.oweb.doc下不生效

**Comment by linfan** [comment]
`TestableMock`的一个使用方式是让每个业务类提供自己的Mock类，这个和以往的Mock工具有些不太一样。

比如上述代码里，虽然是做`BuilderControllersApi`类型的测试，但实际要被Mock的调用发生在`HtmlApiDocBuilder`类型里面，因此是要`HtmlApiDocBuilder`自己的Mock类来提供Mock方法。从上述现象来看，`HtmlApiDocBuilder`所在的包应该是`com.power.doc.builder`，在此包路径下创建`HtmlApiDocBuilderMock`，然后放置相应Mock方法即可（只与被Mock的代码所在类有关，与从什么地方发起调用无关）。

关于这种Mock机制的原理可以参考文档 https://alibaba.github.io/testable-mock/#/zh-cn/doc/design-and-mechanism

**Comment by gjf450005950** [comment]
> `TestableMock`的一个使用方式是让每个业务类提供自己的模拟类，这个和以前的模拟工具有些不太一样。
> 
> 例如上述代码里，虽然是做`BuilderControllersApi`类型的测试，但实际要被模拟的调用发生在`HtmlApiDocBuilder`类型里面，因此是要`HtmlApiDocBuilder`自己的模拟类来提供模拟方法。从上述现象来看，`HtmlApiDocBuilder`所在的包应该是`com.power.doc.builder`，在此包路径下创建`HtmlApiDocBuilderMock`，然后放置相应的Mock方法即可（只与被Mock的代码所在类有关，与从什么地方发起调用无关）。
> 
> 关于这种模拟机制的原理可以参考文档https://alibaba.github.io/testable-mock/#/zh-cn/doc/design-and-mechanism

了解如上机制，使用TestableMock不是为了测试，使用替换方法的能力做一下其他开发。
能不能提供一种方案使方法与被Mock的方法包不一样

**Comment by linfan** [comment]
使用`@MockWith`注解指定Mock类的话，可以使用任意包位置，只是要在实际进行调用的类（或者相应的测试类）上加`@MockWith`。比如这里实际调用`DocBuilderTemplate.buildDictionary()`方法是在`HtmlApiDocBuilder`类里发生的，要Mock这个方法，是要在`HtmlApiDocBuilder`（或者它的测试类`HtmlApiDocBuilderTest`）上加上`@MockWith`。

Mock类是跟业务类关联（当一个调用要被Mock，我们假设它在测试的时候总是应该被Mock掉，不论从哪里调用过来的），和发起调用的类无关。这个地方一开始使用可能会不太习惯哈。

**Comment by gjf450005950** [comment]
> Q：为何当测试类在非约定位置时，是在被测类上使用@MockWith，而不在测试类上指定被测类？
A：从原则上来说，凡是能只改测试类就实现的，肯定不应该为了测试而去动业务代码（被测类）。 然而由于JavaAgent只能在类首次加载进内存的时候进行字节码处理，实际情况无法保证被测的类一定在测试类之后加载（可能在其他测试用例执行的时候就被提前加载进内存了），等读取到测试类上的信息时，可能已经无法对被测类进行Mock处理。因此对于测试类和被测类相互不知道对方位置的情况，采用了两边都用@MockWith指定Mock容器类的折中设计。


场景不符合，无法在使用的类上加MockWith，因为在jar包内

**Comment by linfan** [comment]
就上述这种情况来说的话，其实可以不用`@MockWith`注解，在项目测试目录的`com.power.doc.builder`包路径创建`HtmlApiDocBuilderMock`类就可以实现Mock了。即使`HtmlApiDocBuilder`类型来自于Jar包。

**Comment by gjf450005950** [comment]
> 就上述这种情况来说的话，其实可以不用`@MockWith`注解，在项目测试目录的`com.power.doc.builder`包路径创建`HtmlApiDocBuilderMock`类就可以实现Mock了。即使`HtmlApiDocBuilder`类型来自于Jar包。

是的，但是公司项目对包名有要求，突然出现一个`com.power`包有点奇怪。如果把`arthas`的部分功能搬到`testable-mock`就完美了

**Comment by linfan** [comment]
关于外部`jar`包的这种情况，之后会通过全局配置来做优化，见 #105 。

`arthas`的原理和`testable`比较像，只是`arthas`针对长期运行的后台进程，用的是运行时javaagent注入，`testable`使用的是启动时注入。对于单元测试的情况，运行时注入的时机太晚了，启动时注入除了每个类只能改一次字节码以外，其他能力和运行时注入差不多，应该能实现类似`arthas`功能。有什么好的建议也欢迎提出哈。

**Comment by gjf450005950** [comment]
> 关于外部`jar`包的这种情况，之后会通过全局配置来做优化，见 #105 。
> 
> `arthas`的原理和`testable`比较像，只是`arthas`针对长期运行的后台进程，用的是运行时javaagent注入，`testable`使用的是启动时注入。对于单元测试的情况，运行时注入的时机太晚了，启动时注入除了每个类只能改一次字节码以外，其他能力和运行时注入差不多，应该能实现类似`arthas`功能。有什么好的建议也欢迎提出哈。

谢谢， ` #105` 功能实现能满足目前需求。
