### ISSUE TITLE
工程里使用了jacoco-maven-plugin插件，也添加了@{argLine}参数，仍然有找不到或无法加载主类 @{argLine}的问题

### ISSUE THREAD

**Issue by GodwinHub** [alibaba/testable-mock#107]
pom文件中plugin的配置如下，当存在图片标红里面的配置时，单测执行mock的内容不生效，去掉这部分内容mock生效，但是会报找不到或无法加载主类 @{argLine}，同时CI覆盖率跌为0
![plugin1](https://user-images.githubusercontent.com/78467920/109492112-6e250d00-7ac5-11eb-9762-5c2f4b6e3174.png)
![plugin2](https://user-images.githubusercontent.com/78467920/109492160-7da45600-7ac5-11eb-9dc1-433073abd89f.png)

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19</version>
                <configuration>
                    
                    <testFailureIgnore>true</testFailureIgnore>
                    
                    <argLine>-Dfile.encoding=UTF-8</argLine>

                    
                    <argLine>-noverify ${surefireArgLine}
                          -javaagent:${settings.localRepository}/org/powermock/powermock-module-javaagent/${powermock.version}/powermock-module-javaagent-${powermock.version}.jar
                    </argLine>
                    <argLine>@{argLine} -javaagent:${settings.localRepository}/com/alibaba/testable/testable-agent/${testable.version}/testable-agent-${testable.version}.jar</argLine>
                    <systemPropertyVariables>
                        <jacoco-agent.destfile>${project.build.directory}/jacoco.exec</jacoco-agent.destfile>
                    </systemPropertyVariables>

                    <properties>
                        
                        <property>
                            <name>suitethreadpoolsize</name>
                            <value>1</value>
                        </property>
                        <property>
                            <name>usedefaultlisteners</name>
                            <value>false</value>
                        </property>
                    </properties>
                    <suiteXmlFiles>
                        <suiteXmlFile>src/test/resources/testng.xml</suiteXmlFile>
                    </suiteXmlFiles>
                    
                    <reportsDirectory>target/test-output</reportsDirectory>

                </configuration>
            </plugin>

注：上面图片里红色圈出部分对应这里
<argLine>-Dfile.encoding=UTF-8</argLine>
<argLine>-noverify ${surefireArgLine}
               -javaagent:${settings.localRepository}/org/powermock/powermock-module-javaagent/${powermock.version}/powermock-module-javaagent-${powermock.version}.jar
</argLine>

            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.version}</version>
                <executions>
                    <execution>
                        <id>pre-unit-test</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <configuration>
                            
                            <destFile>${project.build.directory}/jacoco.exec</destFile>
                            
                            <propertyName>surefireArgLine</propertyName>
                        </configuration>
                    </execution>

                    <execution>
                        <id>post-unit-test</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <configuration>
                            <dataFile>${project.build.directory}/jacoco.exec</dataFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by linfan** [comment]
在jacoco插件的配置里已经显式设置了`<propertyName>surefireArgLine</propertyName>`，因此在前面引用的地方应该使用`${surefireArgLine}`（上述代码里已经加了），不需要再加`@{argLine}`。可以试一下直接把`@{argLine}`直接去掉。

**Comment by linfan** [comment]
`@{argLine}`是在没有配置`propertyName`的时候的默认参数名字🙂
