### ISSUE TITLE
请问下Spring环境下，对于bean的嵌套该如何mock 呢？

### ISSUE THREAD

**Issue by LikeElephantintheforest** [alibaba/testable-mock#108]
请问下Spring环境下，对于bean的嵌套该如何mock 呢？ 大致调用如下：

```java
class A {
  @Autowired  Class B;
  
  needTestmethod(Request req){
      b.request(req);
  }
 
}
```

```java
class B {
  @autowired Class C;

  method(){
  }
  
}
```

```java
Class C {
 @autowired Class D;
 
 method(){
  }
  
}
```

```java
Class D {
  
 needMockMethod(){
 }

}
```
---------

1. 其中需要对D中的needMockMethod()方法进行mock。
2.在单元测试中需要对Class A 中的needTestmethod(Request req)进行调用。

**Comment by linfan** [comment]
始终是让每个类自己提供自己的Mock容器类，比如是在类型`C`的代码里有`d.needMockMethod()`这个调用要Mock掉，那么就在`C`类型的Mock容器类加Mock方法。

在测试目录与`C`相同的包路径下创建`CMock`类型（业务类+Mock），添加类似下面这样的Mock方法就可以了。

```java
@MockMethod(targetClass = D.class)
needMockMethod() {
}
```

**Comment by iceqing** [comment]
> 测试目录与`C`相同的包路径下创建`CMock`类型（业务类+Mock），添加类似下面这样的Mock方法就可以了

遇到同样问题，感觉这样的解决方案不是很优雅，有没有办法直接在当前mock类（A类）进行D类的方法mock ?
