### ISSUE TITLE
筒子们，多少人用啊

### ISSUE THREAD

**Issue by honestAnt** [alibaba/testable-mock#11]

**Comment by linfan** [comment]
看来需要写篇帖子介绍一下这个项目的起源和团队情况🤔

**Comment by linfan** [comment]
加了个简短的项目介绍~~
https://alibaba.github.io/testable-mock/#/zh-cn/doc/about-us

**Comment by linfan** [comment]
长篇介绍暂时不打算写了哈，这个Issue先关哦，有具体问题可以再提出
