### ISSUE TITLE
子类中修改父类的变量还是报错

### ISSUE THREAD

**Issue by yuanrong0824** [alibaba/testable-mock#111]
看了下代码0.5版本只是把异常抛出去了 没有获取父类的filed进行set

**Comment by linfan** [comment]
在主干代码里已经修复了，抱歉没有如预期包含在`0.5.1`版本中，在本周内会发布`0.5.2`版本包含此修复

**Comment by linfan** [comment]
`0.5.2`版本已发布

**Comment by yuanrong0824** [comment]
收到 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/testable-mock"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月13日(星期六) 中午11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/testable-mock] 子类中修改父类的变量还是报错 (#111)



 0.5.2版本已发布
