### ISSUE TITLE
0.5.1版本，MockDiagnose(LogLevel.VERBOSE)导致Mock没有生效，报错

### ISSUE THREAD

**Issue by shower2019** [alibaba/testable-mock#113]
加上＠MockDiagnose(LogLevel:VERBOSE)就出错，加上＠MockDiagnose(LogLevel:ENABLE)可以顺利通过
报错信息如下：
...
...
[VERBOSE] Line45, invoking "xx.xx.xx.xx.business.impl.EnvBuusinessImplTest$Mock::getEnvInfo(xx.xx.xx.xx.service.EnvInfoService, java.lang.String) : xx.xx.xx.xx.model.EnvInfo
[VERBOSE] Line 49, invoking "xx.xx.xx.xx.model.EnvInfo::getEnvIp(): java.lang.String"
[VERBOSE] Line 49, invoking "java.lang.String::matches(java.lang.String):boolean
[DIAGNOSE] java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[WARN] Failed to transform class xx/xx/xx/xx/business/impl/EnvBusinessImpl

**Comment by linfan** [comment]
同 #109 ，会在`0.5.2`版本中修复
