### ISSUE TITLE
0.5.1版本，利用TestableMock做集成Mock测试，如何做好各个Mock方法的隔离性？

### ISSUE THREAD

**Issue by jiajiali0511** [alibaba/testable-mock#114]
描述：
目前在做集成的mock测试时，只能通过单侧时mock的方法返回（mock方法的作用范围是GLOBAL）。
但如果存在多个测试方法调用同一个底层方法时，底层方法的改动后可能就会影响其他的方法测试。

目的：
1.如何做到集成测试类之间的隔离？
2.如何做到集成测试与单侧之间的隔离？

思路：
可以将集成测试时依赖的方法在集成测试类里重新做mock，与单侧时的mock做区分。

希望大神给个解答。

case：
A/B/C/D——四个类
依赖关系——A依赖C、B依赖C、C依赖D

集成测试：
A-->C-->D ： 当测试A的方法时最终依赖D的mock结果
B-->C-->D ： 当测试B的方法时最终依赖D的mock结果

修改D的mock结果时两个测试会冲突。如何做到D的mock结果在A测试和B测试中隔离？

**Comment by ddatsh** [comment]
```xml
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>@{argLine}
                        -javaagent:${settings.localRepository}/com/alibaba/testable/testable-agent/${testable.version}/testable-agent-${testable.version}.jar=mockScope=associated
                    </argLine>
                </configuration>
            </plugin>
```

**Comment by linfan** [comment]
`TestableMock`最初基于的假设是“要Mock的调用大多都是因为有外部依赖，所以在整个单测过程中都应该被Mock，并且大多数情况Mock方法体都很简单且与调用来源无关”，对不符合这种情况的场景（譬如单测和集测混写），使用起来就会稍麻烦。

基本的解法是利用`MOCK_CONTEXT`这个工具变量来区分不同来源的调用，在需要特殊处理的测试用例里设置一个标志键。针对单测和集测混写这种场景，如果单测写得比较规范（每个单测都是测试自身的逻辑代码），也可以把全局的MockScope改为`associated`，如@ddatsh 写的这种方式。

**Comment by jiajiali0511** [comment]
> `TestableMock`最初基于的假设是“要Mock的调用大多都是因为有外部依赖，所以在整个单测过程中都应该被Mock，并且大多数情况Mock方法体都很简单且与调用来源无关”，对不符合这种情况的场景（譬如单测和集测混写），使用起来就会稍麻烦。
> 
> 基本的解法是利用`MOCK_CONTEXT`这个工具变量来区分不同来源的调用，在需要特殊处理的测试用例里设置一个标志键。针对单测和集测混写这种场景，如果单测写得比较规范（每个单测都是测试自身的逻辑代码），也可以把全局的MockScope改为`associated`，如@ddatsh 写的这种方式。

@linfan 你好，这样的话会有以下问题：
1.”利用`MOCK_CONTEXT`这个工具变量来区分不同来源的调用“——对于自测用例代码复杂度会升高，会有各种不同的判定逻辑。
2.”把全局的MockScope改为associated“——集成测试时就拿不到单侧时Mock的结果。

**Comment by linfan** [comment]
是的，如前面的回复所述，`TestableMock`的设计假设就是“大多数Mock方法体都很简单且与调用来源无关”，对于有少量需要区分调用来源的情况，可以通过`MOCK_CONTEXT`来处理。但如果在有非常多需要针对不同来源做不同处理的Mock方法，则以往在每个测试用例里单独写Mock的工具会更合适，譬如`Mockito`。
