### ISSUE TITLE
请问私有内部类中的方法如何mock

### ISSUE THREAD

**Issue by wxa56** [alibaba/testable-mock#118]
因为是私有的，无法直接指定targetClass

**Comment by linfan** [comment]
在它的外部类关联的Mock容器类里定义的Mock方法即可，对内部类中的方法调用同样生效。
具体例子见`demo/java-demo`目录下面的`DemoInnerClass.java`（或`demo/kotlin-demo`的`DemoInnerClass.kt`）文件。

已更新至[FAQ文档](https://alibaba.github.io/testable-mock/#/zh-cn/doc/frequently-asked-questions)😀。

**Comment by wxa56** [comment]
> 在它的外部类关联的Mock容器类里定义的Mock方法即可，对内部类中的方法调用同样生效。
> 具体例子见`demo/java-demo`目录下面的`DemoInnerClass.java`（或`demo/kotlin-demo`的`DemoInnerClass.kt`）文件。
> 
> 已更新至[FAQ文档](https://alibaba.github.io/testable-mock/#/zh-cn/doc/frequently-asked-questions)😀。

thank you
