### ISSUE TITLE
评估放宽测试类名称约定的可行性

### ISSUE THREAD

**Issue by linfan** [alibaba/testable-mock#12]
在`TestableMock`的实现中，由于被测类需要访问定义在测试类中的Mock方法，为了便于处理，默认约定了测试类名称为`被测类名+Test`。虽然绝大多数Java项目均符合此约定，但依然存在特殊场景。

基于实用性考虑，需提供额外机制支持非标准结构项目的测试Mock。

**Comment by mjhgithub** [comment]
如果放宽测试类名，给testable-mock开发带来更高的复杂度和稳定性问题，那得不偿失。其实只要将约定规范提前说明，大家遵循使用也没有问题，我已经看到文档中有说明了，赞！

**Comment by linfan** [comment]
先整体Review看下影响程度~ 肯定是在不影响稳定性的前提下哦

**Comment by zcglisp** [comment]
"测试类与被测类的包路径应相同"，去掉这个约定也在本issues的考虑范围内吗？
被测类调用的类如果不在此包中，现在(0.4.7)还无法mock。
被测类调用的类如果在此包中，现在(0.4.7)可以mock。

**Comment by linfan** [comment]
因为Mock定义在测试类中，但Mock需要在运行时自动生效到被测类里，所以两者之间始终需要有某种方式能关联上。
目前是只能通过同包+名字约定来关联，未来会增加其他可选的关联方式，比如通过注解标识。

这修改计划是放到`0.5`版本之后，在`0.5`版本需要解决“[常见问题](https://alibaba.github.io/testable-mock/#/zh-cn/doc/frequently-asked-questions)”里第8条提到的问题，会对现在的Mock的底层实现机制做一些调整（保持使用体验基本不变），在设计的时候也会为这个Issue做准备。

**Comment by linfan** [comment]
`0.5.0`版本已发布。
参见文档 https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock-with
