### ISSUE TITLE
建议增加或调整注解以充分利用ide的重构功能

### ISSUE THREAD

**Issue by sunnyfun888** [alibaba/testable-mock#120]
目前demo演示的方式存在一个隐患，一旦mock的方法名有变化，mock代码中的方法名如果没有跟着手工调整，mock方法将立即失效且没有任何错误提示，这在某些情况下可能造成致命的后果。
    其实现代ide完全有能力自动同步这些变更，只要mock的类继承(或实现)被mock的类(或接口)。

比如AbcService引用了AbcDao，现在需要mock AbcDao 的方法，可以这么写：

```
@MockWith(AbcDaoMock.class)
class AbcServiceTest {
    
    @Autowired
    private AbcService abcService;
    
    public static class AbcDaoMock implements AbcDao {
        
        @MockMethod(targetClass = AbcDao.class)
        public long doSomeThing1(Integer in) {
            return 1L;
        }

        @MockMethod(targetClass = AbcDao.class)
        public long doSomeThing2(Integer in) {
            return 1L;
        }

    }

    @Test
    void testXxx() {
    }

}
```

但是如果出现更复杂的情况，AbcService 同时引用了AbcDao 和 BcdDao，需要mock AbcDao 的 doSomeThing1 和 doSomeThing2 方法，和 BcdDao 的 doSomeThing3 方法，上面这种写法就失效了，因为@MockWith的入参不支持多个class。如果能支持这种写法：@MockWith({AbcDaoMock.class, BcdDaoMock.class})，上面的场景就能满足了。

但是，仔细分析的话，如果mock的类都继承(或实现)了被mock的类(或接口)，@MockMethod注解在方法上出现了冗余，如果增加一个打在mock类的注解，比如@MockClass(AbcDao.class)，代码将更精简，比如：

```
class AbcServiceTest {
    
    @Autowired
    private AbcService abcService;
    
    @MockClass(AbcDao.class)
    public static class AbcDaoMock implements AbcDao {
        
        public long doSomeThing1(Integer in) {
            return 1L;
        }

        public long doSomeThing2(Integer in) {
            return 1L;
        }

    }

    @MockClass(BcdDao.class)
    public static class BcdDaoMock implements BcdDao {
        
        public long doSomeThing3(Integer in) {
            return 1L;
        }

    }

    @Test
    void testXxx() {
    }

}
```

期待将来能有这些功能。

**Comment by linfan** [comment]
最后提到的这种`MockClass`可行哈，不过好像并不能解决被Mock的方法改名导致Mock失效的问题。此时如果原方法被改名了，即使Mock类继承原目标类，也是相当于子类里定义了父类不存在的方法，IDE和Java编译器都不会给任何提示。

其实Mock和PrivateAccessor防重构问题之前就分别有Issue在跟进，其中PrivateAccessor的防重构已经实现 #21，Mock防重构目前还未完成 #5 ，但方案设计已经做了。大致效果是会在单元测试开始运行前进行统一的Mock目标检查，如果Mock容器类中定义的方法匹配的源目标不存在，则会在单测运行前就报错，阻止单测执行。

近期会先发布下一个大版本`0.6`的功能，Mock校验最早能在`0.6.1`版本里包含。

**Comment by sunnyfun888** [comment]
Mock类继承原目标类，如果使用IDE的重构方法功能，会自动同时修改父类和子类的方法的。 另外子类打上@Override注解，手动改名也是能被IDE探测到的。
所以能解决被Mock的方法改名导致Mock失效的问题。

**Comment by linfan** [comment]
感觉这样做的优点和缺点都很显著，优点是能获得一定程度上的IDE支持，最大的缺点是使用复杂性会显著增加。

这个方案有两种情况覆盖不了。一是被Mock方法所属的类定义了`final`，这种情况无法继承；二是Mock方法里需要引用原目标对象（比如实现调用原方法），`Testable`当前的做法是在方法首位加一个目标所属类的参数，此时Mock方法定义与被Mock目标方法签名就不一致了，不能用`@Override`。

此外会带来一个潜在的歧义问题。当前Mock方法的定义约定若`@MockMethod`注解存在`targetClass`参数，则Mock方法参数与目标方法一致，若不加此参数，则Mock方法的首位参数是目标方法的所属类，这个定义是严格的。而将所属类的定义提到Mock容器类上，用`@MockClass`注解，若遇到Mock方法首位参数与目标类相同时，则理论上存在两种可能：参数与目标方法相同，或首参是目标方法所属类。虽然通过查看原类型中有哪些方法通常能辨别，但会增加的代码阅读难度，与`Testable`保持简单易用的原则不太相符。

考虑到`Testable`当前已有防重构功能计划，目前先不去做这种附加设计了。依然感谢亲的这个议题😀。
