### ISSUE TITLE
mock 工具类中protected final类的方法失败，请教一下怎么改？

### ISSUE THREAD

**Issue by FLMint** [alibaba/testable-mock#122]
![image](https://user-images.githubusercontent.com/31384084/112247776-da8fc800-8c8f-11eb-81bb-8af42179a2c2.png)

工具类：
![image](https://user-images.githubusercontent.com/31384084/112247856-f6936980-8c8f-11eb-9648-5ffd85186ae9.png)
![image](https://user-images.githubusercontent.com/31384084/112247893-00b56800-8c90-11eb-816a-3e339d45b638.png)

**Comment by BigAssBeatYourChest** [comment]
调用方法时没有用到mock的方法，还是调用原方法

**Comment by linfan** [comment]
Mock容器类型是和包含调用代码的被测类关联的哦，看下是不是`Mock`这个类定义到`RedisUtil`的测试类里，而不是发起`setIfAbsent()`调用的代码所在类的测试类里了？

**Comment by BigAssBeatYourChest** [comment]
> Mock容器类型是和包含调用代码的被测类关联的哦，看下是不是`Mock`这个类定义到`RedisUtil`的测试类里，而不是发起`setIfAbsent()`调用的代码所在类的测试类里了？

是定义在发起setIfAbsent()调用的代码所在类的测试类里，结合spock使用的，看了上一个Issue的方法尝试下也没有成功...

**Comment by linfan** [comment]
spock我近期会专门验证一下，0.5版本没有在spock的用例上单独做过验证，可能真的有兼容问题

**Comment by FLMint** [comment]
> spock我近期会专门验证一下，0.5版本没有在spock的用例上单独做过验证，可能真的有兼容问题

好的，感谢

**Comment by linfan** [comment]
问题同 #121 ，请使用`TestableMock`的`0.6.2`或以上版本😃
