### ISSUE TITLE
Android Studio配置testable-mock不生效

### ISSUE THREAD

**Issue by AndroidToolsWu** [alibaba/testable-mock#123]
我打算在Android中使用JUnit + TestableMock(0.5.2版本) + Robolectric进行单元测试的编写，按着文档指引进行配置依赖和gradle命令，并接入了demo里的代码(DemoMock和DemoMockTest类)，可是在运行时报期望与实际不符的问题。 如下图
![企业微信截图_1616639440305](https://user-images.githubusercontent.com/33802014/112409921-4851f780-8d55-11eb-8044-91fbbdadb202.png)

我在Android依赖的lib里可以找到Testable相关资源文件（agent、all、core、processor），推测是jvmArgs在Android Studio里没有生效，导致@MockMethod无法被执行，求助帮忙分析一下具体原因，感谢！
（我的android studio版本是4.1.2 、Gradle版本4.1.2 、targetSdk29）

**Comment by AndroidToolsWu** [comment]
Demo代码如下
[MockitoDemo.zip](https://github.com/alibaba/testable-mock/files/6201673/MockitoDemo.zip)

**Comment by linfan** [comment]
手上暂时没有安装Android Studio和SDK的机器，粗看了一下代码，引入方式应该是正确的，通过`gradle build`执行是否正常呢？

**Comment by AndroidToolsWu** [comment]
进行Build时无法通过，报错如下，看起来是build的时候执行了一遍Test方法，在调用verify("callFromDifferentMethod").withTimes(4);时因没有通过触发了VerifyFailedError的异常

![企业微信截图_16167399338073](https://user-images.githubusercontent.com/33802014/112591335-2df44880-8e3f-11eb-8024-2d6f68847c1d.png)

**Comment by linfan** [comment]
那就是已经正常引入了，出错的测试用例是`should_able_to_mock_static_method`。

看了你的代码，在`DemoMockTest.java`的这个用例里，你把`demoMock.getBox().get()`这行调用注释了，这样后面验证调用次数为1的时候自然就要报`VerfiyFailedError`，因为调用被注释了，实际次数是0。

**Comment by AndroidToolsWu** [comment]
是的，当我把此方法整个去掉的话，build是可以通过的。 但是一运行下图方法
![112409921-4851f780-8d55-11eb-8044-91fbbdadb202](https://user-images.githubusercontent.com/33802014/112778458-2d45f700-9077-11eb-9574-2937dce7ca11.png)

还是会报错

**Comment by AndroidToolsWu** [comment]
不知道有没有交流群？

**Comment by linfan** [comment]
`gradle build`命令是包含执行单元测试的，从前一个图来看，应该只是`should_able_to_mock_static_method`这一个测试失败，其余6个都通过了。后面的这个图是在IDE里运行单个测试用例？

**Comment by AndroidToolsWu** [comment]
是的，单独进行run就会报错

**Comment by AndroidToolsWu** [comment]
就像这样运行
![企业微信截图_16169978695094](https://user-images.githubusercontent.com/33802014/112793329-b0774500-9097-11eb-8c44-24ca8fc8f3f4.png)

**Comment by linfan** [comment]
Gradle单独运行我先验一下，看能否复现~

**Comment by linfan** [comment]
我们主线业务是阿里云的开发者协同平台，这个项目属于是内部孵化的开源产品，建群容易分心，有问题先通过Issue异步处理吧~

**Comment by AndroidToolsWu** [comment]
好的，谢谢你

**Comment by linfan** [comment]
已初步定位是一处与Gradle兼容有关的BUG，影响版本`0.5.2`和`0.6.0`，会在下个版本`0.6.1`中进行修复。
可以暂时先回退到`0.5.1`版本使用，抱歉带来的不好体验，近期会补充Gradle环境的回归测试任务，避免新修改导致的兼容问题。

**Comment by linfan** [comment]
Gradle兼容的问题已在`0.6.1`版本修复，另外今天刚刚发了`0.6.2`版本还修了另一个框架兼容相关的问题，可以直接升级到最新的版本使用哦

**Comment by AndroidToolsWu** [comment]
好的~ 我试一下，要是可以这个issue我就close了

**Comment by AndroidToolsWu** [comment]
还是不行，难道和gradle版本有关？ 是因为这个版本不行吗？
![企业微信截图_16178487042449](https://user-images.githubusercontent.com/33802014/113959022-b0740380-9854-11eb-8631-2d73a3432f73.png)

**Comment by AndroidToolsWu** [comment]
问题的现象和之前一样

**Comment by linfan** [comment]
是和之前的哪一个现象一样呢？
第一帖的那个问题，应该是代码里有一行你注释掉了，导致那个测试会挂。后面的一个问题，我理解现象是”在命令行执行`gradle build`是通过的，只是在IDE里运行单个测试会报错“，是吗？

**Comment by linfan** [comment]
在Gradle的配置只是让启动单元测试的时候追加一个jvmArgs参数，应该和Gradle版本关系不大。
麻烦再贴一个现在错误的报错信息，另外版本是用的`0.6.2`吧？

**Comment by AndroidToolsWu** [comment]
就是与预期结果不一致的问题，调用这一行的时候就已经验证失败了，后边的case都不走了。 在ide手动run和build都会在这里报错然后停止。
`assertEquals("mock_one_mock_others", demoMock.callerOne() + "_" + demoMock.callerTwo());`

**Comment by AndroidToolsWu** [comment]
报错和上边run的和gradlew build出现的错误一样，截图在上方

**Comment by AndroidToolsWu** [comment]
运行在0.6.2版本

**Comment by linfan** [comment]
从2楼中提供的代码来看，”should_able_to_get_source_method_name“用例的运行不应该报错。

我仔细看了前后的图，在第4楼的图中，显示的错误信息是”7 tests completed, 1 failed“，失败的用例是”should_able_to_mock_static_method“，此时”should_able_to_get_source_method_name“用例是通过的。

然后”should_able_to_mock_static_method“用例失败的原因，我在第5楼回复了。

之后”should_able_to_get_source_method_name“用例报错应该是还有其他代码修改引起的，可以仔细检查一下，或者能否提供一下最后这个版本的完整代码？

**Comment by AndroidToolsWu** [comment]
[TestableMockDemo.zip](https://github.com/alibaba/testable-mock/files/6300766/TestableMockDemo.zip) 
代码在这里，因文件大小限制，我删除了自动生成的build文件

**Comment by albuswhite** [comment]
我这边也是用AS，项目的demo中的mock也是都无法生效，全是用例失败

**Comment by linfan** [comment]
我在Gradle工程里对新的zip包里的代码做了验证，除去`test_should_able_to_set_mock_context`这个case因为你删了原示例中的`MOCK_CONTEXT.put("case", "special_case");`这样代码，会导致测试失败，其他的用例，包括`should_able_to_get_source_method_name `都是通过的。

从Android官方的[Gradle Plugin和Gradle版本对应表](https://developer.android.google.cn/studio/releases/gradle-plugin)来看，`com.android.tools.build:gradle:4.1.2`应该对应于`Gradle 6.5+`，已经属于比较新的版本，应该也不会是Gradle版本问题。

我这里暂时没有可用的Android Studio和Android SDK的环境，无法做更进一步的调查。这个Issue先保留，有相关信息会再更新。

**Comment by linfan** [comment]
> 我这边也是用AS，项目的demo中的mock也是都无法生效，全是用例失败

@albuswhite 从前述问题来看，AS可能存在部分用例不通过的情况。如果全部用例失败，更可能是配置引入`TestableMock`时候的问题。可先参考[自助问题排查](http://freyrlin.gitee.io/testable-mock/#/zh-cn/doc/troubleshooting)文档，检查是否生成了`testable-agent.log`运行日志。

**Comment by albuswhite** [comment]
AS这边我今天又试了一下，你这个log文件我在as运行下怎么也找不到。不过我成功运行了，解决问题是参考的那个关于eclipse的 vm options

**Comment by Nelson-KK** [comment]
> AS这边我今天又试了一下，你这个log文件我在as运行下怎么也找不到。不过我成功运行了，解决问题是参考的那个关于eclipse的 vm options

能看下demo工程吗

**Comment by linfan** [comment]
已增加完整的[Android Demo](https://github.com/alibaba/testable-mock/tree/master/demo/android-demo)
