### ISSUE TITLE
使用testable-mock+jacoco， 收集到的覆盖率为0%

### ISSUE THREAD

**Issue by lyxiaobei** [alibaba/testable-mock#124]
插桩方式：在线插桩

**Comment by linfan** [comment]
`on-the-fly`覆盖率应该是不受`TestableMock`影响的，需要更多的信息，是Maven还是Gradle？

**Comment by lyxiaobei** [comment]
maven

**Comment by linfan** [comment]
去掉`TestableMock`依赖以后覆盖率就恢复吗？
应该是加Testable JavaAgent的时候没有保留Jacoco JavaAgent的原因，有两种可能：
1. 没有加`@{argLine}`
2. 在`jacoco-maven-plugin`上有`propertyName`参数将默认的argLine参数改名了，参考 #107

**Comment by linfan** [comment]
从原理来说，`TestableMock`是原位替换字节码，不会干扰`Jacoco`覆盖率采集

**Comment by linfan** [comment]
如果没有更多问题，这个issue先关闭了哦
