### ISSUE TITLE
Class not loaded : com.alibaba.testable.core.tool.TestableTool 

### ISSUE THREAD

**Issue by hyperleoon** [alibaba/testable-mock#125]
use MOCK_CONTEXT with Mockito，rais Class not loaded : com.alibaba.testable.core.tool.TestableTool error

@Service
public class FooService {

    public String hello() {
        return "hello";
    }
}

@Service
public class DemoService {

    @Autowired
    private FooService fooService;

    public String hello() {
        return fooService.hello();
    }
}

// test
public class DemoServiceTest {

    @Mock
    private FooService fooService;

    @InjectMocks
    private DemoService demoService;

    public void before() {
        MockitoAnnotations.initMocks(this);
    }

    @MockMethod(targetClass = FooService.class)
    public String hello() {
        switch ((String)MOCK_CONTEXT.get("case")) {
            case "one":return "mock_one";
            case "two":return "mock_two";
            default:return "mock";
        }
    }

    @Test
    public void test_hello() {
        MOCK_CONTEXT.put("case","one");
        demoService.hello();
        MOCK_CONTEXT.put("case","two");
        demoService.hello();
    }
}

![image](https://user-images.githubusercontent.com/39700308/112575512-6558fa00-8e2b-11eb-846d-409d0caf110f.png)

**Comment by linfan** [comment]
You could just ignore this error, there are some bytecode modification applied to MOCK_CONTEXT before test execution, so the IDE cannot show this variable as it was, it won't effect the whole debug process.

**Comment by hyperleoon** [comment]
![image](https://user-images.githubusercontent.com/39700308/112785097-d267cc00-9085-11eb-933f-2e6dfbe48da1.png)

it will cause npe

**Comment by linfan** [comment]
According to this issue and #126 , it's very likely that the testable-agent hasn't been correctly configured in context. (`MOCK_CONTEXT` is literally defined as null if byte code modification not happening, also mocks in #126 not working)

Check the `pom.xml` or `build.gradle` file, if the `testable-agent.jar` part is missed.

In the coming `0.6.1` version, some more diagnose information will be added for self-troubleshooting, which I think would make it easier to find out the issue.

**Comment by linfan** [comment]
Could you try `0.6.2` version (or `0.6.1`), and have a look in the `testable-agent.log` file according to the [troubleshooting](https://alibaba.github.io/testable-mock/#/en-us/doc/troubleshooting) doc ? thanks.

**Comment by hyperleoon** [comment]
Actually i miss testable-agent.jar part in pom.xml，testable-agent.log is readly helpful from 0.6.2 version. thanks for your support!
