### ISSUE TITLE
PrivateAccessor injects private variables, the mock method does not take effect

### ISSUE THREAD

**Issue by hyperleoon** [alibaba/testable-mock#126]
@Service
public class FooService {

    public String hello() {
        return "hello";
    }
}

@Service
public class DemoService {

    @Autowired
    private FooService fooService;

    public String hello() {
        return fooService.hello();
    }
}

// test
public class DemoServiceTest {

    private DemoService demoService = new DemoService();

    @MockMethod(targetClass = FooService.class)
    public String hello() {
        return "nock";
    }

    @Test
    public void test_hello() {
        PrivateAccessor.set(demoService,"fooService",new FooService());
        System.out.println(demoService.hello());
    }
}

![image](https://user-images.githubusercontent.com/39700308/112591086-c63dfd80-8e3e-11eb-8ece-88c5c6bd1c88.png)

version:0.5.2

**Comment by linfan** [comment]
For version `0.5.x`, the mock method have to be defined in a "mock container class", as described [in doc](https://alibaba.github.io/testable-mock/#/en-us/doc/use-mock).

There's no problem with the `PrivateAccessor` 😀.

**Comment by hyperleoon** [comment]
![image](https://user-images.githubusercontent.com/39700308/112779238-d93c1200-9078-11eb-8425-a664d51041fe.png)
not work...

**Comment by hyperleoon** [comment]
Actually i miss testable-agent.jar part in pom.xml，testable-agent.log is readly helpful from 0.6.2 version. thanks for your support!
