### ISSUE TITLE
执行junit时报错

### ISSUE THREAD

**Issue by wenjiech** [alibaba/testable-mock#127]
java.lang.ClassFormatError:Duplicate method name&signature in class file com/。。。。。
请问一下这个是什么问题？
spring boot项目 
谢谢

**Comment by linfan** [comment]
像是Testable生成的某个方法和原类型里的方法恰好重名了，或者由于某种原因同一个类被处理了两次。
报错的这个类型是一个要测的业务类吗？（或者是测试类 / Mock容器类 / 其他无关的类？）

**Comment by wenjiech** [comment]
是spring boot的启动类
com/test/ServerApplication$$EnhancerBySpring$$abe994e

**Comment by wenjiech** [comment]
> 像是Testable生成的某个方法和原类型里的方法恰好重名了，或者由于某种原因同一个类被处理了两次。
> 报错的这个类型是一个要测的业务类吗？（或者是测试类 / Mock容器类 / 其他无关的类？）

是spring boot的启动类
com/test/ServerApplication$$EnhancerBySpring$$abe994e

**Comment by linfan** [comment]
初步看起来和`0.6.0`版本放宽了字节码处理目标类型有关，如果是Maven项目可以先试下`0.5.2`版本是否可行，Gradle项目建议使用`0.5.1`版本。这个问题预计在下个版本里能修复。

**Comment by linfan** [comment]
可以升级到`0.6.2`版本了哈，上述问题已修复
