### ISSUE TITLE
mock不生效

### ISSUE THREAD

**Issue by rock2016** [alibaba/testable-mock#128]
### 运行结果
![代码](https://user-images.githubusercontent.com/18436562/112964656-1c7ea980-917b-11eb-9760-df68bb081f04.png)
### 已经引用包
![引用包](https://user-images.githubusercontent.com/18436562/112964819-3e782c00-917b-11eb-8e72-2d01c17e5a4e.png)

**Comment by rock2016** [comment]
是直接引用官方提供demo中的代码。

**Comment by linfan** [comment]
单从这两张图确实只能看出是没生效，可以先参考[自助排查文档](http://freyrlin.gitee.io/testable-mock/#/zh-cn/doc/troubleshooting)在Mock类上加上`@MockDiagnose(LogLevel.VERBOSE)`，看一下输出的情况。

**Comment by rock2016** [comment]
增加@MockDiagnose(LogLevel.ENABLE) ，没有多余的输出。
gradle配置### 
 testImplementation('com.alibaba.testable:testable-all:0.6.0')
  testAnnotationProcessor('com.alibaba.testable:testable-processor:0.6.0')

**Comment by linfan** [comment]
Gradle工程在当前的项目回归测试里没有包含，目前已经确定从`0.5.2`版本开始的一个修改导致了Gradle构建的兼容有问题，建议先使用`0.5.1`版本。
在近期会发布新版本进行修复，同时将Gradle纳入到回归测试中，抱歉带来不好的使用体验。

**Comment by rock2016** [comment]
使用0.5.1的时候还是mock生效。

**Comment by rock2016** [comment]
使用0.5.1还是未生效。

**Comment by linfan** [comment]
如果是通过IntelliJ运行的话，看下是不是改完`build.gradle`没有更新本地IDE缓存哈？
IntelliJ编辑`build.gradle`内容以后，编辑器右上角会出现一个小小的刷新按钮，需要点击一下才会生效。见下图：
![reload-gradle](https://user-images.githubusercontent.com/1113435/113475691-c3c84d00-94a9-11eb-8e62-48d2e91177ed.jpg)

目前Gradle兼容问题的原因已经定位了，会在`0.6.1`版本里修复。

**Comment by linfan** [comment]
`0.6.1`版本已发布，包含Gradle编译的BUG修复，同时今天新发的`0.6.2`版本又修了一处兼容性相关的BUG。
可以试一下升级到最新版本使用~
