### ISSUE TITLE
可以mock mybatis plus dao service接口么

### ISSUE THREAD

**Issue by loululin** [alibaba/testable-mock#13]
我这边 mock mybatis plus dao service接口 启动UT报错

**Comment by loululin** [comment]
是否可留个 mock mybatis plus dao 的demo

**Comment by linfan** [comment]
错误信息和被测方法的大致情况能贴一下吗？

**Comment by loululin** [comment]
kotlin demo中 没有看到接口方法 mock的例子，，

**Comment by linfan** [comment]
我抽空补一个Case做个验证，我理解你的问题是Mock`在Service对象里对Dao接口方法的调用`报错了对吧？

**Comment by loululin** [comment]
对的

**Comment by loululin** [comment]
您好，mock mybatis plus 接口的demo有了么，想参考一下

**Comment by linfan** [comment]
单独示例还没有写，但是我在内部实际项目里找到了有这种用法的地方，确定是可行的。

先再确认一下你是指Service调用Dao的测试，还是Dao调用Mapper的测试。如果Service调用Dao的话肯定可行，因为Dao就是普通类，这个代码我就不贴了。Dao调用Mapper稍微特殊一点，因为Mapper实现类是Mybatis动态生成的。实际这两种情况都适用。我贴一个Dao调用Mapper的例子，只包含相关部分代码（类型名脱敏用Xxx代替）：

被测类

```
public class ReqXxxDAO extends BaseDAO {
    private XxxReqMapper reqMapper;

    public String getNum() {
        ... ... // 省略无关代码
        return reqMapper.getXxxNum(param);
    }
}
```

测试类

```
public class ReqXxxDAOTest {

    private ReqXxxDAO dao = new ReqXxxDAO();

    @MockMethod
    Integer getXxxNum(XxxReqMapper r, QueryParam param) {
        return ...;  // 此处有一些基于param的判断逻辑，省略
    }

    @Test
    public void testGetNum() {
        assertEquals(1, dao.getNum());
    }

}
```

你可以提供一些详细的信息，遇到的错误是什么，相关代码是怎样的。

**Comment by loululin** [comment]
谢谢您的回复先，dao是接口(kotlin)，类似：
```kotlin
/**
 * <p>
 * 钱包交易流水记录表 Mapper 接口
 * </p>
 *
 * @author loulvlin
 * @since 2020-12-23
 */
interface WalletTradeDetailMapper : BaseMapper<WalletTradeDetail>
```
想问下，可以mock BaseMapper中的等方法么，如 'T selectById(Serializable id);' 这种？

**Comment by linfan** [comment]
可以的，唯一需要注意的是如果在DAO对象中定义的Mapper是子类型的（如`WalletTradeDetailMapper`），即使调用继承自父类型（如`BaseMapper`），在定义Mock方法时，首位的参数应该使用子类类型。在文档的[常见问题](https://alibaba.github.io/testable-mock/#/zh-cn/doc/frequently-asked-questions)中也有提到。

**Comment by leige1027** [comment]
@linfan 你好，如果是service 调用 dao,  dao继承mybatis中 basemapper中的通用方法 list<T> select(T t),怎么mock,我这边在service中，@MockMethod 了dao层这个通用的select方法，但是单元测试类还是走了真实的调用请求了数据库
