### ISSUE TITLE
建议赶紧隐藏这个项目，就代码里面那些个各种下划线和命名，就真的业余到家了...

### ISSUE THREAD

**Issue by rogerchina** [alibaba/testable-mock#133]

**Comment by linfan** [comment]
本项目代码风格和命名遵循[阿里巴巴Java编码规约](https://edu.aliyun.com/course/417)。

猜测亲指的下划线命名是`TestableMock`生成的字节码中有部分使用双下划线开头的私有成员变量和方法，此处设计是为了避免运行时注入的成员名与原类型中的原生Java成员发生意外重名，故意采用了不符合常规Java命名风格的名称。类似的做法例如`CGLIB`使用带`$$EnhancerByCGLIB$$`或`$$EnhancerBySpringCGLIB$$`尾缀对运行时注入的类型命名。如果亲有更好的命名建议，欢迎针对具体代码提出建议。

另一处带有下划线风格的命名的地方是示例中的单元测试方法名，统一采用了`should_xxx`的命名规范，这是一种相对`testXxx`命名更少被使用，但更贴近业务语义，具有更丰富表达力的单元测试命名方式。在[《码出高效：Java 开发手册》](https://book.douban.com/subject/30333948/)一书的单元测试章节中，有关于这几种单元测试命名规则的详细讨论。针对其中的利弊权衡，同样欢迎针对具体的场景进行详细讨论。

**Comment by rogerchina** [comment]
算了，满眼这，我也真不敢看了，别强调*具体代码*四个字了。就事论事，无意冒犯。除了开源作者，凡是意见相左的，都他妈给我滚。都多跟开源项目提建议，不是在我这里瞎他么点。

**Comment by rogerchina** [comment]
NC太多了
