### ISSUE TITLE
Eclipse中Mock不生效

### ISSUE THREAD

**Issue by YM-zero** [alibaba/testable-mock#134]
![截图](https://user-images.githubusercontent.com/82324794/114309631-66bc3f00-9b1a-11eb-9345-0296bf4b93a7.png)

**Comment by YM-zero** [comment]
直接使用的java-demo中的代码

**Comment by linfan** [comment]
Eclipse使用基于JavaAgent的工具相对比较繁琐，具体可参考[在IDE中运行单元测试](https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-in-ide)文档
