### ISSUE TITLE
与Clover不兼容 v0.6.2

### ISSUE THREAD

**Issue by brucecui** [alibaba/testable-mock#136]
抱歉，运行结果在内网，只能部分截图。总之添加@MockDiagnose(LogLevel.VERBOSE)之后可以看到大量与Clover相关的信息。如果从Gradle中去掉Clover，Mock可以生效。

![image](https://user-images.githubusercontent.com/889934/114385265-611a3400-9bc2-11eb-8028-b61977ef6308.png)
![image](https://user-images.githubusercontent.com/889934/114385492-afc7ce00-9bc2-11eb-96cb-52bc5d2db2f6.png)

**Comment by linfan** [comment]
从截图来看应该是个BUG，我会尝试复现一下

**Comment by linfan** [comment]
从报错的地方来看，`Clover`似乎会在Mock类里生成一个非静态，但却不含有`this`引用的方法，导致`Testable`在方法中获取`this`引用时下标溢出（`this`总是在方法局部变量列表的首位，因此代码里直接取下标`0`，然而这个方法的局部变量列表为空）。在下个版本里我们会对这种特殊情况加上处理，尝试修复。

由于使用`Clover`需要License，我没有找到适合用于复现问题的项目，无法直接查看`Clover`对类型做了什么修改，能创造出不含`this`引用的非静态方法。**如果有可能的话**，您可以在截图中报错的内部类Mock上加上一个`@DumpTo`注解，这个注解会将此Mock类的实际字节码保存到本地，然后将本地生成的一个`.class`发送给我（jinji.lf@alibaba-inc.com），这将有助于我们更有针对性的修复此问题。例如：

```java
public class XxxTest {

    // 加此注解然后执行一次单元测试
    // 在该工程的build/testable目录下面应该能找到一个class文件
    @DumpTo("build/testable")
    public static class Mock { ... }

}
```

**Comment by brucecui** [comment]
多谢。周一我会尝试一下。主要是运行环境在内网，不能传到公网。我试着想想办法。

**Comment by brucecui** [comment]
你好，我dump了class，但是没有办法发到外网。Clover的license只有内网有。

生成的class大概1k左右。不知道我能不能从这边直接提取到你需要的信息。可行的话麻烦告知方法。

另外我看了下项目的构建class output目录，好像clover会给每个类额外生成两个class， 以类似“$__CLR4_0_3xxxxx..."这样的后缀结尾。上面的截图里也能看到类似的信息 （抱歉我把原始类路径类名擦掉了）。不知道这样的信息有没有帮助。
![image](https://user-images.githubusercontent.com/889934/115175732-24889400-a0fe-11eb-89e3-ad5485fb5acb.png)

**Comment by linfan** [comment]
`0.6.3`已经发布了，包含对这种情况的适配，可以试一试是否修复了这个问题。

如果依然不行，可以在命令行用`javap -p -c -l -v <class文件>`把class文件的字节码内容打印出来，然后把内容脱敏了发给我哈

**Comment by brucecui** [comment]
你好，早上试了一下。暂时仍然报错。从日志看，这次exception里的Index从0变成了1.
![image](https://user-images.githubusercontent.com/889934/115318141-b43a4b00-a1af-11eb-8396-8783acb8d850.png)

我dump了class，javap打印的字节码截图如下（抱歉！）。
我是在一个已经存在的PowerMock的testcase上改的。所以除了clover还可以看到powermock。新添加Testable的内容只是mock了一个简单的String.trim.
![image](https://user-images.githubusercontent.com/889934/115318189-d6cc6400-a1af-11eb-8fd1-13f86f13a738.png)
![image](https://user-images.githubusercontent.com/889934/115318213-e6e44380-a1af-11eb-8ba4-b784d2c19d79.png)
![image](https://user-images.githubusercontent.com/889934/115318243-f6638c80-a1af-11eb-965c-c566c949bbb5.png)

**Comment by linfan** [comment]
报错的位置是还有另一处假设非静态方法有`this`引用的地方，尝试往局部变量表下标1的位置插入值（原意是避开下标0的`this`引用），这个问题下次发布的时候会处理。

从`javap`打印的内容来看，trim()方法的`locals`值是4，因此方法局部变量表应当不为空，但没有看到`LocalVariableTable`部分的输出，不知是确实没有打印还是你去掉了。如果确实没有打印则不排除是经过PowerMock+Clover处理过后的字节码无法读取局部变量表内容，我先按这个假设看能否修复。

**Comment by brucecui** [comment]
我只替换了路径，包，和类名。行号在截图中是连续的。可能确实没有打印。

**Comment by linfan** [comment]
之前的报错位置在`0.8.4`版本已经处理，可以试试看是否修复此问题

**Comment by brucecui** [comment]
不好意思没有及时回复。我会尽快测试。多谢！

**Comment by brucecui** [comment]
> 之前的报错位置在`0.8.4`版本已经处理，可以试试看是否修复此问题

不好意思，public repo里最晚到`0.6.5`. 上面的版本是`0.**6**.4`吗

![image](https://user-images.githubusercontent.com/889934/117271511-d6f58080-ae8c-11eb-96c3-9ca375e7c566.png)

**Comment by linfan** [comment]
前面是笔误哈，修复是在`0.6.4`版增加的
直接用新的`0.6.5`版本试试吧~

**Comment by brucecui** [comment]
刚刚测试了一下，似乎还是有问题。Log截图：
![image](https://user-images.githubusercontent.com/889934/117407577-55abf580-af41-11eb-81b4-c5e87d1e3d6f.png)
![image](https://user-images.githubusercontent.com/889934/117407619-62c8e480-af41-11eb-811e-22e78c3c11d0.png)
![image](https://user-images.githubusercontent.com/889934/117407676-74aa8780-af41-11eb-859b-31998ffd02f4.png)
![image](https://user-images.githubusercontent.com/889934/117407697-7e33ef80-af41-11eb-8f65-0b60c724000d.png)

**Comment by linfan** [comment]
从错误信息来看很难直接猜测出原因。
报错位置在`BaseClassHandler.java`的23行：
![image](https://user-images.githubusercontent.com/1113435/117480129-c7149400-af93-11eb-8754-142786f653f7.png)

这里打印的是异常堆栈里最后一个来自`com.alibaba.testable`包的位置，所以实际位置可能在`accept()`调用内部，错误为`NullPointerException`。结合上下文，此处`cn`对象不可能为空，否则前面已经报错了，所以空对象应该是前一行代码刚刚new出来的`cw`对象，在`accept()`内部抛错。

但从目前能看到的信息，无法解释为何刚刚new出来的`cw`对象会为空。感觉这个Case暂时应该无法推进了，看未来是否能遇到类似问题，在有现场的情况下做进一步排查。
