### ISSUE TITLE
私有方法的Mock必须放到Mock类中，会与Mockito不兼容

### ISSUE THREAD

**Issue by Michael-Hsu** [alibaba/testable-mock#137]
有时Mockito需要和TestableMock配合使用，在使用TestableMock的mock私有方法的功能时，0.5版本及以后必须要把私有方法放到一个名为Mock的类中，会导致与Mockito的@Mock注解使用冲突，能否换一个名字，例如MockClass

**Comment by linfan** [comment]
问题收到，会在下个版本里支持配置默认的内置Mock容器类名

**Comment by linfan** [comment]
`0.6.3`版本已支持自定义内部Mock类的名称。
参考[全局运行参数](http://freyrlin.gitee.io/testable-mock/#/zh-cn/doc/javaagent-args)，在`testable.properties`配置文件添加以下内容即可：

```
mock.innerClass.name = MockClass
```
