### ISSUE TITLE
OmniConstructor  该方法的newInstance这个方法，不能实例Date类型的数据，会报stackOverException

### ISSUE THREAD

**Issue by wangyong58566** [alibaba/testable-mock#138]
com.alibaba.testable.core.tool.OmniConstructor

麻烦修改一下com.alibaba.testable.core.util.TypeUtil#isBasicType  加入|| clazz.equals(Date.class); 
public static boolean isBasicType(Class<?> clazz) {
    return clazz.isEnum() || clazz.equals(Integer.class) || clazz.equals(Short.class) || clazz.equals(Long.class)
        || clazz.equals(Byte.class) || clazz.equals(Character.class) || clazz.equals(Float.class)
        || clazz.equals(Double.class) || clazz.equals(Boolean.class) || clazz.equals(Class.class)
        || clazz.equals(String.class) || clazz.equals(Date.class);
}

**Comment by wangyong58566** [comment]
麻烦在新的版本解决该问题

**Comment by linfan** [comment]
收到，感谢精确定位问题😃

**Comment by linfan** [comment]
`0.6.3`版本已包含此修改
