### ISSUE TITLE
使用mockScope=associated生效范围的几个问题

### ISSUE THREAD

**Issue by GodwinHub** [alibaba/testable-mock#139]
1.将pom文件中的plugin配置为mockScope=associated，想仅对Mock容器关联测试类中的测试用例生效，但是静态模块中的方法如果Mock还是需要将生效范围置为GLOBAL，我的应用场景是使用TestableMock代替了PowerMock+Mockito，JUnit单独写，对于同一个被测类有PowerMock+Mockito和Junit两个单测，所以修改为仅对Mock容器关联测试类中的测试用例生效，想对JUnit不生效，但是静态模块中的方法还是会全局生效，有没有什么解决办法，或是增加个注解让Mock的生效范围更有针对性，或是增加个注解让不希望生效的测试类使用
2.mockScope=associated时，复用Mock方法，继承的BasicMock类中的Mock方法还是需要置为GLOBAL，仍然会全局生效，其实只是希望对继承了这个方法的Mock容器类的关联测试类生效
3. 参数pkgPrefix的使用能否在testable-aggregate工程里增加个使用案例

**Comment by linfan** [comment]
前几天就看到你的问题了，看完没太Get到意思就搁置了，抱歉现在才回复。
1. 是指每个业务类型你都会写两个单元测试，但希望`TestableMock`只对其中一个测试生效？为什么会需要这样混合使用呢？
2. 当前的实现确实未将Mock容器父类中的方法与其测试用例关联，只有将父类方法的`scope`参数设置为`GLOBAL`才能生效。这是一处需要功能增强的地方。
3. `pkgPrefix`主要是用于在大型工程里缩小Mock类和相关业务类的搜索范围，从而提升单测启动速度，从前两个问题来看，我感觉它的当前功能并不适合你的场景。具体用法，譬如在实例项目中，可以加上`pkgPrefix=com.alibaba.demo.basic,com.alibaba.demo.one2multi`参数将`TestableMock`的作用范围限制在上述的两个包中。

**Comment by GodwinHub** [comment]
> 前几天就看到你的问题了，看完没太Get到意思就搁置了，抱歉现在才回复。
> 
> 1. 是指每个业务类型你都会写两个单元测试，但希望`TestableMock`只对其中一个测试生效？为什么会需要这样混合使用呢？
> 2. 当前的实现确实未将Mock容器父类中的方法与其测试用例关联，只有将父类方法的`scope`参数设置为`GLOBAL`才能生效。这是一处需要功能增强的地方。
> 3. `pkgPrefix`主要是用于在大型工程里缩小Mock类和相关业务类的搜索范围，从而提升单测启动速度，从前两个问题来看，我感觉它的当前功能并不适合你的场景。具体用法，譬如在实例项目中，可以加上`pkgPrefix=com.alibaba.demo.basic,com.alibaba.demo.one2multi`参数将`TestableMock`的作用范围限制在上述的两个包中。

对于第一个问题我是这样理解的，JUnit的目的是为了本地调用测试环境进行单测，完成代码与环境数据或是测试库数据的接洽，验证代码实际执行的正确性，使用PowerMock+Mockito写这这套全Mock数据的单测，目的是为了将实际环境数据不易覆盖到的判断分支都验证一下，所以有了这两种单测。
pkgPrefix我又看了一下确实不符合我的使用场景，感谢指正。

**Comment by linfan** [comment]
问题2 已在`0.6.5`版本修复，父类中的Mock方法现在支持`ASSOCIATED`的scope了
