### ISSUE TITLE
[ERROR] 错误: 找不到或无法加载主类 @{argLine}

### ISSUE THREAD

**Issue by 100Continue** [alibaba/testable-mock#14]
添加@{argLine} 之后，mvn test报错

**Comment by linfan** [comment]
如果pom文件里没有引用Jacoco的时候，不要加`@{argLine}`这个变量哦

**Comment by linfan** [comment]
`@{argLine}`变量是为了引用Jacoco或其他带JavaAgent的插件参数，避免把其他插件的配置覆写掉，如果没有这类插件存在，是引用不到`@{argLine}`变量的

**Comment by kofkyobsa** [comment]
@linfan 我们使用mvn 命令直接执行jacoco ,覆盖率为0,
命令: mvn clean test org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar, 
所以才加的这个参数

**Comment by linfan** [comment]
通过命令行加载`jacoco-maven-plugin`的话应该不用加`@{argLine}`，覆盖率跌零的问题我先试复现一下~

**Comment by linfan** [comment]
确实是被覆写了，如果`jacoco-maven-plugin`不是在pom文件里使用而是从命令行加载的，文档实例的两种写法都不适用。
实际运行时候Jacoco的配置会被覆盖，导致无法生成`jacoco.exec`覆盖率文件，而且这种情况下通过`@{argLine}`变量也无法读取到Jacoco的配置。

解法是这样的，把`pom.xml`文件里`maven-surefire-plugin`的`<argLine>`去掉，让TestableMock也通过命令行来引用：

```
mvn clean com.alibaba.testable:testable-maven-plugin:prepare test org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
```

确保`com.alibaba.testable:testable-maven-plugin:prepare`这个写在`test`之前即可。

**Comment by 100Continue** [comment]
@linfan 我们这边通过在pom文件中加入jacoco插件，同时加入@{argLine}入参。就可以正常使用命令行调用了。
你回复的这个方式，需要修改持续集成服务的命令行方式，对平台侵入性较高。推行的成本会高一些。

**Comment by npvip** [comment]
> @linfan 我们这边通过在pom文件中加入jacoco插件，同时加入@{argLine}入参。就可以正常使用命令行调用了。
> 你回复的这个方式，需要修改持续集成服务的命令行方式，对平台侵入性较高。推行的成本会高一些。

能给下参考方法吗？

**Comment by Fouy** [comment]
> @linfan 我们这边通过在pom文件中加入jacoco插件，同时加入@{argLine}入参。就可以正常使用命令行调用了。
> 你回复的这个方式，需要修改持续集成服务的命令行方式，对平台侵入性较高。推行的成本会高一些。
  @100Continue  能不能提供下是咋配置的 ？

**Comment by linfan** [comment]
@ningtalk @Fouy demo实例里的pom文件是包含jacoco插件的，可以参考
https://github.com/alibaba/testable-mock/blob/master/demo/java-demo/pom.xml
