### ISSUE TITLE
OmniConstructor新建对象中包含BigDecimal对象构建报错

### ISSUE THREAD

**Issue by kxxfydj** [alibaba/testable-mock#145]
描述如题，无法新建包含BigDecimal属性的对象
![image](https://user-images.githubusercontent.com/17681179/115983197-57d19400-a5d2-11eb-89a6-ffe93e0a7799.png)
应该和之前的Date无法创建一样的原因

**Comment by linfan** [comment]
类似原因，但加类型白名单只是一种绕过的办法，近期会研究一下是能否彻底解决这个问题

**Comment by linfan** [comment]
已在`0.6.5`版本彻底修复~
