### ISSUE TITLE
复用父类的Mock方法后，实际并没有调用

### ISSUE THREAD

**Issue by DavidGSX** [alibaba/testable-mock#147]
通过继承方式复用父类的Mock方法，在执行测试用例时，日志显示有调用
[DIAGNOSE] Line 61, mock method "sendMsg" used
但是子类在verify("sendMsg").withTimes(1);时报错
Expected times: 1
Actual times: 0
com.alibaba.testable.core.error.VerifyFailedError: 

在父类方法中手动打印自定义的日志，也没有输出
在父类方法中断点调试，断不到点
虽然打印了DIAGNOSE日志，但是实际并没有调用
在源码中打印调用日志，发现调用到源码，并没有调用父类的Mock方法
如果将父类的Mock方法放到当前测试用例的Mock中，可以正常调用

**Comment by linfan** [comment]
估计调用次数统计的地方对继承的方法处理有问题，基本可以确定是BUG，原因近期会排查

**Comment by linfan** [comment]
Mock方法未进入应该与`scope=associated`情况下对Mock类继承的一处BUG（ #139 ）有关，已经在`0.6.5`版本修复，请验证

**Comment by ghbdong** [comment]
我使用的0.6.6版本，依然存在父类不可用的问题，将父类方法放到子类，mock有效
![image](https://user-images.githubusercontent.com/13817423/121625948-0ceadd80-caa7-11eb-9025-06ee9798ba3b.png)
![image](https://user-images.githubusercontent.com/13817423/121625969-1aa06300-caa7-11eb-9077-4fc3688493f6.png)

**Comment by linfan** [comment]
当Mock类内容完全为空时，存在无法将该类正确识别为Mock类的BUG。改问题已经在`0.6.7`版本修复。
