### ISSUE TITLE
私有方法参数包含List类型，执行无效

### ISSUE THREAD

**Issue by jiangbingi** [alibaba/testable-mock#15]
1.定义了一个私有打印集合方法
`private void printList(List<String> str) {
        System.out.println(str);
    }`
2.在测试类里面传入list并调用，发现控制台没有任何输出，换成单个字符串是可以的

**Comment by linfan** [comment]
问题已定位，是由于内部类型匹配的一个BUG导致的，方法参数类型为接口的时候会调用失败。预计在这周内发布下个版本修复哈~

**Comment by linfan** [comment]
已发布`0.4.4`版本，修复了这个问题，可以试试哈

**Comment by jiangbingi** [comment]
已解决，有个实践问题想问下，就是我要模拟一个远程客户端调用超时或者各种错误类型，这个应该怎么写呢，我原本是想每一种情况定义一个mock方法，但是好像在同一个类是不行的，得拆分几个类？还有就是verify方法调用次数是根据方法名的，如果要mock方法有重名的话是累计计算的，怎么能够够精确一些

**Comment by linfan** [comment]
Mock方法里能接收到实际调用的参数，可以在方法里加一些根据入参进行判断的逻辑，返回不同类型的错误。
如果要Mock的方法有重名，为了在verify的时候做区分，可以把原方法名放到`@MockMethod`注解的`targetMethod`参数里，这样Mock方法本身就可以起不同名字区分开了。

**Comment by jiangbingi** [comment]
这样第一个侵入性比较强，有些参数满足不了得添加一些控制参数，实际上这些参数只是测试用实际业务并没有。mock逻辑都写在一个方法里，复杂一点的话可能代码比较长，按照之前写的习惯，更倾向于一种测试用例一个方法，对于一个mock对象不同表现对象不同块，最后按测试场景按需组装不同的方法

**Comment by linfan** [comment]
是个普遍问题哈🤔

一种轻量的解法是在TestableMock里增加控制参数注入的机制，已创建[issue-17](https://github.com/alibaba/testable-mock/issues/17)，看看是否有更好的建议。
