### ISSUE TITLE
idea+maven环境，demo的mock单测未生效，tag

### ISSUE THREAD

**Issue by Rayyliu** [alibaba/testable-mock#151]
![image](https://user-images.githubusercontent.com/45362242/116510600-be6af080-a8f7-11eb-957a-083faa266039.png)

**Comment by linfan** [comment]
看下单测运行过后，在`java-demo/target`目录下面是否有生成`testable-agent.log`日志文件？
另外，只有这一个用例未生效，还是所有的用例都无法通过？

**Comment by Rayyliu** [comment]
> 没有生成`testable-agent.log`日志说明Testable的JavaAgent在单元测试时没有正确加载。是否有修改过项目的`pom.xml`文件，尤其是下面这部分内容？
> 
> ```
> <plugin>
>     <groupId>org.apache.maven.plugins</groupId>
>     <artifactId>maven-surefire-plugin</artifactId>
>     <version>3.0.0-M5</version>
>     <configuration>
>         <argLine>@{argLine} -javaagent:${settings.localRepository}/com/alibaba/testable/testable-agent/${testable.version}/testable-agent-${testable.version}.jar</argLine>
>     </configuration>
> </plugin>
> ```
> 
> PS：在IDEA里对`pom.xml`修改之后，会在文件的右上角先生成一个更新按钮，点击以后才会生效，是否是更改过此文件但未生效的原因？
> ![image](https://user-images.githubusercontent.com/1113435/116533202-adc87380-a913-11eb-8f23-00a41fe40258.png)

demo下载下来后没有修改过pom文件
![image](https://user-images.githubusercontent.com/45362242/116637609-efe6c900-a996-11eb-9b09-426c32efbec3.png)

**Comment by linfan** [comment]
我在master最新版本和0.6.4版本的代码上都做了测试，全新的代码目录，IntelliJ打开项目执行测试，但没有复现这个问题。

是用的什么版本的IntelliJ版本和JDK呢？

**Comment by Rayyliu** [comment]
> J打开项目执

JDK1.8     难道是对IntelliJ版本有限制吗？ 我猜测是这个原因，公司电脑的IntelliJ版本较低，家里较高一点的版本没出险这个问题

**Comment by linfan** [comment]
没有做有意的限制，但从现象来看，估计确实是IntelliJ版本原因。出错的是InteliJ的什么版本呢？

**Comment by Rayyliu** [comment]
> 没有做有意的限制，但从现象来看，估计确实是IntelliJ版本原因。出错的是InteliJ的什么版本呢？

![image](https://user-images.githubusercontent.com/45362242/116767151-d447f500-aa60-11eb-8701-cb04b3c0d0dd.png)
ban版本确实有点太

**Comment by Rayyliu** [comment]
> 没有做有意的限制，但从现象来看，估计确实是IntelliJ版本原因。出错的是InteliJ的什么版本呢？

**Comment by Rayyliu** [comment]
> > 没有做有意的限制，但从现象来看，估计确实是IntelliJ版本原因。出错的是InteliJ的什么版本呢？

用不同版本运行了下，2018,2019版本不可以，2020能成功，这个锅IntelliJ背了

**Comment by linfan** [comment]
收到，近期会找个旧版本的IntelliJ环境查下原因

**Comment by linfan** [comment]
用IntelliJ 2018.1.8版本做了验证，示例代码能够在IDE里正常运行，应该不完全是IntelliJ版本的问题。

从现象来看，直接原因应该是pom.xml文件中的 maven-surefire-plugin 插件参数在IDE运行时没有生效，暂时没有更多线索。

**Comment by Rayyliu** [comment]
> 用IntelliJ 2018.1.8版本做了验证，示例代码能够在IDE里正常运行，应该不完全是IntelliJ版本的问题。
> 
> 从现象来看，直接原因应该是pom.xml文件中的 maven-surefire-plugin 插件参数在IDE运行时没有生效，暂时没有更多线索。

![image](https://user-images.githubusercontent.com/45362242/117316894-9e20d000-aebb-11eb-8fb1-524ea0b65a13.png)
这是执行成功的，但是也没在java-demo/target目录下面生成testable-agent.log日志文件
