### ISSUE TITLE
对于私有静态方法中参数为数组不支持

### ISSUE THREAD

**Issue by quanbetter** [alibaba/testable-mock#152]

**Comment by linfan** [comment]
是指什么功能对List Set参数不支持？

**Comment by quanbetter** [comment]
> 是指什么功能对List Set参数不支持？
PrivateAccessor调用类的私有静态方法:
private static Set<Interceptor> reflectInterceptors(String[] interceptorClassNames)


  @Test
    void reflectInterceptorsTest() {
        String[] interceptorClassNames = new String[]{"com.quan.nam", "name"};
        PrivateAccessor.invokeStatic(ExporterInterceptor.class,"reflectInterceptors",interceptorClassNames);
    }

**Comment by linfan** [comment]
已复现，当方法仅有一个参数，且参数类似是数组的时候会有问题，近期会修复

**Comment by quanbetter** [comment]
好的

**Comment by linfan** [comment]
已在`0.6.5`版本修复
