### ISSUE TITLE
【被测试类和测试类的包名须一样】这个限制太坑了

### ISSUE THREAD

**Issue by Qwenjin** [alibaba/testable-mock#153]
举例：
被侧类类所在包：com.apple.service
测试类1所在包：com.apple.test.service
测试类2所在包：com.apple.aaa.bbb

这个工具几乎无法在已有项目中使用，因为大部分旧项目的包都不是规范，
强行按照testable的包名要求去改造原有单元测试消耗太多人力。

**Comment by Qwenjin** [comment]
@MockMethod(targetClass = YourTargetClass.class)中已经指定了被测试类，
完全没有必要包路径一致吧？

**Comment by linfan** [comment]
如果不用`verify()`方法和`scope`参数的话，可以不考虑测试类和Mock类的关联，只需要被测类关联到Mock类。

默认Mock类可以是两个位置，一是同包的被测类里名称是"Mock"的内部类，另一种是同包下名称是"被测类+Mock"的类。可以直接在测试目录下面，与被测类同包的位置，创建一个"+Mock"的类，让被测类关联Mock类。比如被测类是`com.apple.service.Abc`，创建`com.apple.service.AbcMock`类，在里面写Mock方法即可。

另外近期会支持 #105 所述的外置映射配置，包括对包路径进行映射转换，但可能未必适合解决你的这个问题。

`targetClass`指定的是Mock方法所属的类型，不一定就是被测类。

**Comment by Qwenjin** [comment]
原来我理解错了，
假定methodA内部会调用并返回methodB的值，而methodB简单返回"testB"。
此时，mock了methodA和methodB，分别返回"mockA"和"mockB"。
新建测试类调用methodA，我预期是返回"mockA"，而实际上是返回"mockB"，
也就是说被测试方法methodA是调用真实的逻辑，mothodA中依赖的其他方法才是调用mock的。

**Comment by linfan** [comment]
只需要理解一个逻辑，“被Mock的是**被测类**中的调用” 即可，只有被测类里的代码需要Mock，测试类自己里面代码是无需Mock的。

从测试类调用`methodA()`，如果不想调用不调用就是了，都是测试代码。
被测类`methodA`里面调用`methodB()`，因为被测类是业务逻辑，不应该为了测试去修改，所以才需要使用Mock。

**Comment by Qwenjin** [comment]
> 只需要理解一个逻辑，“Mock只对**被测类**中的调用生效” 即可，只有被测类里的代码需要Mock，测试类自己里面代码是无需Mock的。
> 
> 从测试类调用`methodA()`，如果不想调用不调用就是了，都是测试代码。
> 被测类`methodA`里面调用`methodB()`，因为被测类是业务逻辑，不应该为了测试去修改，所以才需要使用Mock。

测试类(XXXTest)本身的代码和测试类中调用的`被侧类的方法`是无需mock的，
`被侧类的方法`中调用的`其他方法`才需要Mock。
这么理解对吧？

**Comment by linfan** [comment]
> > 只需要理解一个逻辑，“Mock只对**被测类**中的调用生效” 即可，只有被测类里的代码需要Mock，测试类自己里面代码是无需Mock的。
> > 从测试类调用`methodA()`，如果不想调用不调用就是了，都是测试代码。
> > 被测类`methodA`里面调用`methodB()`，因为被测类是业务逻辑，不应该为了测试去修改，所以才需要使用Mock。
> 
> 测试类(XXXTest)本身的代码和测试类中调用的`被侧类的方法`是无需mock的，
> `被侧类的方法`中调用的`其他方法`才需要Mock。
> 这么理解对吧？

正确。

Mock测试类的调用没有意义。
