### ISSUE TITLE
一个测试类中如何关联多个Mock类

### ISSUE THREAD

**Issue by Suny95** [alibaba/testable-mock#157]
如果一个测试类中需要关联多个Mock类，且测试类的包路径与mock类包路径不一致，我要如何在测试类中引用这些mock类

如下图所示，目前只有mock1类可以生效，mock2是无法生效的

mock1
![image](https://user-images.githubusercontent.com/26239751/117770404-73da6400-b267-11eb-9f77-112131c3e738.png)

mock2
![image](https://user-images.githubusercontent.com/26239751/117770456-848ada00-b267-11eb-9b5b-8ae5c3e22dac.png)

测试类
![image](https://user-images.githubusercontent.com/26239751/117770637-bd2ab380-b267-11eb-8029-7ae3fbd5ac18.png)

被测类的方法
![image](https://user-images.githubusercontent.com/26239751/117770687-cd429300-b267-11eb-9d00-2e08a76c6823.png)

**Comment by linfan** [comment]
我大概理解到原因了，TestableMock的设计是每个业务类提供自己的Mock方法集，比如Service里调用多个Util类，是需要在Service类自己的Mock类里提供相应的Mock方法，而不是各个Util类所在的Mock类来提供Mock方法，因为要被Mock的**调用**发生在Service类里。

这个问题在之前的Issue里也有提过，TestableMock在这个方面的设计出发点是大部分Mock的方法在各单元测试里都是可复用的，写一次即可。至于应该写在方法所在类的Mock类里，还是写在调用方法的类的Mock类里，两者技术上都能实现，各有优劣。前者会导致Mock某些系统类和三方包的里的类变得比较麻烦，后者则相对更不符合使用的直觉。目前TestableMock是用了后一种方法，即Service调用Util类的方法，要Mock这个调用，是在Service自己的Mock类里加Mock方法定义。

**Comment by Suny95** [comment]
可问题是有些测试类他不在相同的包下调用，比如我们目前的场景

Guards
+ com.xxx.utils

OrderHandlerTest
+ com.xxx.handler

OrderHandlerTest
+ com.xxx.handler

我目前在OrderHandlerTest写了Mock容器，但是它不生效，只有放在com.xxx.utils下，mock才会生效
![image](https://user-images.githubusercontent.com/26239751/118116438-dd4fa380-b41c-11eb-913e-66ff44e74007.png)

按文档上说的话，这样配的方式应该是可以生效的，但是很奇怪，我这边好几个mock容器类如果不放在被mock类的同包下，基本都不会生效~~~

**Comment by linfan** [comment]
> 我这边好几个mock容器类如果不放在被mock类的同包下，基本都不会生效~~~

整体思路上，是每个业务类都自己写自己的Test类和Mock类（可以用单独的`XxxMock`类，或者是`XxxTest`的内部类），业务类本身、测试类、Mock类都在同一个包下，便于管理。

如果业务类和它的Mock类不同包，可以在业务类上用`@MockWith`注解显示指定，但相比之下还是使用一致的包路径更直观。

**Comment by Suny95** [comment]
我不知道是因为什么，被测类与测试类是同包下，被测类里调用utils方法，但不会走测试类的静态内部类mock方法~~

**Comment by Suny95** [comment]
我不知道是因为什么，被测类与测试类是同包下，被测类里调用utils方法，但不会走测试类的静态内部类mock方法~~

**Comment by Suny95** [comment]
重新验证了一下，现在的情况是：

utils的Mock是写在OrderHandlerTest中，OrderHandlerTest在调用OrderHandler后，代码运行下去会调用到其他的Handler，utils是在其他的Handler里调用的，这种情况下Mock就失效了

**Comment by linfan** [comment]
> 代码运行下去会调用到其他的Handler，utils是在其他的Handler里调用的，这种情况下Mock就失效了

每个类型提供自己的Mock类，在其他Handler内发生的调用会采用这个Handler自身关联的Mock类中的Mock方法集合。即发生在`AbcHandler`中的调用将匹配`AbcHandlerMock`（或`AbcHandlerTest.Mock`）类型中的Mock方法，发生在`XyzHandler`中的调用将匹配`XyzHandlerMock`（或`XyzHandlerTest.Mock`）类型中的Mock方法。

**Comment by Suny95** [comment]
明白了，这不会将mock的范围延伸到其他类中

**Comment by linfan** [comment]
是的。

`TestableMock`基于方法签名来匹配Mock的方法能在很大程度上降低学习Mock定义语法的成本和消除对Mock目标的限制。但在Mock定义是跟着”方法发生调用的类“，还是跟着”方法所属的类“在实现的时候确实有过争议（两种方式在技术上皆可行）。目前`TestableMock`实现的是Mock定义跟着”方法发生调用的类“的这种方式，所以是Mock调用在哪个类发生，就匹配这个类对应Mock容器里的Mock方法。
