### ISSUE TITLE
这个库的api稳定了吗？是否可以大规模的在线上使用？

### ISSUE THREAD

**Issue by jackzhangdev** [alibaba/testable-mock#160]
这个库的api稳定了吗？是否可以大规模的在线上使用？后期是否会大改？

**Comment by linfan** [comment]
在正式的`1.0`版本发布之前肯定还会有API修改，每次大版本更新都会包含详细的[版本升级指南](https://alibaba.github.io/testable-mock/#/zh-cn/doc/upgrade-guide)。同时可以肯定的是，不会出现功能减少或无法升级的情况。目前已经有不少项目（包括相当大型的项目）在正式使用这个测试工具库了，工具本身的稳定性可以放心。如果确实遇到使用问题，可以将问题详细描述提Issue给我们。

**Comment by jackzhangdev** [comment]
非常感谢
