### ISSUE TITLE
静态代码块 mock

### ISSUE THREAD

**Issue by jackzhangdev** [alibaba/testable-mock#161]
```java
static {
		System.loadLibrary("evil.dll");
}
```

[https://github.com/powermock/powermock/wiki/Suppress-Unwanted-Behavior](https://github.com/powermock/powermock/wiki/Suppress-Unwanted-Behavior)

支持这种类似于 powermock 的 @SuppressStaticInitializationFor，来禁止 static 代码块的初始化吗？
或者有其他方案吗？

**Comment by linfan** [comment]
可以直接把`System.loadLibrary()`调用在测试时Mock掉。定义如下Mock方法即可：

```java
@MockMethod(targetClass = System.class)
private void loadLibrary(String libname) {
    System.out.println("loadLibrary " + libname);
}
```
