### ISSUE TITLE
OmniConstructor实例化Long报错NumberFormatException

### ISSUE THREAD

**Issue by HuangChao5** [alibaba/testable-mock#162]
代码中: 
com.alibaba.testable.core.tool.OmniConstructor#getBestConstructor
获取最小的构建器进行构建实例，
Long类型获取到java.lang.Long#Long(java.lang.String)这个构建器，进行实例化，
所以报错
Caused by: java.lang.NumberFormatException: For input string: ""

测试代码: 
@Test
    public void longTest() throws Exception {
        Long aLong = OmniConstructor.newInstance(Long.class);
    }

**Comment by linfan** [comment]
已补充针对基本类型构造的[测试用例](https://github.com/alibaba/testable-mock/blob/master/testable-core/src/test/java/com/alibaba/testable/core/tool/OmniConstructorTest.java#L18)，并未复现该问题。

实测优先选择的是`public java.lang.Long(long)`构造器，不排除是特定JDK版本存在构造器顺序的问题，下个版本会针对这种情况进行优化。

一种解决办法是开启`OmniConstructor`的字节码增强模式，参考[文档](https://alibaba.github.io/testable-mock/#/zh-cn/doc/omni-constructor)的“注意2”内容。

**Comment by HuangChao5** [comment]
> 已补充针对基本类型构造的[测试用例](https://github.com/alibaba/testable-mock/blob/master/testable-core/src/test/java/com/alibaba/testable/core/tool/OmniConstructorTest.java#L18)，并未复现该问题。
> 
> 实测优先选择的是`public java.lang.Long(long)`构造器，不排除是特定JDK版本存在构造器顺序的问题，下个版本会针对这种情况进行优化。
> 
> 一种解决办法是开启`OmniConstructor`的字节码增强模式，参考[文档](https://alibaba.github.io/testable-mock/#/zh-cn/doc/omni-constructor)的“注意2”内容。

配置了还是一样的报错呢
JDK:   adopt-openjdk-14
日志打印信息:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.alibaba.testable.core.tool.OmniConstructor (file:/D:/company/repository/maven/com/alibaba/testable/testable-core/0.6.5/testable-core-0.6.5.jar) to constructor java.lang.Void()
WARNING: Please consider reporting this to the maintainers of com.alibaba.testable.core.tool.OmniConstructor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by linfan** [comment]
"Illegal reflective access by xxx"这是个警告，是JDK 9+对反射访问私有成员增加了限制导致的，不会影响测试执行。
理论上在开启OmniConstructor增强模式以后有办法避开这个警告，我试试看~
