### ISSUE TITLE
0.6.6 MOCK_CONTEXT 在代码中有 CompletableFuture 时会不符合预期

### ISSUE THREAD

**Issue by Article23399** [alibaba/testable-mock#164]
```java
// com.example.demo.TestServiceTest.java
@RunWith(SpringRunner.class)
@SpringBootTest
public class TestServiceTest {
    @Autowired
    private TestService testService;

    public static class Mock {
        @MockMethod(targetClass = TestService.class, targetMethod = "test2")
        private int test2(int a) {
            System.out.println("test2方法被mock了");
            System.out.println(MOCK_CONTEXT);
            return a + 2;
        }
    }

    @Test
    public void test() {
        System.out.println("运行test");
        MOCK_CONTEXT.put("method", "test");
        System.out.println(MOCK_CONTEXT);
        testService.test1(1);
    }

    @Test
    public void test1() {
        System.out.println("运行test1");
        MOCK_CONTEXT.put("method", "test1");
        System.out.println(MOCK_CONTEXT);
        testService.test1(2);
    }
}

// com.example.demo.TestService.java
@Service
public class TestService {

    public int test1(int a) {
        CompletableFuture<Integer> testFuture = CompletableFuture.supplyAsync(() -> test2(a));
        return testFuture.join();
    }

    private int test2(int a) {
        return 999;
    }
}
```
在单独运行test1时符合预期，输出
```plain
运行test1
{method=test1}
test2方法被mock了
{method=test1}
```
在整个运行TestServiceTest时不符合预期，其中test1输出

```plain
运行test1
{method=test1}
test2方法被mock了
{method=test}
```
似乎MOCK_CONTEXT对象不对

去掉 CompletableFuture 后整个运行 TestServiceTest 符合预期
```plain
运行test1
{method=test1}
test2方法被mock了
{method=test1}
```

**Comment by linfan** [comment]
感谢详细的代码。

这个Case命中了“被Mock方法在线程池中运行”的场景，这种场景在实际运用中比较少遇到，在文档里被一笔带过了。解决方法是开启`thread.pool.enhance.enable`配置，这个配置在[全局运行参数](https://alibaba.github.io/testable-mock/#/zh-cn/doc/javaagent-args)文档有简单提到。

如果是Maven项目，同时需要对`pom.xml`文件里做如下修改：在`maven-surefire-plugin`的<argLine>属性里，再补上这段：`-Xbootclasspath/a:${settings.localRepository}/com/alibaba/transmittable-thread-local/2.12.1/transmittable-thread-local-2.12.1.jar`

（加上原本的`-javaagent`配置，整体就变成`<argLine>-Xbootclasspath/a:${settings.localRepository}/com/alibaba/transmittable-thread-local/2.12.1/transmittable-thread-local-2.12.1.jar -javaagent:${settings.localRepository}/com/alibaba/testable/testable-agent/${testable.version}/testable-agent-${testable.version}.jar</argLine>`，挺长的一串）

如果是Gradle项目，目前与这个参数不兼容，具体原因还没细查，我们自己的项目基本上是Maven的。我会尝试解决一下这个Gradle兼容问题，然后将相关问题补充到正式文档。

**Comment by Article23399** [comment]
测了下，在我的环境下开启ttl的配置后gradle加一行可以运行，之后就正常了
```
    test {
        jvmArgs "-javaagent:${classpath.find { it.name.contains("testable-agent") }.absolutePath}"
        jvmArgs "-Xbootclasspath/a::${classpath.find { it.name.contains("transmittable-thread-local") }.absolutePath}"
    }
```
