### ISSUE TITLE
测试子类，在子类Test中写了Mock，对继承的父类中的方法中的调用进行mock不成功

### ISSUE THREAD

**Issue by elvis-fxw** [alibaba/testable-mock#166]
如题，在对子类的测试类Test中，子类中有一个从abstract父类继承来的方法a(),在a()中调用了另一个类的方法b()，我现在对b()写了mock方法。结果实际调用的时候，调用的还是原来的方法b()，没有进入到mock方法中。

**Comment by linfan** [comment]
TestableMock是对关联被测类中的“调用”进行匹配，即如果调用`b()`发生在父类的代码中，则需要在与父类关联的Mock容器类中定义匹配的Mock方法。

即假设父类名为Parent，需将`b()`调用的Mock方法定义在`ParentTest.Mock`或`ParentMock`类中。

**Comment by elvis-fxw** [comment]
感谢，这个我早上也搞清楚了，写在ParentMock就可以了
