### ISSUE TITLE
MOCK_CONTEXT报空指针问题

### ISSUE THREAD

**Issue by elvis-fxw** [alibaba/testable-mock#167]
今天我发现在Test类如果没有写Mock静态类，或者Mock静态类里面没有实现方法，则MOCK_CONTEXT会报错NullPointer问题。
我现在有这样的使用场景：
一个测试类：ChildTest，一个父类ParentMock.
我现在在ChildTest中测试子类，测试的是父类中的方法a().（因为父类是abstract类，我想在测子类的同时测试一下父类的方法），这个时候我就要使用到ParentMock。但是我在ChildTest中使用MOCK_CONTEXT，就会报错了。

所以我想问一下，是否可以支持这种情况？感觉在一个测试类中，使用到某个xxxMock是可能的，这个时候应该允许使用MOCK_CONTEXT。否则我现在要强行在ChildTest中写一个我不需要的Mock方法。

**Comment by linfan** [comment]
是个已知的设计问题，临时解决方法见[使用不包含mock方法的mock容器类](http://freyrlin.gitee.io/testable-mock/#/zh-cn/doc/use-mock-with?id=_4-使用不包含mock方法的mock容器类)。

好消息是，当前已经有不损失性能的更优方案，预计此问题会在下个小版本中彻底修复。

**Comment by linfan** [comment]
已发布`v0.6.7`版本，包含此问题修复，之前的临时方案可以不需要了~
