### ISSUE TITLE
Springboot 项目 Mock了ServiceA类中的A方法，A在ServiceA的B方法中被调用，方法B为注入ServiceA的private DaoB类中的方法 报MemberNotExistException

### ISSUE THREAD

**Issue by JingGwanWong** [alibaba/testable-mock#169]
Springboot 项目 Mock了ServiceA类中的A方法，A在ServiceA的c方法中被调用，方法B为注入ServiceA的private DaoB类中的方法 现获取ServiceA中的 私有 DaoB，报MemberNotExistException：
如下：
class ServiceA{
private *** DaoB；
c(){
daoB.B();
 A();
}
 A(){...}
}

**Comment by linfan** [comment]
目前私有方法访问的防重构机制只支持对被测类对象的私有成员进行检查。[文档](https://alibaba.github.io/testable-mock/#/zh-cn/doc/private-accessor)的**注意1**部分有说明。比如：

```java
class ServiceATest {

    private ServiceA svcA = new ServiceA();  // 被测类对象
    private ServiceB svcB = new ServiceB();  // 其他类对象

    void testXxx() {
        svcA.privateMethod(a, b, c);   // 这种情况能够检测
        svcB.privateMethod(a, b, c);   // 这种情况一定会报MemberNotExistException
    }
}
```

如果需要用于非测试类的私有成员访问，可以加`@EnablePrivateAccess(verifyTargetOnCompile = false)`配置，禁用放重构机制。
