### ISSUE TITLE
日志显示mock了，但是代码运行时，还是会报空指针。

### ISSUE THREAD

**Issue by wulihuawuqia** [alibaba/testable-mock#172]
![image](https://user-images.githubusercontent.com/17930741/121672777-c61ad900-cae2-11eb-8867-692092521953.png)

![image](https://user-images.githubusercontent.com/17930741/121672915-eea2d300-cae2-11eb-9d44-46cb4e7c5cfa.png)
同样的mock类
![image](https://user-images.githubusercontent.com/17930741/121673083-21e56200-cae3-11eb-98f5-e5663e584a81.png)

**Comment by linfan** [comment]
从日志来看，只是`tryGetDistributedLock`这个调用被Mock了，因此这个调用不会出问题，但这并不等于`jimDbLockUtils`对象整个被Mock了。而`getUniqueRequestId()`调用没有被Mock，所以上面这行还是会导致空指针。

**Comment by wulihuawuqia** [comment]
> 从日志来看，只是`tryGetDistributedLock`这个调用被Mock了，因此这个调用不会出问题，但这并不等于`jimDbLockUtils`对象整个被Mock了。而`getUniqueRequestId()`调用没有被Mock，所以上面这行还是会导致空指针。

是getUniqueRequestId 这个Mock成功啦，但是tryGetDistributedLock这个导致空指针

**Comment by wulihuawuqia** [comment]
![image](https://user-images.githubusercontent.com/17930741/121687332-cfad3c80-caf4-11eb-9829-7ece428fe8ea.png)
![Uploading image.png…]()

**Comment by wulihuawuqia** [comment]
发现是一个Long 类型，和Integer 类型不同
