### ISSUE TITLE
成员变量静态方法初始化如何 Mock？

### ISSUE THREAD

**Issue by ShadowTwj** [alibaba/testable-mock#175]
```java
public class TestA {
    public static TestA newInstance(String name) {
        ...
    }
}
```

- 被测试类
```java
public class MockDemo {

    private static TestA testA = TestA.newInstance("demo");

    public String test(){
        ...
    }
}
```

- 测试类
```java
class MockDemoTest extends Specification {

    static class Mock {
        @MockMethod(targetClass = TestA.class)
        public TestA newInstance(String name) {
            return null
        }
    }

    def mockDemo = new MockDemo()

    def "test"() {
        //mockDemo....
    }
}
```

使用 `Spock`，应该如何来 `Mock` 被测试类的成员变量初始化的静态方法呢？

在被测试类中使用 `Mock` 容器这样来 `Mock` 并没有起作用

**Comment by linfan** [comment]
![image](https://user-images.githubusercontent.com/1113435/125090464-f06fae80-e101-11eb-8679-775b36fa4642.png)

使用方法没有问题，初步来看像是因为Mock的构造方法与调用的构造方法参数不一致，请确认。

**Comment by ShadowTwj** [comment]
> 不好意思~是我打错了，已经修正，在我的环境中是`mock`没有起作用的

> 我怀疑和 https://github.com/alibaba/testable-mock/issues/176#issue-940710250 这个问题是一个原因，都是在同一个环境下，`mock`没有起作用
