### ISSUE TITLE
Spock mock失败

### ISSUE THREAD

**Issue by ShadowTwj** [alibaba/testable-mock#176]
- 被测试类
```java
public class Demo {

    public String method1() {
        return method2();
    }

    private String method2() {
        return "demo";
    }
}
```

- 测试类
```java
class demoTest extends Specification {
    static class Mock {
        @MockMethod(targetClass = Demo.class)
        private String method2() {
            return "demo mock"
        }
    }

    def demo = new Demo()

    def "test"() {
        when:
        def s = demo.method1()

        then:
        s == "demo mock"
    }
}
```

mock 成功应该返回`demo mock`，但是返回了`demo`

对`Spock`的版本有要求嘛？

目前 `Spock` 版本是`1.3-groovy-2.4`，`testable` 版本是`0.6.7`

**Comment by linfan** [comment]
上述代码看起来应该能工作，我抽空验证一下~

没有`Spock`版本要求，`TestableMock`原理上不依赖测试特定框架。

**Comment by linfan** [comment]
我在`demo/spock-demo`这个实例项目里测试了你的这段代码，同时把`Spock`版本降到`1.3-groovy-2.4`，`Groovy`版本降到`2.4.6`，可以正常通过。
可以看一下测试执行完在`target`(maven工程)或者`build`(gradle工程)目录里有没生成`testable-agent.log`文件，如果没有，应该是依赖引入有问题，可以参考一下示例项目的`demo/spock-demo/pom.xml`和`demo/spock-demo/build.gradle`文件。

**Comment by ShadowTwj** [comment]
找到原因了，是没有添加`maven`的插件导致的，感谢。。。
