### ISSUE TITLE
@MockWith不生效的问题

### ISSUE THREAD

**Issue by elvis-fxw** [alibaba/testable-mock#179]
想复用一个Mock类，因为我们会调用外部接口，想对这个外部接口做Mock，所有地方调这个外部接口都进入到Mock。

那么这个我要进行Mock的类，我称之为A。现如今我写了一个Mock类（AMock），放在了一个mock包下，没有放在指定的路径下。

这时我可能要对类B进行测试，写了一个BTest，并且B调用C，C调用D，D调用A。（就是调用链涉及到好几个类）
类似：B->C->D->A

这时我在BTest上面写了一个@MockWith，想要触发A的Mock。但是没有生效！

而且另外，我在把这个AMock移到与BTest同一个包下，也不生效。

唯一一个生效的情况：我写一个ATest放在A类的同名路径下，然后在BTest测试的时候，能通过B->C->D->A成功进入到AMock中。

所以请问一下，我这样的写法，有什么问题，导致BTest的调用进入不到AMock？

**Comment by linfan** [comment]
这个踩坑姿势我们的确万万没有考虑到😝，说实话`@MockWith`作为适配非标场景的”补丁功能“，一直是许多麻烦的源泉...

回正题，上述问题的原因是TestableMock在匹配Mock类时，采用的是”让业务类、测试类分别尝试关联Mock类“，最终形成”每个业务类对应一个测试类，一个Mock类“这种结构（在[文档](https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock-with)第2段末尾有解释）。实际使用的时候，为了尽量避免测试时候改业务类代码，约定业务类在寻找Mock类的时候，除了在约定的位置上找，还会从**自己的测试类**以及**自己**的定义上读取`@MockWith`注解。

因此可以在测试类上加`@MockWith`注解的前提是，该测试类就是目标业务类的测试类，比如类型A和类型ATest，为了避免改动A，可以在ATest上加`@MockWith`。但对于B->C->D->A这样的测试场景，在BTest上加`@MockWith`并不能帮助A类找到自己的Mock类。

简而言之，解决办法是直接在A类上加`@MockWith`注解，让A类能正确关联到自己的Mock类即可。

**Comment by elvis-fxw** [comment]
感谢！我现在还是在同名包下写ATest的静态内部Mock类来解决。

至于你提出的在A类上加@MockWith的办法，囿于我现在的代码结构，我暂时没办法尝试。
我现在的代码结构可以理解为：代码分为模块m1和m2.在m2中依赖了m1.
其中A类在m1，而单测我是写在m2下的src/test下面。所以在A类中无法引用到m2下的Mock类。

另外，在A类中加入@MockWith感觉有侵入代码之嫌，感觉上没有那么舒服。

在此感谢你的解答，后面有机会我会再进行尝试。
