### ISSUE TITLE
java demo error

### ISSUE THREAD

**Issue by rongdanfeng** [alibaba/testable-mock#18]
Java demo DemoPrivateAccessTest类 26行
DemoPrivateAccess.staticCount = 2;
私有成员变量写法编译不了，不能运行。

**Comment by linfan** [comment]
通过Maven编译应该能通过，如果是在IDE里运行，IntelliJ参考文档常见问题第6条，Eclipse的编译功能不是基于Javac的暂时无解
https://alibaba.github.io/testable-mock/#/zh-cn/doc/frequently-asked-questions

**Comment by linfan** [comment]
IntelliJ里运行单元测试的问题在`0.4.5`版本中已修复，见 https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-in-ide 文档。
之前回复链接中的内容已无效。
