### ISSUE TITLE
Can not set static final int field 

### ISSUE THREAD

**Issue by WilsonWu1995** [alibaba/testable-mock#181]
`private static final int staticCount = 0;`
将用例中的static变量改成static final后无法mock成功
`    @Test
    void should_access_private_static_field() {
        setStatic(DemoPrivateAccess.class, "staticCount", 3);
        assertEquals(Integer.valueOf(3), getStatic(DemoPrivateAccess.class, "staticCount"));
    }`
报错如下：
`com.alibaba.testable.core.exception.MemberAccessException: Failed to access private field "staticCount"`
`Can not set static final int field com.alibaba.demo.basic.DemoPrivateAccess.staticCount to java.lang.Integer`

**Comment by linfan** [comment]
目前确实不支持修改`static final`修饰的字段，一般来说非常不建议修改`static final`字段，它们是真正的”常量“，即使在测试的时候也不应该改它们的值。

当然如果你非要改的话，下个小版本我们就加上支持🤪

**Comment by linfan** [comment]
已在`v0.6.8`支持。
使用前需在`testable.properties`文件开启`private.access.enhance.enable`配置项，详见[全局运行参数](https://alibaba.github.io/testable-mock/#/zh-cn/doc/javaagent-args)文档。
