### ISSUE TITLE
复用Mock方法，报错java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by niu-jifei** [alibaba/testable-mock#184]
创建 BasicMock 里面Mock了方法A和方法B，此时ServiceMock extends BasicMock 继承了该Mock容器，在测试类中使用 ServiceMock 容器时，提示错误
java.lang.NoSuchMethodError: ServiceMock.testableIns()Lcn/ServiceMock;

**Comment by linfan** [comment]
像是一个已经在`0.6.7`版本中修复的问题，请检查一下使用的TestableMock版本。

`testableIns()`方法是TestableMock识别到Mock容器类以后在测试启动前自动注入的一个方法，在[原理文档](https://alibaba.github.io/testable-mock/#/zh-cn/doc/design-and-mechanism)中有提到。在`0.6.7`版本之前有个BUG，即当子类自身没有任何Mock方法定义（所有Mock方法均在父类）时，该子类不会被识别为Mock容器类，可以升级版本再试试。

**Comment by niu-jifei** [comment]
问题已经解决，更换完版本就OK了
