### ISSUE TITLE
现在有一个这样的情况，关于被mock的方法，

### ISSUE THREAD

**Issue by mi-im** [alibaba/testable-mock#188]
您好，我们需要测试它的两种情况，一种抛异常的，一种没有抛异常的，这样的有实现的例子吗

**Comment by mi-im** [comment]
我自己虽然可以通过用入参的一些无关紧要的属性在mock的方法里进行分支判断来抛出异常，但这样不太好吧

**Comment by linfan** [comment]
在Testable里一般是通过在测试用例里用MOCK_CONTEXT做标记，然后在Mock方法里读取出来区分

**Comment by mi-im** [comment]
> 在Testable里一般是通过在测试用例里用MOCK_CONTEXT做标记，然后在Mock方法里读取出来区分

好的，谢谢
