### ISSUE TITLE
demo项目中mock有效，自己项目中mock无效

### ISSUE THREAD

**Issue by Yuml** [alibaba/testable-mock#19]
我在官方的demo项目里面使用mock，mock是生效的。但是在我自己的springboot项目里使用mock，mock没有生效。两个项目中测试用的代码完全一样的，不知道为什么结果不同。

![image](https://user-images.githubusercontent.com/30248552/103129410-a11ce000-46d3-11eb-8fd2-d22bb1d5a5e9.png)

![image](https://user-images.githubusercontent.com/30248552/103129404-982c0e80-46d3-11eb-8a63-88f4f8939271.png)

**Comment by Yuml** [comment]
增加注释@MockWith(diagnose = MockDiagnose.ENABLE)之后：

![image](https://user-images.githubusercontent.com/30248552/103129756-f4dbf900-46d4-11eb-8f5d-6aa9d6bf19c7.png)

**Comment by linfan** [comment]
目前`TestableMock`仅支持测试类与被测类在同包，且名称为`测试类+Test`的情况。
按照标准的Maven或Gradle项目结构，源文件和测试应该符合这种约定。

具体来说，按上面这种情况，目录结构应为：
```
src/
   main/
      java/
         com/
            cmiot/
               dock/
                  MyMockTaskTest.java
   test/
      java/
         com/
            cmiot/
               dock/
                  MyMockTask.java
```

这个约束未来可能会放宽，见[Issue-12](https://github.com/alibaba/testable-mock/issues/12)

**Comment by linfan** [comment]
已更新文档明确说明包路径需相同的约束，感谢指出这个信息遗漏：
https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock

**Comment by Yuml** [comment]
哦哦，明白了，谢谢。文档上没注意看到有这一点，希望和测试类名的约定放一起，这样就不容易看漏了。
