### ISSUE TITLE
@MockMethod注解mock方法无效

### ISSUE THREAD

**Issue by hao0111** [alibaba/testable-mock#190]
单元测试代码如下：

public class XXServiceTest{

@MockMethod(targetClass = RestTemplate.class)
    private <T> ResponseEntity<T> exchange(String url, HttpMethod method, HttpEntity<?> requestEntity,
        Class<T> responseType) {
        log.info("xxxxx=======>>>>>>");
        return new ResponseEntity("{\"mchId\":\"1\"}",HttpStatus.OK);
    }

   @Test
    public void checkThirdPay(TestBean<, String, PartnerResponseDO<PartnerThirdPayDO>> testBean)
        throws TxxyBusinessException {
         PartnerBaseBackCondition  condition = PartnerBaseBackCondition.builder().order("xxx").build():
        Response<ThirdPayDO> responseData = xxService.check(condition);
    }

}

测试的方法xxService.check（），方法体会通过RestTemplate去调用远程接口，想mock掉远程的真实调用，但是并不生效，是否写法有问题，还请帮忙指出，谢谢

**Comment by linfan** [comment]
`@MockMethod`修饰的方法需要放在一个单独的Mock容器类里，约定名称是`<被测类>Test.Mock`或者`<被测类>Mock`。做如下修改即可：

```
public class XXServiceTest{

   static class Mock {
        @MockMethod(targetClass = RestTemplate.class)
        private ResponseEntity exchange(String url, HttpMethod method, HttpEntity<?> requestEntity, Class responseType) {
            log.info("xxxxx=======>>>>>>");
            return new ResponseEntity("{"mchId":"1"}",HttpStatus.OK);
        }
    }

    ...
}
```

**Comment by forfuns** [comment]
相同问题，看了教程和demo，没能明白漏做了哪个步骤


代码：
![](https://s3.bmp.ovh/imgs/2021/08/374838b98b376a19.png)

结果：

```
java.lang.AssertionError: expected [aaaa] but found [xxx]
Expected :aaaa
Actual   :xxx
```

**Comment by linfan** [comment]
Mock只对被测类里的调用有效，测试代码内的逻辑不会被Mock，见文档的“特别说明部分”：
https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock?id=_4-特别说明

**Comment by forfuns** [comment]
> Mock只对被测类里的调用有效，测试代码内的逻辑不会被Mock，见文档的“特别说明部分”：
> [https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock?id=_4-特别说明](https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock?id=_4-%E7%89%B9%E5%88%AB%E8%AF%B4%E6%98%8E)

抱歉，我好像没能理解你的意思（包括文档的意思）

![企业微信20210809-225357](https://user-images.githubusercontent.com/1745525/128726970-d75d8a8f-789f-442e-bc62-94b7dac92005.png)

**Comment by forfuns** [comment]
假设我就想 mock `String.trim` 方法,我该怎么编写Mock类？

**Comment by linfan** [comment]
你的Mock方法写法没有问题，只是Mock只会对被测类生效，对测试类里的代码不会生效。因为Mock的目的就是在测试的时候，在不改变业务类源码的情况下，把某些会影响测试的调用替换掉，测试代码本身的调用是无需替换的。

假设被测类是`XXService`，它的测试类是`XXServiceTest`。现在新增一个Mock容器类`XXServiceTest.Mock`或者`XXServiceMock`，然后在其中定义要替换的Mock方法。这些Mock方法只对`XXService`类中的代码会发生匹配&替换，对`XXServiceTest`类的代码不会有任何作用。

> 假设我就想 mock String.trim 方法,我该怎么编写Mock类？
> 在`XXService`的代码里如果有`String.trim`调用，就会在测试的时候被自动Mock掉了

**Comment by forfuns** [comment]
> 你的Mock方法写法没有问题，只是Mock只会对被测类生效，对测试类里的代码不会生效。因为Mock的目的就是在测试的时候，在不改变业务类源码的情况下，把某些会影响测试的调用替换掉，测试代码本身的调用是无需替换的。
> 
> 假设被测类是`XXService`，它的测试类是`XXServiceTest`。现在新增一个Mock容器类`XXServiceTest.Mock`或者`XXServiceMock`，然后在其中定义要替换的Mock方法。这些Mock方法只对`XXService`类中的代码会发生匹配&替换，对`XXServiceTest`类的代码不会有任何作用。
> 
> > 假设我就想 mock String.trim 方法,我该怎么编写Mock类？
> > 在`XXService`的代码里如果有`String.trim`调用，就会在测试的时候被自动Mock掉了

我好像明白了。。测试通过
