### ISSUE TITLE
Mock类继承不生效

### ISSUE THREAD

**Issue by lingyunlujixin** [alibaba/testable-mock#191]
版本：0.6.2
对部分高频Mock方法进行复用的场景下，使用继承的方式（如https://alibaba.github.io/testable-mock/#/zh-cn/doc/mock-method-reusing所说），发现父类的mock方法没有生效

另外，最新的稳定版本是啥，希望在github上直接给出maven坐标

**Comment by lingyunlujixin** [comment]
试了下，发现必须在子类中写点啥就可以了，应该是bug

**Comment by linfan** [comment]
是一个已知BUG，在`0.6.7`版本中已修复，见[版本更新](https://alibaba.github.io/testable-mock/#/zh-cn/doc/release-note)
