### ISSUE TITLE
想通过EnablePrivateAccess注解修改被测类的私有属性，但是一运行测试方法就失败并返回错误

### ISSUE THREAD

**Issue by mi-im** [alibaba/testable-mock#193]
java: java.lang.ExceptionInInitializerError
pcloud_subapp_name can't not be found in System properties or pcloud_subapp_name cant be fount in System env
被测类的私有属性是通过Value注解注入的，在测试方法里通过PrivateAccessor.set方法进行修改的，一运行就会报上述错误，我没有创建pcloud_subapp_name这个变量

**Comment by mi-im** [comment]
我把PrivateAccessor.set方法注释掉再运行还是报了相同的错误

**Comment by mi-im** [comment]
不用EnablePrivateAccess的话，直接用PrivateAccessor工具类是可以修改，并且不会报错

**Comment by linfan** [comment]
可以去掉`@EnablePrivateAccess`这个注解，不会影响`PrivateAccessor`工具类的正常使用，早期的另一种基于`@EnablePrivateAccess`注解的私有字段访问方法已经在文档里标记为不推荐了哦

**Comment by mi-im** [comment]
> 可以去掉`@EnablePrivateAccess`这个注解，不会影响`PrivateAccessor`工具类的正常使用，早期的另一种基于`@EnablePrivateAccess`注解的私有字段访问方法已经在文档里标记为不推荐了哦

好的，谢谢
