### ISSUE TITLE
Mock通用Mapper的方法没有调用

### ISSUE THREAD

**Issue by niu-jifei** [alibaba/testable-mock#196]
private TPosMainMapper mainMapper;
TPosMain tPosMain = mainMapper.selectByPrimaryKey(psNo);
对 selectByPrimaryKey 方法进行了Mock，在运行的时候检测到了Mock的方法，但是没有使用到 Mock的方法，导致了NPE，
像通用Mapper的这些方法应该如何进行Mock使用

**Comment by linfan** [comment]
mapper调用是可以Mock的，先参考[自主排查文档](https://freyrlin.gitee.io/testable-mock/#/zh-cn/doc/troubleshooting)把调用的实际方法签名打印出来，和Mock方法对比一下，可能就会发现原因了
