### ISSUE TITLE
影响其他测试类的运行

### ISSUE THREAD

**Issue by VicDelacroix** [alibaba/testable-mock#20]
被测试类A/B，类A包含类B，类B包含类C

测试类A使用springboottest，未使用testable，未使用其他mock框架
测试类B使用testable，mock了类C，运行正常

测试类A运行时，类B执行类C的方法，抛出了NPE

这个现象出现的时候我一头雾水，反复debug好久找不到原因，直到把测试类B整个注释掉……
公司代码不方便直接贴上来，大概结构如下

> @RequiredArgsConstructor
@Service
public class ClassA {
    private final ClassB instanceB;
    public CompletableFuture<String> query() {
        return instanceB.query();
    }
}

> @RequiredArgsConstructor
@Service
public class ClassB {
    private final ClassC instanceC;
    public CompletableFuture<String> query() {
        return instanceC.readRedis();
    }
}

> @Service
public class ClassC {
    public CompletableFuture<String> readRedis() {
        return CompletableFuture.completedFuture("");
    }
}

> @RunWith(SpringRunner.class)
@SpringBootTest(classes = ServiceInitializer.class)
public class ClassATest {
    @Autowired
    private ClassA instanceA;
    @Test
    public void test() {
        instanceA.query();
    }
}

> public class ClassBTest {
    private ClassB instanceB = new ClassB(new ClassC());
    @MockMethod
    private CompletableFuture<String> readRedis(final ClassC self) {
        return CompletableFuture.completedFuture("mocked");
    }
    @Test
    public void test() {
        instanceB.query();
    }
}

**Comment by linfan** [comment]
已定位，是一处与TestableMock初始化有关的低级错误，这周末会修复掉

**Comment by linfan** [comment]
已更新`0.4.5`版本修复此问题，抱歉由于之前版本错误带来的不便

**Comment by xusida** [comment]
我也是同样的问题，刚准备放弃呢，没想到这么快修复了:+1

**Comment by linfan** [comment]
@xusida 遇到问题先搜下Issue，要是没有的话就提一个，别轻易放弃哦😜

**Comment by qufulin** [comment]
+1 遇到同样问题，搞了两天发现是bug，然后看到了这个issue～～～

**Comment by linfan** [comment]
已挂公告到首页README~
最近连续几个版本更新都不够走心😝，特别是空指针这个BUG影响有点大，接下来的版本会先经过内测稳定再发布哈
