### ISSUE TITLE
testable-agent.log 文件未找到

### ISSUE THREAD

**Issue by zcbbpo** [alibaba/testable-mock#201]
Spring-Boot maven项目，
当使用`<directory>${basedir}/../target</directory>`时，未在对应的目录中生成testable-agent.log日志文件，移除这项配置时，testable-agent.log 文件能生成。

**Comment by cuiyuanjie** [comment]
可以在项目中增加一个testable.properties配置文件，文件里面定义log.file设置日志文件位置
