### ISSUE TITLE
私有方法单测不支持传null参进行测试

### ISSUE THREAD

**Issue by liranGG** [alibaba/testable-mock#226]
private void aMethod(int i, String s) {
    if(s == null) {
        System.out.printlin("good");
    }
}

我想传null参测这个方法，用PrivateAccessor.invoke(被测方法对象, "aMethod", 1, null)不行，报空指针，请求支持这样操作，或者添加一个输入参数类型的找方法。

**Comment by linfan** [comment]
已修复，升级到`0.6.9`版本即可

**Comment by liranGG** [comment]
> 已修复，升级到`0.6.9`版本即可

我提交的新的229、230能回复我不？

**Comment by LuuucasChen** [comment]
> > 已修复，升级到`0.6.9`版本即可
> 
> 我提交的新的229、230能回复我不？

我使用PrivateAccessor.invoke，无法自动注入依赖，这个应该如何解决呢
