### ISSUE TITLE
被测类方法的mock是否可以不用传实现类的参数？

### ISSUE THREAD

**Issue by qufulin** [alibaba/testable-mock#23]
现在约定为测试类必须要与被测类在相同的包下面，且为名字加Test，这个约定问题不大，但是被测类方法的mock还是要定义一个被测类的参数（其实现的接口都不行），我觉得既然有了命名约定，那么其方法的Mock可以省略。
举例：A接口，A的实现类AImpl, 内部方法am，A的测试类AImplTest，要覆盖方法am，需要定义一个AImpl的参数（定义成A也不生效），这里我觉得定义这个AImpl的参数没有必要，可以省略。

**Comment by linfan** [comment]
主要为了统一规则，避免冲突。

如果Mock外部类加上指示类型的参数，当前类没有这个参数，就有可能出现同一个Mock定义既匹配到外部类方法定义，又匹配到被测类的方法定义的情况，造成很隐蔽的BUG。

另外这个额外参数是有作用的哈。可以用来调用原类型中的方法，比如在测试void函数的时候就会用到。

**Comment by linfan** [comment]
参数类型是用`A`还是`AImpl`取决于实际发起调用的这个对象的类型，如果是`A`类型变量指向`AImpl`类型实例，这里就要用`A`。在文档的常见问题页里有具体说明。

**Comment by linfan** [comment]
你很快就会发现这个额外的参数是很有用的，相信我😀

**Comment by qufulin** [comment]
我的意思是这样的
// A
{
      private B b;
      
      private String am() {
         return "Local Impl";
      }
      
      private String bm() {
         return b.m();
      }
}
// ATest
{
    private A a;
    
    //a中注入B对象省略
    
    @MockMethod(targetMethod = "bm")
    public String mockAm(B b) { //此处的参数是必要的，防止混淆
        return "bmMock";
    }
    
    @MockMethod(targetMethod = "am")
    public String mockAm(A a) { //此处我觉得可以不用强制，可以有，也可以省略，如果不需要调用调用原对象就不需要这个参数，约定为不加的话就是mock测试类名去掉Test的类的方法
        return "amMock";
    }
}

**Comment by linfan** [comment]
举个例子哈，假如参数是可省略的，那么在测试类`ATest`里看到这个Mock定义

```
@MockMethod(targetMethod = "bm")
public String mockAm(B b) {
    return "bmMock";
}
```

它既可能是Mock类型`B`当中的`String bm()`方法，也可能Mock是`A`类型当中的`String bm(B b)`方法，就会产生歧义。

这种歧义一方面会给阅读代码的开发者带来一定麻烦，同时也可能引起意想不到的Mock置换（试想如果以上两个方法都存在，但实际上只需要Mock后者，这时候是无法表达的）。与省略带来的好处相比，不太值得。

**Comment by qufulin** [comment]
二义性客观存在，但是几率并不高，即使真的出现，也可以通过增加配置项来消除二义性，
如：@MockMethod(targetMethod = "tx", targetClass=XXX.class) 消除测试类和内部依赖类的方法的二义性
增加@MockObject(举例名字可以再定)    
@MockMethod(targetMethod = "bm")
public String mockAm(@MockObject B b) {
    return "bmMock";
}
来消除bm(), bm(B outhorInstance)的二义性

当然这样对增加框架的实现难度，因为需要检查二义性是否存在并提示给使用框架的开发者
从框架编写者的角度出发，只要增加一个参数就可以消除二义性，可能会觉得不错，但是从使用框架的开发者角度出发，如果有100个方法需要mock，只有一个会产生二义性，那么就需要在99的mock的方法里增加无用参数（如果确实需要可以自行添加），这样对增加使用者的门槛，也会降低使用者的意愿

**Comment by linfan** [comment]
二义性的主要问题并不是技术实现麻烦，而是降低了代码可读性。写的时候确实省事，其他人阅读代码的时候就得一个个的去猜测和比对。

增加targetClass注解参数来替代修改方法本身的首个参数是一种可取的做法，可以将参数信息和目标信息更好的分开，但不建议有默认目标是被测类这条规则。

**Comment by linfan** [comment]
另外，从演进的角度来说，目前TestableMock还不支持Mock方法在测试类之间复用（但已经预留伏笔啦，不然你猜为啥开启调试的注解叫做@MockWith😀）。

Mock方法集和Mock方法复用的功能目前在规划中（初步设计是支持测试类与提供Mock方法类分离，通过Mock类的继承来适配复杂复用的场景，同时会继续兼容当前这种Mock类即测试类的简单用法，最终方案目前还在讨论中），明确指定Mock目标会更有利于无缝兼容未来的Mock复用机制。

**Comment by linfan** [comment]
`@MockMethod`注解添加`targetClass`参数的功能可在[Issue-24](https://github.com/alibaba/testable-mock/issues/24)中讨论。
十分感谢提出这个具有思考性的问题~
