### ISSUE TITLE
加上${argLine}标签后单元测试出现乱码

### ISSUE THREAD

**Issue by ApacheYukino** [alibaba/testable-mock#236]
![cb6f12cef0156ffc0709b2853afe408](https://user-images.githubusercontent.com/56866576/141433582-2a3ec256-0ff6-408a-9c7f-f1b233da9d0b.jpg)
大致意思是找不到该变量，百度的解决方法是去除maven设置里面的argLine标签，但这样mock就不生效了

另外，官方文档和jacoco结合的说明比较少，网上的入门配置也不是很多，经常出现mock不生效或单元测试覆盖率不行的问题

**Comment by linfan** [comment]
报找不到`argLine`变量，要么是这个项目没有引用jacoco，要么是jacoco显示通过`propertyName`配置修改了变量名，后一种情况可以参考这个issue https://github.com/alibaba/testable-mock/issues/107

**Comment by ApacheYukino** [comment]
已解决，IDEA版本从2018.3升级到2019.3
内网环境的2019只有社区版
