### ISSUE TITLE
如何Mock被测试类中关联对象中内部方法相互调用

### ISSUE THREAD

**Issue by lzjyzq2** [alibaba/testable-mock#237]
不是很好描述。。。贴一下代码吧。
- RecordService
```java
// service
public class RecordService {

    public List<Record> getRecords(){
        return new RecordDao().getRecords();
    }
}
```
- RecordDao 
```java
public class RecordDao {
    public List<Record> getRecords(){
        List<Record> records = new ArrayList<>();
        Record record = new Record();
        record.put("userid",user().getId());
        records.add(record);
        return records;
    }

    public User user(){
        User user = new User();
        user.setId("9527-9527-9527-9527");
        user.setUsername("张三");
        user.setAge(18);
        return user;
    }
}
```
- 测试类
```
public class RecordServiceTest {

    public static class Mock{
        @MockInvoke(targetClass = RecordDao.class)
        public User user(){
            User user = new User();
            user.setId("4396-4396-4396-4396");
            user.setUsername("李四");
            user.setAge(20);
            return user;
        }
    }

    /**
     * 测试用例
     */
    @Test
    public void test_getRecords(){
        RecordService recordService = new RecordService();
        String userid = (String) recordService.getRecords().get(0).get("userid");
        System.out.println(userid);
        // 期望输出 4396-4396-4396-4396 ， 实际输出 9527-9527-9527-9527
        assertEquals("4396-4396-4396-4396",userid);
    }
}
```
- 我想要测试的是RecordService中的方法`getRecords`，其作用是根据`session`中的用户返回数据。
- `RecordService`中的`getRecords`调用了`RecordDao`中的`getRecords`，`RecordDao`中的`getRecords`内部调用了`user()`去取得用户数据。我想模拟`RecordDao `中的`user`方法取得模拟的用户数据。这个应该如何实现。
PS：`Dao`层的方法执行需要数据库连接，但数据库的连接只能在`Service`层中进行。
- Demo仓库：https://github.com/lzjyzq2/testable-mock-demo
感谢您能阅读到这里！

**Comment by linfan** [comment]
先说结论，因为`user()`调用实际是发生在`RecordDao`类型里的，因此只能通过`RecordDao`类型关联的Mock类来定义替代的Mock方法。做法是在测试目录中与`RecordDao`路径相同的包内创建`RecordDaoMock`类型，然后将`user()`Mock方法定义在里面。

TestableMock在设计之初主要考虑的是规范的单元测试场景，即每个测试类都是针对被测类中的逻辑进行验证，而不会同时测到跨多个单元（类型、方法）的逻辑。譬如在`RecordServiceTest`的用例中测试`RecordDao`类型里的代码逻辑其实就是“跨单元”了。在这种场景下，TestableMock依然适用，但就会出现Mock方法需要被分别写到多个Mock类里的情况，这也是（我们现在认为）TestableMock在设计上最不够优雅的地方。

**Comment by lzjyzq2** [comment]
> 

非常感谢您的回复，查看了多个issue，也有了大概的了解。提问是想知道是否可行、是否有较好的实践或者最佳实践。现在已经了解到了。非常感谢。
