### ISSUE TITLE
被测试类存在继承父类，mock的时候无法mock继承父类方法

### ISSUE THREAD

**Issue by qijy** [alibaba/testable-mock#242]
被测试类
class ServiceA extend AbstractServiceA<SaInput> {
  public void get() {
     .....
     super.put(SaInput);
     ....
  }
}
父类：
class AbstractServiceA<T extends XXXInput> {
  public void put(T input) {
     .....
     ....
  }
}

测试类
class ServiceATest {
 private  ServiceA sa = new  ServiceA();
  public static class Mock {
        @MockMethod(targetClass = AbstractServiceA.class, targetMethod="put")
        public Object put(SaInput input) {
           return obj;
        ｝
    }

 @Test
  public void test_s() {
     sa.get(); 
    // 此时调用到sa的get方法里的put方法时，不会进入mock跳过，请问怎么处理？是否支持这样的调用方法？
   // 使用版本0.6.10
  }
}

**Comment by linfan** [comment]
代码里被Mock的方法原型是`void put(T input)`，但Mock方法定义的原型是`Object put(SaInput input)`，不确定是否与这个问题有关。

我用上述代码做了测试，同时将put方法原型统一改为`Object put(Object input)`（模板类型`T`在定义Mock方法的时候用模板类`T`，也可以用`Object`代替），验证Mock是能够正常生效的。

**Comment by qijy** [comment]
我这边再尝试一下
