### ISSUE TITLE
使用包地址路径映射后mock类报找不到方法，查看源码发现mock类不应该使用包映射后的类名

### ISSUE THREAD

**Issue by ymlsmile** [alibaba/testable-mock#248]
![504751D3-DE58-4716-B33C-343CD0189B0E](https://user-images.githubusercontent.com/27130430/144953281-b13bd076-5089-4997-a108-0557d9e87851.jpeg)

**Comment by linfan** [comment]
这个地方确实有问题，感谢指出，会在近期发布包含此修复的版本。
下次有类似情况可以直接提交PR哈。

**Comment by linfan** [comment]
已发布`0.7.1`版本，包含此修复
