### ISSUE TITLE
stream表达式先关的问题，具体没找到问题点

### ISSUE THREAD

**Issue by suyujie** [alibaba/testable-mock#250]
List<Integer> rlist = boList.stream().map(bo->bo.getId()).distinct().collect(toList());
List<Integer> rlist = boList.stream().map(XBean::getId).distinct().collect(toList());

测试中，第二行代码报错了。第一行正常
第二行报错信息
区别就是 一个用 箭头方式，一个用::方式。
其中对象里面的 Id 是 lombok的@Data注解生成的get set

java.lang.IncompatibleClassChangeError: Expected static method com.jd.ipc.model.dto.VirtualCateDto.getDeptId3()Ljava/lang/Integer;

**Comment by iceqing** [comment]
遇到同样的问题

**Comment by zcbbpo** [comment]
是像这种的吗？
```
public static class XBean {
        private Long id;

       public Long getId() {
           return id;
       }

       public void setId(Long id) {
           this.id = id;
       }
   }

    public void foo() {
        List<XBean> testList = Collections.emptyList();
        //noinspection RedundantOperationOnEmptyContainer
        List<Long> response = testList.stream().map(XBean::getId).distinct().collect(Collectors.toList());
    }
```

**Comment by suyujie** [comment]
是的&nbsp; 箭头好使，双冒号不行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月16日(周四) 晚上6:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/testable-mock] stream表达式先关的问题，具体没找到问题点 (Issue #250)




 
是像这种的吗？
 public static class XBean {         private Long id;        public Long getId() {            return id;        }        public void setId(Long id) {            this.id = id;        }    }     public void foo() {         List<XBean&gt; testList = Collections.emptyList();         //noinspection RedundantOperationOnEmptyContainer         List<Long&gt; response = testList.stream().map(XBean::getId).distinct().collect(Collectors.toList());     }  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by suyujie** [comment]
> 是像这种的吗？
> 
> ```
> public static class XBean {
>         private Long id;
> 
>        public Long getId() {
>            return id;
>        }
> 
>        public void setId(Long id) {
>            this.id = id;
>        }
>    }
> 
>     public void foo() {
>         List<XBean> testList = Collections.emptyList();
>         //noinspection RedundantOperationOnEmptyContainer
>         List<Long> response = testList.stream().map(XBean::getId).distinct().collect(Collectors.toList());
>     }
> ```

**Comment by suyujie** [comment]
已经修复了？时效杠杠的呀。。会发布小版本吗？
