### ISSUE TITLE
枚举类 里面的方法好像不能mock

### ISSUE THREAD

**Issue by ycy2017** [alibaba/testable-mock#258]

**Comment by ycy2017** [comment]
public class Aaa {

  public String a() {
    String b = this.b();
    return "a" + b + A.c() + E.E;
  }

  public String b() {
    return "b";
  }

}



public enum E {

  E("A"),  B("B");

  E(String value) {
    this.value = value;
  }

  private String value;

  public E formate(){
    return E.E;
  }

}


public class A {

  public static String c(){
    return "c";
  }

}

**Comment by linfan** [comment]
在你的`Aaa`类的`a()`方法中并没有调用到`formate()`方法哦，如果改为如下定义，那么就会输出`abyyyyyB`了。

```java
    public String a() {
        String b = this.b();
        return "a" + b + A.c() + E.E.formate();   // 调用formate()方法
    }
```

**Comment by linfan** [comment]
从`MockDiagnose`的日志也能看出，测试执行的过程中，只调用了`c()`方法，没有关于`formate()`调用的输出
