### ISSUE TITLE
idea中build gradle 项目失败，指定类找不到，URLClassLoader路径有问题

### ISSUE THREAD

**Issue by Yiniu** [alibaba/testable-mock#26]
代码修改如下

public EnablePrivateAccessTranslator(Symbol.ClassSymbol clazz, TestableContext cx) {
        String pkgName = ((Symbol.PackageSymbol) clazz.owner).fullname.toString();
        String testClassName = clazz.getSimpleName().toString();
        String sourceClass = testClassName.substring(0, testClassName.length() - ConstPool.TEST_POSTFIX.length());
        this.privateAccessStatementGenerator = new PrivateAccessStatementGenerator(cx);
        this.sourceClassName = cx.names.fromString(sourceClass);
        try {
            Class<?> cls = null;
            String sourceClassFullName = pkgName + "." + sourceClass;
            try {
                cls = Class.forName(sourceClassFullName);
            } catch (ClassNotFoundException e) {
                if (System.getProperty(IDEA_PATHS_SELECTOR) != null) {
                    // fit for intellij 2020.3+
                    String sourceFileWrapperString = clazz.sourcefile.toString();
                    String sourceFilePath = sourceFileWrapperString.substring(
                            sourceFileWrapperString.lastIndexOf("[") + 1, sourceFileWrapperString.indexOf("]"));
                    int indexOfSrc = sourceFilePath.lastIndexOf(File.separator + "src" + File.separator);
                    String targetFolderPath = StringUtil.fitPathString(sourceFilePath.substring(0, indexOfSrc) +
                            "/build/classes/java/main/");
                    URLClassLoader urlClassLoader = new URLClassLoader(new URL[]{new URL("file:/" + targetFolderPath)});
                    cls = urlClassLoader.loadClass(sourceClassFullName);
                } else {
                    // fit for gradle build
                    String path = StringUtil.fitPathString("file:"
                            + System.getProperty(USER_DIR) + "/build/classes/java/main/");
                    cls = new URLClassLoader(new URL[]{new URL(path)}).loadClass(sourceClassFullName);
                }
            }
            if (cls == null) {
                System.err.println("Failed to load source class: " + sourceClassFullName);
                return;
            }
}

**Comment by linfan** [comment]
已采用并将包含在`0.4.7`版本中，感谢详细的反馈~

**Comment by Yiniu** [comment]
StringUtil.fitPathString(),中的 文件路径分隔符 替换，也有问题，之前忘记贴出来了。“/”替换“\”,需要两次转义，path.replaceAll("/","\\\\");

建议加一个远程分支，开放提交权限，审核通过以后，合到master分支。

**Comment by linfan** [comment]
Github天然支持协作的哈，可以提交Pull Request，这样在仓库里就会有你的Commit啦~
可以搜索”Github Pull Request“，有很多介绍文章，比如我随意贴一篇 https://blog.csdn.net/qq_33429968/article/details/62219783

**Comment by linfan** [comment]
欢迎把发现的问题直接通过Pull Request的方式提交到这个项目~

**Comment by linfan** [comment]
`0.4.7`版本已发布，这个Issue我先关闭了哈，如果还有遇到问题，可以Reopen或者另开一个新的Issue哦~

**Comment by Yiniu** [comment]
ok 感谢指导。



---原始邮件---
发件人: "Fan Lin"<notifications@github.com&gt;
发送时间: 2020年12月31日(周四) 晚上8:24
收件人: "alibaba/testable-mock"<testable-mock@noreply.github.com&gt;;
抄送: "Yiniu"<416855890@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [alibaba/testable-mock] idea中build gradle 项目失败，指定类找不到，URLClassLoader路径有问题 (#26)




 
Github天然支持协作的哈，可以提交Pull Request，这样在仓库里就会有你的Commit啦~
 可以搜索”Github Pull Request“，有很多介绍文章，比如我随意贴一篇 https://blog.csdn.net/qq_33429968/article/details/62219783
