### ISSUE TITLE
使用官方demo运行mock不生效

### ISSUE THREAD

**Issue by weihubeats** [alibaba/testable-mock#270]
版本:
testable.version:0.7.5

运行案例:
![image](https://user-images.githubusercontent.com/42484192/159237356-01b212bc-e6a3-4d37-887c-8600003dade4.png)

运行结果仍然是没有mock的结果
![image](https://user-images.githubusercontent.com/42484192/159237437-2f34f448-f7bd-487f-a4b8-0de9d4b597f8.png)

这几个类都是直接copy testable-mock demo里面的类

**Comment by liudaolunboluo** [comment]
如果是高于jdk9的版本，应该是这个原因：https://github.com/alibaba/testable-mock/issues/272
可以试试去掉被测试代码中的字符串拼接

**Comment by linfan** [comment]
已发布`0.7.6`版本，包含此修复
