### ISSUE TITLE
mock失效

### ISSUE THREAD

**Issue by liudaolunboluo** [alibaba/testable-mock#272]
日志输出：
[WARN] java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[WARN] com.alibaba.testable.agent.model.BsmArg.<init>(BsmArg.java:23)

使用的单元测试框架：spock
被测试类就是一个普通的类不是jniutil之类的

**Comment by liudaolunboluo** [comment]
经过debug之后发现，在JDK11严格来说是JDK9以上版本中，只要代码里有"XXX"这样的字符串的话，那么必然会失败，例如：

```java
    throw new BusinessException(ErrorCodeEnum.TEST,
                    ErrorCodeEnum.TEST.getErrorMsg() + "，测试测试");
```

抛异常的时候有字符串拼接

```java
log.error(ErrorCodeEnum.TEST.getErrorMsg() + "，测试测试")
```

也就是常量和字符串有拼接 的时候就会发现异常。

原因如下：

在`com.alibaba.testable.agent.handler.SourceClassHandler#fetchInvokeDynamicHandle`方法中：

```java
private List<BsmArg> fetchInvokeDynamicHandle(MethodNode mn) {
        List<BsmArg> handleList = new ArrayList<BsmArg>();
        for (AbstractInsnNode instruction : mn.instructions) {
            if (instruction.getOpcode() == Opcodes.INVOKEDYNAMIC) {
                InvokeDynamicInsnNode invokeDynamicInsnNode = (InvokeDynamicInsnNode) instruction;
                //handleList.add((Handle) invokeDynamicInsnNode.bsmArgs[1]);
                BsmArg bsmArg = new BsmArg(invokeDynamicInsnNode.bsmArgs);
                handleList.add(bsmArg);
            }
        }
        return handleList;
    }
```

` BsmArg bsmArg = new BsmArg(invokeDynamicInsnNode.bsmArgs);`这一行，`BsmArg`类中有：

```
  public BsmArg(Object[] bsmArgs) {
        this.bsmArgs = bsmArgs;
        handle = (Handle) bsmArgs[1];
        methodDesc = (Type) bsmArgs[2];
        handleDesc = Type.getType(handle.getDesc());
        originalHandleDesc = handle.getDesc();
```

但是如果有上述的字符串拼接的时候，这个时候我们的语法树就有这个方法——`makeConcatWithConstants`这个好像是jdk9之后新增的，因为jdk9开始String换了byte来实现了。该方法的bsmArgs并不是常规方法的句柄、描述、名称，只有bsmArgs数组只有一个成员就是要拼接的字符串，所以在BsmArg的构造方法中报错数组越界

**Comment by liudaolunboluo** [comment]
![](https://s3.bmp.ovh/imgs/2022/03/954f91c114c68c29.png)

**Comment by liudaolunboluo** [comment]
0.6.8版本+junit没有问题

0.7.5版本+spock可以复现

0.7.5版本+junit可以复现

这个问题应该是0.7.5引进的

**Comment by liudaolunboluo** [comment]
```
  throw new BusinessException(ErrorCodeEnum.Test, "测试测试");
```
再次更新，不一定是要常量+字符串，纯字符串也可复线

**Comment by liudaolunboluo** [comment]
尝试：
https://stackoverflow.com/questions/58681265/how-to-turn-off-string-concatenation-optimization
https://www.baeldung.com/java-string-concatenation-invoke-dynamic
中的设置-Djava.lang.invoke.stringConcat= BC_SB 来回退到jdk8的StringBuilder好像不起作用仍然报错

**Comment by liudaolunboluo** [comment]
尝试：
https://stackoverflow.com/questions/58681265/how-to-turn-off-string-concatenation-optimization
https://www.baeldung.com/java-string-concatenation-invoke-dynamic
中的设置-Djava.lang.invoke.stringConcat= BC_SB 来回退到jdk8的StringBuilder好像不起作用仍然报错

**Comment by liudaolunboluo** [comment]
再次排查分析之后根本原因应该是Java 9利用InvokeDynamic调用了StringConcatFactory.makeConcatWithConstants方法进行字符串拼接优化，也就是说makeConcatWithConstants的opcode是INVOKEDYNAMIC，认为他是一个普通方法，但是他不是，所以建议可以在代码里过滤掉makeConcatWithConstants方法

**Comment by zcbbpo** [comment]
好的，非常感谢详细的细节

**Comment by linfan** [comment]
@liudaolunboluo 感谢详细的调研，以及@zcbbpo 的PR 🥇 
这个Issue先关闭，我处理完近期相关的Issue来统一发版本，如果还有其他问题可以Reopen
