### ISSUE TITLE
包路径映射问题

### ISSUE THREAD

**Issue by ymlsmile** [alibaba/testable-mock#275]
当有两个类，分别在com.xx.common和com.xx.common.service包下，我想将这两个类的mock类放在com.xx.common.mock包下，配置了包路径映射
发现com.xx.common.service包下的mock类不生效
能否将GlobalConfig中的mockPkgMapping改为有序Map
或者将TestableClassTransformer.mapPackage方法改为包路径全匹配，而不是前缀匹配

**Comment by linfan** [comment]
不太理解为何 mockPkgMapping 无序或者 mapPackage() 方法的前缀匹配会导致 com.xx.common.service 包映射不生效，能否更详细的描述一下问题场景。

如果已经有明确的解决方法，也可以顺便直接提一个PR哦。

**Comment by ymlsmile** [comment]
@linfan 
例如 com.xx.common.service包下的Demo类，在com.xx.common.mock包下定义了Mock类DemoMock，但是由于匹配包的时候前缀匹配到了com.xx.common包，所以映射后的路径为com.xx.common.service.DemoMock而不是com.xx.common.mock.DemoMock，导致到不到Mock类

**Comment by ymlsmile** [comment]
@linfan
例如 com.xx.common.service包下的Demo类，在com.xx.common.mock包下定义了Mock类DemoMock，但是由于匹配包的时候前缀匹配到了com.xx.common包，所以映射后的路径为com.xx.common.mock.service.DemoMock而不是com.xx.common.mock.DemoMock，导致找不到Mock类

**Comment by linfan** [comment]
已发布`0.7.6`版本，将`mockPkgMapping`定义为有序映射，现在会按照映射规则在配置文件中的顺序依次进行匹配
