### ISSUE TITLE
版本号(0.6.7)好像有点不一致

### ISSUE THREAD

**Issue by mismo** [alibaba/testable-mock#28]
前一版本号为0.4.6，后一版本号变为0.6.7，不知是笔误还是有意。
![1](https://user-images.githubusercontent.com/1709961/103397224-5dfabb00-4b72-11eb-8e87-e1978efe313a.png)

**Comment by linfan** [comment]
已订正，文档中是正确的，git tag的标签打错了
感谢指出~~
