### ISSUE TITLE
静态方法mock无效

### ISSUE THREAD

**Issue by luoleijun** [alibaba/testable-mock#281]
package com.alibaba.demo.lambda;

import com.alibaba.testable.core.annotation.MockInvoke;
import org.junit.jupiter.api.Test;

/**
 * @Author leijun.luo
 * @Date 2022/5/15 10:24
 * @Version 1.0
 */
public class StaticMethodTest {

    public static class Mock {
        @MockInvoke(targetClass = StaticMethod.class, targetMethod = "function1")
        public static String function1(Integer i) {
            return "mmmmmmm" + i;
        }
    }

    @Test
    public void handle() {
        System.out.println(StaticMethod.function1(1));;
    }

}

**Comment by luoleijun** [comment]
在官方代码，这个包test/java/com.alibaba.demo.lambda下添加这个文件，运行handle
期望返回：mmmmmmm1
实际返回：static1

**Comment by zcbbpo** [comment]
是否是这样的呢：
src: 包下
![image](https://user-images.githubusercontent.com/54526829/168716520-539576fe-a238-45b5-a5a7-7d265c1cf532.png)

test 包下
![image](https://user-images.githubusercontent.com/54526829/168716572-2b43878d-d31e-44fb-8387-e9125846c7a8.png)

result: 
![image](https://user-images.githubusercontent.com/54526829/168716616-66d70ef6-284c-4724-bd8c-39c8239ab33a.png)

**Comment by zcbbpo** [comment]
see https://github.com/alibaba/testable-mock/issues/222

**Comment by luoleijun** [comment]
可以了，感谢回复
