### ISSUE TITLE
mybatis-plus单元测试异常，接口调用正常

### ISSUE THREAD

**Issue by dpp814** [alibaba/testable-mock#284]
启动服务调用接口正常返回，但是单元测试会报错（执行到查询附件时报错）
![1653536908(1)](https://user-images.githubusercontent.com/22487387/170412274-5d1fc197-2019-4bf3-8d1b-5ab8a2a27c04.jpg)
![1653536978(1)](https://user-images.githubusercontent.com/22487387/170412306-8c6b8d61-7ac6-4efa-a737-0827a3c1c4fe.jpg)
![1653536757(1)](https://user-images.githubusercontent.com/22487387/170412322-181165c7-a25e-4cde-b5da-a20d9cf19dab.png)

**Comment by dpp814** [comment]
不一定是moke的问题，先排查。。

**Comment by linfan** [comment]
和 https://github.com/alibaba/testable-mock/issues/280 是同一个问题，近期会处理

**Comment by linfan** [comment]
已发布 `0.7.7` 版本，包含此修复
