### ISSUE TITLE
Springboot项目下mock不生效

### ISSUE THREAD

**Issue by riane2** [alibaba/testable-mock#285]
简单的创建了UserService类，有个公共方法内部调用静态方法返回一个字符串
利用Testable的idea插件生成测试类，然后在Mock方法内部mock了静态方法，用@Resource注解注入了UserService类，测试发现mock静态方法没生效

![image](https://user-images.githubusercontent.com/45055246/173711159-a58b34ff-46e0-4c76-914d-580112e9fcab.png)
![image](https://user-images.githubusercontent.com/45055246/173711229-8499ed40-046b-421a-a627-9e8cb537b7b8.png)
![image](https://user-images.githubusercontent.com/45055246/173711260-d1489630-e040-4166-9015-f5ed5f39a70a.png)

**Comment by linfan** [comment]
我稍后提供一个Springboot的示例工程。
图片里的代码来看应该没什么问题，会不会是pom.xml里的依赖引入配置不太正确？

**Comment by linfan** [comment]
我按上述代码还原了一个示例
https://github.com/linfan/testable-spring-demo

如果依然有问题，可以参考[自助问题排查](https://alibaba.github.io/testable-mock/#/zh-cn/doc/troubleshooting)文档排查

**Comment by riane2** [comment]
> 我按上述代码还原了一个示例 https://github.com/linfan/testable-spring-demo
> 
> 如果依然有问题，可以参考[自助问题排查](https://alibaba.github.io/testable-mock/#/zh-cn/doc/troubleshooting)文档排查

已经解决了，确实是之前配置没配对，感谢大佬百忙之中的回复
