### ISSUE TITLE
使用Spring框架，无法mock被@Service注解的class

### ISSUE THREAD

**Issue by itwild** [alibaba/testable-mock#30]
详情：https://github.com/alibaba/testable-mock/pull/29/commits
麻烦看看有没有更好的解决方法，谢谢！

**Comment by linfan** [comment]
已合并。
仔细想了一下，感觉还需要再处理"$$EnhancerBySpringCGLIB$$"的情况，我改了一些直接把任何"$$EnhancerBy"之后的部分都去掉了，顺便（可能）还能兼容到Google Guice的情况。
启动Spring容器运行单元测试的情况之前都没覆盖，也许还有坑，感谢反馈~

**Comment by yangnaihua** [comment]
刚想试试，正好遇到了~期待新版本

**Comment by wqq-java** [comment]
请问什么时候能发新版本，刚好遇到这个bug

**Comment by linfan** [comment]
下个版本应该就这周内吧，会和[issues-24](https://github.com/alibaba/testable-mock/issues/24)的修改一起带上。
可以先下载源码本地mvn install试试看，如果有其他问题也欢迎反馈

**Comment by JOHHHNNN** [comment]
啊 我一直以为是自己的问题 。。。

**Comment by linfan** [comment]
`0.4.8`版本已发布，包含此PR修复💐

**Comment by jjzwu** [comment]
我用0.4.8版本，service注解的类还是不能mock

**Comment by linfan** [comment]
我没有可复现CGLIB问题的现成案例哈...
试写了一个使用`@RunWith(SpringRunner.class)`启动的测试是正常Mock的，不过从Dump出来的class文件看，应该并没有被动态代理转换过。这是我的测试用例：
![image](https://user-images.githubusercontent.com/1113435/104010889-35189c80-51e8-11eb-81a9-501939ea434d.png)

能提供一下你现在遇到问题的Service测试类内容吗？@jjzwu

**Comment by itwild** [comment]
抽时间写了个在springboot中使用的例子

[https://github.com/itwild/less/blob/master/less-spring-boot/src/test/java/com/github/itwild/less/springboot/service/impl/HeroServiceImplTest.java](https://github.com/itwild/less/blob/master/less-spring-boot/src/test/java/com/github/itwild/less/springboot/service/impl/HeroServiceImplTest.java)

不过当前版本 @MockMethod(targetClass = Xxx.class) 这种写法有问题，已经有人提了issues，[https://github.com/alibaba/testable-mock/issues/40](https://github.com/alibaba/testable-mock/issues/40)，我看作者好像也修复了

**Comment by yangnaihua** [comment]
![image](https://user-images.githubusercontent.com/7445145/104030568-e4934600-51cb-11eb-8888-473c3575a63d.png)
![image](https://user-images.githubusercontent.com/7445145/104030587-eceb8100-51cb-11eb-9850-0362f103bff7.png)
返回的是null

**Comment by linfan** [comment]
@yangnaihua @itwild 收到~ 我做下验证看看
[issue-40](https://github.com/alibaba/testable-mock/issues/40)在`0.4.9`已经修复了

**Comment by linfan** [comment]
@itwild 我试了less里的`HeroServiceImplTest`这个测试，实际加载的类也还是`HeroService`，并没有经过CGLIB代理。也试了把TestableMock版本降到`0.4.7`，测试依然通过。
![image](https://user-images.githubusercontent.com/1113435/104079369-9038a680-525d-11eb-8e0d-a42b2bf3ccc1.png)

有什么复现的建议么？🤔

**Comment by itwild** [comment]
@linfan  又回顾了一下，当时估计可能其他不正确操作让我朝着CGLIB动态代理而导致mock没有生效。抱歉，目前的这个使用场景应该不需要关心CGLIB代理的影响。细想了一下，CGLIB增强的类继承`HeroServiceImpl`, 所以会先加载`HeroServiceImpl`，这个时候需要mock方法会被`testable-mock`注入`HeroServiceImpl`，所以后面CGLIB再对`HeroServiceImpl`增强生成的`HeroServiceImpl$$EnhancerBySpringCGLIB$$b53b5c30`，已经包含了被注入的mock方法。

![image](https://user-images.githubusercontent.com/60608749/104088599-22af6900-52a3-11eb-9990-613394861527.png)

![image](https://user-images.githubusercontent.com/60608749/104088606-2c38d100-52a3-11eb-9070-75c17dfc8514.png)


另外直接打印出来heroService的class和父class也比较直观，如下：

```java
System.out.println(heroService.getClass());
System.out.println(heroService.getClass().getSuperclass());
```

```sh
class com.github.itwild.less.springboot.service.impl.HeroServiceImpl$$EnhancerBySpringCGLIB$$b53b5c30
class com.github.itwild.less.springboot.service.impl.HeroServiceImpl
```

综上来看，以目前的使用场景，https://github.com/alibaba/testable-mock/pull/29/commits 这个pr的代码应该没有用，可以去掉。

**Comment by linfan** [comment]
@itwild 好，那就先改回去了哈，还是要感谢你及时反馈和解决问题的这种态度 😄

**Comment by linfan** [comment]
@yangnaihua 截图的情况按说是能正常访问的。如果是直接调用`PrivateAccessor.invoke()`有问题，可以DEBUG跟到`invoke()`里面具体看下，那里面逻辑不多

**Comment by linfan** [comment]
这个Issue先关闭，如果有其他相关问题请Reopen或者另起一个Issue
