### ISSUE TITLE
接口mock无效

### ISSUE THREAD

**Issue by kisssjqia** [alibaba/testable-mock#307]
因为我们接口是在另一个模块的，所以我是直接在serviceImpl路径上创建的测试类，但是mock无法生效，运行总是跑到daoImpl中
![1669793852937](https://user-images.githubusercontent.com/53514222/204735378-793707a7-6110-449c-b7e9-3016fcce75f9.jpg)

另外，testable-agent.log也无法有效生成。demo虽然能执行成功，但是也没有在target生成日志。用的idea版本是2022.2.3

**Comment by linfan** [comment]
Mock不会对测试类里面的代码生效，只对被测业务类里发生的调用有效。

见文档的[特别说明](https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock?id=_4-%e7%89%b9%e5%88%ab%e8%af%b4%e6%98%8e)部分。

**Comment by kisssjqia** [comment]
非常感谢！我在刚开始使用时理解错误了。
