### ISSUE TITLE
@MockContainer被移除了吗？

### ISSUE THREAD

**Issue by kisssjqia** [alibaba/testable-mock#309]
demo中的testable-core工程能看到有@MockContainer，也有相应的案例DemoMultipleInheritTest使用，并且在文档的注解参数清单也能看到@MockContainer。

![testable-demo](https://user-images.githubusercontent.com/53514222/205614696-0b4d7c98-73bc-40bd-8893-0b9308d90f67.png)

但是在我引用0.7.8版本时发现并没有@MockContainer注释
![official](https://user-images.githubusercontent.com/53514222/205614689-cfef5d70-3159-4496-a5c9-0b46a285b691.png)

**Comment by linfan** [comment]
被提前发现了哈~~
`@MockContainer`是计划在`0.3.9`版本新增的功能，目前只发布到了内部的SNAPSHOT仓库，还没发布正式版本。

预计本月内会发正式，暂时可以从master分支本地`mvn install`试用，或者编译一个SNAPSHOT版本发到自建的仓库哦😃

**Comment by linfan** [comment]
被提前发现了哈~~
`@MockContainer`是计划在`0.3.9`版本新增的功能，目前只发布到了内部的SNAPSHOT仓库，还没发布正式版本。

预计本月内会发正式，暂时可以从master分支本地`mvn install`试用，或者编译一个SNAPSHOT版本发到自建的仓库哦😃

**Comment by linfan** [comment]
已发布`v0.7.9`版本，包含`@MockContainer`注解，这个注解主要用于支持任意名字的Mock容器类，以及支持Mock容器类之间的多重继承。

文档会在近期更新，可以先参考代码库Demo的内容使用。
