### ISSUE TITLE
命令行的 classpath 参数太长时，IntelliJ IDEA 的 Shorten command line 导致 mock 失败

### ISSUE THREAD

**Issue by zcglisp** [alibaba/testable-mock#31]
IntelliJ IDEA
Run/Debug Configurations->Shorten command line->classpath file->mock失败
Run/Debug Configurations->Shorten command line->JAR manifest->mock成功
classpath中内容比较多的项目容易遇到此问题，能否加入文档中的“常见问题”？

**Comment by linfan** [comment]
稍后就收录到“常见问题”里哈，感谢反馈~

**Comment by linfan** [comment]
已添加为问题9
https://alibaba.github.io/testable-mock/#/zh-cn/doc/frequently-asked-questions

**Comment by zcglisp** [comment]
辛苦了，多谢！
