### ISSUE TITLE
添加@{argLine} 后 Mock 似乎失效了 报 NullPointer ERROR

### ISSUE THREAD

**Issue by feiyuzzz** [alibaba/testable-mock#311]
Hi team，

我们项目中使用引入了 maven-surefire-plugin 以及 jacoco-maven-plugin， 而且加了  @{argLine}， 但是执行maven test or install 时报 NullPointer， 请教一下如何解决

**Comment by feiyuzzz** [comment]
似乎是 mock 不生效了

**Comment by linfan** [comment]
NPE报错的相关堆栈能提供一下吗？也许会有些有意义的信息

**Comment by feiyuzzz** [comment]
> 

你好，我们已经解决了，似乎是 idea 的 maven插件问题，deploy 到环境上就没有出现这个 issue 了
