### ISSUE TITLE
assertj断言字符串报错

### ISSUE THREAD

**Issue by scxkd2016** [alibaba/testable-mock#33]
项目是java-demo，
<dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.18.1</version>
            <scope>test</scope>
        </dependency>
=================================
@EnablePrivateAccess
class DemoPrivateAccessTest {

    private DemoPrivateAccess demoPrivateAccess = new DemoPrivateAccess();

    @Test
    void should_able_to_access_private_method() {
        List<String> list = new ArrayList<String>() {{ add("a"); add("b"); add("c"); }};
        String hello = demoPrivateAccess.privateFunc(list, "hello", 1);//(1)
        System.out.println(hello);
        Assertions.assertThat(demoPrivateAccess.privateFunc(list, "hello", 1)).isEqualTo("abc + hello + 1");//(2)
        assertEquals("abc + hello + 1", demoPrivateAccess.privateFunc(list, "hello", 1));
        assertEquals("abc + hello + 1", PrivateAccessor.invoke(demoPrivateAccess, "privateFunc", list, "hello", 1));
    }
===========================
(1)处会报Error:(25, 41) java: privateFunc(java.util.List<java.lang.String>,java.lang.String,int) 在 com.alibaba.testable.demo.DemoPrivateAccess 中是 private 访问控制

(2)处会报Error:(27, 19) java: 对assertThat的引用不明确
  org.assertj.core.api.Assertions 中的方法 <T>assertThat(T) 和 org.assertj.core.api.Assertions 中的方法 <T>assertThat(T) 都匹配

**Comment by linfan** [comment]
已复现，会在近期修复~
感谢反馈🌸

**Comment by linfan** [comment]
问题(1)在`0.4.8`版本已修复。

(2)的情况稍微特殊一点，需要代码编写的时候加一个类型转换处理。

直接这样写在编译时候会报同时匹配多个可用重载方法的错误：

```java
Assertions.assertThat(demoPrivateAccess.privateFunc()).isEqualTo("member");
```

加一个和`privateFunc()`方法返回值匹配的类型转换，就可以正常编译通过。

```java
Assertions.assertThat((String)demoPrivateAccess.privateFunc()).isEqualTo("member");
```

原因是`TestableMock`在转换私有方法或者字段访问后，返回的是模板类型，由编译器在编译时自动判断实际类型。但`assertThat()`方法有多种重载方法都能匹配到这个模板类，导致编译器无法正常选择要调用的重载方法，加上类型转换能为编译器明确指定一种重载调用。
或者是先赋值到变量，然后用assertThat，即转换成(1)这种情况来使用。

**Comment by scxkd2016** [comment]
> 问题(1)在`0.4.8`版本已修复。
> 
> (2)的情况稍微特殊一点，需要代码编写的时候加一个类型转换处理。
> 
> 直接这样写在编译时候会报同时匹配多个可用重载方法的错误：
> 
> ```java
> Assertions.assertThat(demoPrivateAccess.privateFunc()).isEqualTo("member");
> ```
> 
> 加一个和`privateFunc()`方法返回值匹配的类型转换，就可以正常编译通过。
> 
> ```java
> Assertions.assertThat((String)demoPrivateAccess.privateFunc()).isEqualTo("member");
> ```
> 
> 原因是`TestableMock`在转换私有方法或者字段访问后，返回的是模板类型，由编译器在编译时自动判断实际类型。但`assertThat()`方法有多种重载方法都能匹配到这个模板类，导致编译器无法正常选择要调用的重载方法，加上类型转换能为编译器明确指定一种重载调用。
> 或者是先赋值到变量，然后用assertThat，即转换成(1)这种情况来使用。

收到
