### ISSUE TITLE
RedisTemplate怎么mock，能提供一下思路吗？

### ISSUE THREAD

**Issue by CZ-2020** [alibaba/testable-mock#38]
@Autowired
    private RedisTemplate redisTemplate;

Set members = redisTemplate.opsForSet().members("online");
怎么替换members的返回

**Comment by linfan** [comment]
首先进到`opsForSet()`方法的定义，可以看到这个方法返回的类型是`SetOperations<K, V>`，因此要Mock的目标类是`SetOperations`。然后再看一下`member()`方法的原型定义是`Set<V> members(K key)`。这些在IDE里都可以直接跟进到库里面去看（一般是Ctrl或者Cmd键加点击跳转到定义，或者查一下自己的IDE用法哈）。

Mock方法与`members()`方法定义保持一致，增加一个类型为`SetOperations`的首位参数，具体如下：

```
@MockMethod
private Set<V> members(SetOperations self, K key) {
}
```

在本周**即将发布**的`0.4.8`版本里还会支持把目标类放到注解上，这样Mock方法定义就和目标方法完全一致了：

```
// 需 TestableMock 0.4.8 或以上版本
@MockMethod(targetClass = SetOperations.class)
private Set<V> members(K key) {
}
```
