### ISSUE TITLE
启动demo报错

### ISSUE THREAD

**Issue by MrCrossing** [alibaba/testable-mock#4]
能给给出更多的文档么，现在这个文档有点儿不全，在idea2020.3中跑不起来。
错误：java: count 在 com.alibaba.testable.demo.DemoPrivateAccess 中是 private 访问控制

**Comment by linfan** [comment]
如果在IDE里面直接运行的话，参考一下常见问题的第6项
https://alibaba.github.io/testable-mock/#/zh-cn/doc/frequency-asked-questions

**Comment by xiaolinboy** [comment]
Eclipse 运行需要设置什么吗？访问私有方法报错.
![image](https://user-images.githubusercontent.com/13216998/103078130-348ade00-460c-11eb-943c-f18f914e98b6.png)
运行单元测试不行，通过 mvn clean package,就可以运行。
![image](https://user-images.githubusercontent.com/13216998/103078226-600dc880-460c-11eb-8d0f-ad70f2cd6a81.png)

**Comment by linfan** [comment]
@xiaolinboy 加这两个配置
- Program arguments: `-processor com.alibaba.testable.processor.EnablePrivateAccessProcessor`
- VM arguments: `-ea -javaagent:/Users/flin/.m2/repository/com/alibaba/testable/testable-agent/0.4.4/testable-agent-0.4.4.jar`

前一个是针对私有方法访问的，后一个是针对Mock功能的，然后测试就能正常运行了。见下图：

![image](https://user-images.githubusercontent.com/1113435/103087438-7b83ce00-4622-11eb-8e25-393475271eea.png)
![image](https://user-images.githubusercontent.com/1113435/103087654-26948780-4623-11eb-966d-800d0b8ca65d.png)

**Comment by xiaolinboy** [comment]
@linfan 
增加VM配置后可以运行单元测试了，但是DemoPrivateAccessTest 是编译错误，怎么让eclipse 能够编译这个类 DemoPrivateAccessTest。

以下是Eclipse配置文件SpringToolSuite4.ini 的信息
-startup
plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.1200.v20200508-1552
-vm
D:/Program Files/Java/jdk1.8.0_66/bin
-product
org.springframework.boot.ide.branding.sts4
--launcher.defaultAction
openFile
-vmargs
**-ea
-javaagent:E:/temp/.m2/local/repo/com/alibaba/testable/testable-agent/0.4.4/testable-agent-0.4.4.jar
-processor com.alibaba.testable.processor.EnablePrivateAccessProcessor**
-Dosgi.requiredJavaVersion=1.8
-javaagent:lombok.jar
-Xloggc:gc.log
-XX:+PrintGCDetails
-XX:+PrintGCDateStamps
-Xverify:none
-XX:+AggressiveOpts
-XX:CompileThreshold=1000
-XX:+UseStringCache
-XX:+OptimizeStringConcat
-XX:+UseCompressedStrings
-Dosgi.requiredJavaVersion=1.8
-Dosgi.module.lock.timeout=10
-Dorg.eclipse.swt.browser.IEVersion=10001
-Xms1024m
-Xmx1024m
#-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM

**Comment by linfan** [comment]
重新验证了一下，发现`-processor`参数确实不管用，这个是Javac的参数，在运行配置里会被直接忽略，我先前之所以通过是因为先在命令行做了`mvn test-compile`。Eclipse的Java构建是自己实现的，不基于Javac，还没找到可行的配置方法。
目前确定能走通的一种方法是在Eclipse上关闭“Project > Build Automatically”自动构建，然后执行一次`mvn clean`，之后手工执行`mvn test test-compile`来进行构建，但这样使用起来确实不太优雅，如果我能找到基于Eclipse自身配置的解法再来更新。

**Comment by linfan** [comment]
按照Eclipse官方的Annotation Processor支持机制，操作流程应该如下：
1. 在项目目录右键打开`Properties`配置窗口
2. 然后在`Java Compiler -> Annotation Processing`配置启用`Enable annotation processing`
3. 最后在`Java Compiler -> Annotation Processing -> Factory Path`配置启用`Enable project specific settings`，添加`testable-processor-0.4.4.jar`这个Jar包

实际验证并不管用。

**Comment by linfan** [comment]
更新一下进展，Eclipse启用`Annotation Processing`依然不生效的原因大概清楚了，是因为Eclipse的编译期注解处理器也是自己实现的，与Javac的标准实现不兼容。这个问题处理起来需要一定时间。

如果确实使用Eclipse IDE，可以先采用`PrivateAccessor`工具类的方式进行私有成员访问。

**Comment by linfan** [comment]
IntelliJ里运行单元测试的问题在0.4.5版本中已修复，此Issue讨论的相关问题已更新至文档 https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-in-ide
