### ISSUE TITLE
@MockMethod(targetClass = SetOperations.class)报错，不用targetClass写在参数里就没报错

### ISSUE THREAD

**Issue by CZ-2020** [alibaba/testable-mock#40]
java.lang.VerifyError: Operand stack underflow
Exception Details:
  Location:
   ***/**/service/impl/***.***(Ljava/lang/Long;)Ljava/util/List; @22: getfield
  Reason:
    Attempt to pop empty stack.
  Current Frame:
    bci: @22
    flags: { }
    locals: { '***/**/service/impl/***', 'java/lang/Long', 'java/util/List' }
    stack: { }
  Bytecode:
    0x0000000: 2ab4 002d 2bb9 0032 0200 4d2c b800 3899
    0x0000010: 0007 b800 3eb0 b400 42b6 0048 124a b800
    0x0000020: 504e 2cb9 0054 0100 3a04 1904 b900 5c01
    0x0000030: 0099 0038 1904 b900 6001 00c0 0062 3a05
    0x0000040: 2d19 05b6 0066 b600 6cb9 0070 0200 9900
    0x0000050: 0f19 0504 b800 74b6 0078 a700 0c19 0503
    0x0000060: b800 74b6 0078 a7ff c42c ba00 8b00 00b8
    0x0000070: 0091 b900 9501 00b9 0099 0200 2cb0     
  Stackmap Table:
    append_frame(@22,Object[#64])
    append_frame(@42,Object[#86],Object[#88])
    append_frame(@93,Object[#98])
    chop_frame(@102,1)
    chop_frame(@105,1)

**Comment by linfan** [comment]
能提供一下被Mock方法的返回值类型和参数类型吗？我需要复现一下，多谢

**Comment by linfan** [comment]
复现条件是：被Mock调用的发起对象不是局部或成员变量，而是临时构造的对象或其他方法调用的返回的临时对象。
已提交修复，下个版本会包含。

**Comment by 102** [comment]
Я не понимаю китайский

**Comment by linfan** [comment]
@102 Sorry for the inconvenience.
The fix of this issue have already been committed into repository, and will be contain in the next release.

BTW this project also contains an [introduction](https://github.com/alibaba/testable-mock/blob/master/README_EN.md) and [user docs](https://alibaba.github.io/testable-mock/#/en-us/) in English. If you meet any problems during use, please raise an issue, any language is welcomed.

**Comment by linfan** [comment]
released `0.4.9` with the fix.
