### ISSUE TITLE
mock的方法体内定义了超过一个的变量时，如果使用switch会报错

### ISSUE THREAD

**Issue by CZ-2020** [alibaba/testable-mock#41]
@MockMethod(targetClass = SetOperations.class)
    private Boolean isMember(K key,Object o) {
        String testName = (String) TestableTool.MOCK_CONTEXT.get("testName");
        String a = "";
        switch (testName) {
            case "场景1" :
            case "场景2" :
            case "场景3" :
                return true;
            default:
                return false;
        }
    }

Caused by: java.lang.ClassFormatError: StackMapTable format error: bad type array size in method isMember

**Comment by linfan** [comment]
我试着验证了这段代码，但没有复现出错误。搜"bad type array size"这个报错信息也没找到什么有用内容。
能提供一下你的Java版本信息吗？`java -version`

**Comment by CZ-2020** [comment]
1.8.0_161

**Comment by linfan** [comment]
'junit-jupiter' failed to discover tests只说明JUnit 5引擎还没启动就已经报错了，JVM 8的话应该可以基本排除JVM版本问题。

试把Mock方法声明改成`static`看看，`private static Boolean isMember(K key, Object o) {}`，排除一下相关的原因。

如果还是有错误，在`pom.xml`文件引用`testable-agent.jar`的末尾加一个`=dumpPath=<指定一个文件路径>`，比如：

```
<configuration>
	<argLine>@{argLine} -javaagent:${settings.localRepository}/com/alibaba/testable/testable-agent/${testable.version}/testable-agent-${testable.version}.jar=dumpPath=/tmp/dump</argLine>
</configuration>
```

把`/tmp/dump`这部分换成一个本地存在的目录（最好是空目录），然后运行一下测试，在目录里会生成经过TestableMock处理过后的class文件，把对应包含`isMember()` Mock方法的**测试类**的那个文件发一下。

**Comment by CZ-2020** [comment]
Fan Lin <notifications@github.com> 于2021年1月10日周日 下午4:01写道：

**Comment by CZ-2020** [comment]
整体代码如下，目前有两种方法不报错，class的名字结尾不带Test或mock方法里不写switch
@MockWith(diagnose = MockDiagnose.ENABLE)
class BugRecoverTest{

    private BugRecover bugRecover = new BugRecover();

    @AfterEach
    void clear() {
        TestableTool.MOCK_CONTEXT.clear();
    }

    @ParameterizedTest
    @CsvSource({"1","1"})
    void getChatRole(String testName) {
        TestableTool.MOCK_CONTEXT.put("testName", testName);
        bugRecover.getChatRole(1L);
    }

    @MockMethod(targetClass = SysUserRoleMapper.class)
    private SysUserRole selectUserChatRole(Long userId) {
        String testName = (String) TestableTool.MOCK_CONTEXT.get("testName");
        SysUserRole sysUserRole = new SysUserRole();
        switch (testName) {
            case "1" :
            case "2" :
                return sysUserRole;
            default:
                return null;
        }
    }

}

**Comment by CZ-2020** [comment]
先算了，好像和mapper本身也有关，只有mock某几个mapper的方法时会出现；找不到原因，目前把测试类名字最后的Test改成其他、mock的方法里不写swich都能避免这个问题

**Comment by linfan** [comment]
@CZ-2020 复现了，赞这个简短的代码例子

问题还是由于TestableMock在运行期动态修改Mock方法为`static`方法导致的，把方法手工声明为`static`能解决。不过因为方法参数有泛型类型，直接声明为`static`在编译的时候过不去，把泛型`K`写成`Object`就可以了（因为JVM的泛型擦除机制，所有泛型到了运行期其实都是`Object`类，所以在运行的时候可以匹配到，在[常见问题](https://alibaba.github.io/testable-mock/#/zh-cn/doc/frequently-asked-questions)第4条有提到）。Mock方法声明那行改成下面这样：

```
private static Set<String> members(Object key) {
```

动态改Mock方法为`static`方法这个机制是目前很大一部分BUG的源头，会在`0.5`版本里会彻底改掉。`0.5`版本目前已经完成设计开始开发，预计会在最近几周内发布。在新版本里你现在的这种Mock方法写法就也能够正常工作了。

**Comment by linfan** [comment]
`0.5.0`版本已发布🚀
