### ISSUE TITLE
Test case failed using testable-mock with junit:junit:4.+ 

### ISSUE THREAD

**Issue by gospeljohn** [alibaba/testable-mock#43]
I am using the java-demo in this project. And changed the testImplementation to junit:junit:4.+.
like:
`
dependencies {
    //testImplementation('org.junit.jupiter:junit-jupiter:5.6.2')
    testImplementation 'junit:junit:4.+'
    ......
}
`

Then changed the all need import of DemoMockTest, and run the result is failed:
expected:<[mock_]something> but was:<[]something>
Expected :mock_something
Actual   :something
<Click to see difference>

org.junit.ComparisonFailure: expected:<[mock_]something> but was:<[]something>
	at com.alibaba.testable.demo.DemoMockTest.should_able_to_mock_new_object(DemoMockTest.java:75)

Who can tell me the reason? Thanks.

**Comment by linfan** [comment]
Thanks for raise the issue, I‘ll have a try and check it.

Actually we have a much larger test case pool including all demo cases and issue related cases, which run with JUnit 4 and **maven**. Sorry cannot open source it because it also contains several internal issue cases with biz related code. Combine JUnit 4 with Gradle has never been tried before, but should have not reason to fail.

**Comment by gospeljohn** [comment]
Compate with junit very important after all there are lot of users of junit.

Thanks.

**Comment by linfan** [comment]
checkout branch [junit4](https://github.com/alibaba/testable-mock/tree/junit4) and try : )
it works as expected (with Gradle 6.7).

**Comment by gospeljohn** [comment]
cool, so cute.
But can you explain the function of below:
test {
    jvmArgs "-javaagent:${classpath.find { it.name.contains("testable-agent") }.absolutePath}"
    useJUnit()
}

How I deploy the testable-mock with Robolectric to test Android project?

Thanks.

**Comment by linfan** [comment]
`can you explain the function of below`
the first line `jvmArgs ...` will found the full path of `testable-agent.jar` file from jvm classpath, and set a `-javaagent` parameter it to `jvmArgs` property correcting to the jar file found. you could look up `-javaagent` parameter of jvm for more details.
second line `useJUnit()` is a standard configuration for Junit 4.

`How I deploy the testable-mock with Robolectric to test Android project?`
that's a good question, TestableMock and Robolectric are technically match, however I don't have a simple enough demo at my hand. maybe could you found an android demo with recent Robolectric release? I'll show how to fit it.

**Comment by gospeljohn** [comment]
Sure， check the attachment which is I write a sample demo using Robolectric, you can try.
Good luck.

**Comment by linfan** [comment]
hey... I did not see the attachment

**Comment by gospeljohn** [comment]
Sorry, please check the attachment.
[testablemock.zip](https://github.com/alibaba/testable-mock/files/5808626/testablemock.zip)

**Comment by linfan** [comment]
Emm, looks like google repository get blocked from my home network, some android dependence not downloadable, and I'm having 2 days off tomorrow and the day after tomorrow.
Will try to get it done next Monday when back to office, sorry man.

**Comment by gospeljohn** [comment]
Hello, did you have time to try the attchment demo?

**Comment by linfan** [comment]
"SDK location not found", is it possible to setup an android SDK without the big guy **Android Studio**? (have downloaded [sdkmanager](https://developer.android.com/studio/command-line/sdkmanager) but didn't figure out how to)

By checking the code, I found TestableMock dependence haven't been added in the `build.gradle`. Have you try added them and rerun the tests?

**Comment by linfan** [comment]
Sure : )
Checkout the attached zip.

The key point is below configuration inside the `app/build.gradle` file.

```
android {
    testOptions {
        unitTests {
            all {
                jvmArgs "-javaagent:${classpath.find { it.name.contains("testable-agent") }.absolutePath}"
            }
        }
    }
}
```

[testablemock-robolectric.zip](https://github.com/alibaba/testable-mock/files/5830864/testablemock-robolectric.zip)

**Comment by gospeljohn** [comment]
Cool， Thank you very much.

**Comment by linfan** [comment]
Happy to help, also thx for your Robolectric demo 😀.
