### ISSUE TITLE
java8 lambda '::' 关键字配合链式调用导致报ClassCastException

### ISSUE THREAD

**Issue by kxxfydj** [alibaba/testable-mock#44]
//一般的数据库表映射类，PO类
public class User {
    private String name;

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

}

//模拟一般的工具类方法
public class NameChanger {
    public static String changeName(String originName) {
        return originName + "hasChange";
    }
}

public class ChangeCenter {

    private ChangeCenter(){}

    public static ChangeCenter create() {
        return new ChangeCenter();
    }

    public User convert(Function<String,String> function) {
        String convert = function.apply("mmmmmm");
        User user = new User();
        user.setName(convert);
        return user;
    }
}

//lambda使用示例，对应一般的service类
public class DemoLambda {

    public String lambda() {
        return com.alibaba.testable.demo.model.ChangeCenter.create().convert(NameChanger::changeName).getName();
    }
}

//测试类
@MockWith(diagnose = MockDiagnose.ENABLE)
public class DemoLambdaTest {

    DemoLambda demoLambda = new DemoLambda();

    @MockMethod
    private String getName(User self) {
        return "name_from_test";
    }

    @Test
    public void test() {
        System.out.println(demoLambda.lambda());
    }
}

运行该测试用例，会得到如下的错误提示：
[WARN] Failed to transform class com/alibaba/testable/demo/DemoLambda
[DIAGNOSE] java.lang.ClassCastException: org.objectweb.asm.tree.InvokeDynamicInsnNode cannot be cast to org.objectweb.asm.tree.MethodInsnNode

源码追踪是NameChanger::changeName该代码导致com.alibaba.testable.agent.handler.SourceClassHandler#stackEffectOfInvocation该位置处的InvokeDynamicInsnNode被强转成了MethodInsnNode，导致报错。

但是如果DemoLambda代码改成如下：
public String lambda() {
        User user= ChangeCenter.create().convert(NameChanger::changeName);
        return user.getName();
}
测试则通过！

望回复，感谢！

**Comment by linfan** [comment]
感谢详细的反馈，目前我们用到场景里确实没有Mock Lambda之后调用的情况，从描述来看基本能确定是代码处理的BUG了。
预计会在下个版本里修复~

**Comment by linfan** [comment]
已发布`0.4.10`版本，包含此修复

**Comment by kxxfydj** [comment]
好的，很nice
