### ISSUE TITLE
配合Mockito使用，mock被测对象的方法失败

### ISSUE THREAD

**Issue by scxkd2016** [alibaba/testable-mock#46]
```java
public class HeroServiceImplTest extends BaseTest {

    @InjectMocks
    @Spy
    private HeroServiceImpl heroService;

    @Mock
    private WeatherClient weatherClient;

    @Mock
    private HeroMapper heroMapper;


    @MockMethod(targetClass = HeroServiceImpl.class, targetMethod = "story")
    public String story(String self, Long heroId, String cityCode) {
       return "hahahah";
   }


    @Test
    public void storyTest() {
        //String story = heroService.story(1L, "1024");//**此处未mock成功，仍调用了真实方法**
       //---------------------新增
        String story = heroService.callStory();
        System.out.println(story);
    }
}
```

```java
@Slf4j
@Service
public class HeroServiceImpl
        extends BaseServiceImpl<HeroMapper, Hero>
        implements HeroService {

    @Autowired
    private HeroMapper heroMapper;

    @Autowired
    private WeatherClient weatherClient;

    @Override
    public String story(Long heroId, String cityCode) {
        Hero hero = getById(heroId);
        if (hero == null) {
            return String.format("heroId为%d不存在", heroId);
        }

        WeatherExample.Response weather = weatherClient.query(cityCode);

        StringBuilder sb = new StringBuilder();
        sb.append("人物：").append(hero.getHeroName()).append("\n");
        sb.append("技能：").append(hero.getSkill()).append("\n");
        sb.append("地点：").append(weather.getCityInfo().getCity()).append("\n");
        sb.append("天气：").append(weather.getData().getYesterday().getNotice());

        return sb.toString();
    }
    //------------------------------新增
   public String callStory() {
        return this.story(1L,"999");
    }
}
```
使用spring boot，testable版本0.4.9，Mockito版本3.6.0

**Comment by linfan** [comment]
和[Issue-39](https://github.com/alibaba/testable-mock/issues/39)是同一个问题哈，你Mock的方法是`story`，在被测类里如果有其他方法调用了`story`方法，在测试运行的时候实际会执行你的Mock方法。
但在测试类里的方法，比如上面的`storyTest()`方法里，Mock是不会生效的。

被测类的代码因为本身包含业务逻辑，为了在测试的时候能够不影响原本的代码的情况下，绕过一些无需测试的部分，才需要Mock置换。测试类里面如果要访问Mock方法，直接调用就可以了哦，不存在需要动态被换成Mock的情况。

**Comment by scxkd2016** [comment]
> 和[Issue-39](https://github.com/alibaba/testable-mock/issues/39)是同一个问题哈，你Mock的方法是`story`，在被测类里如果有其他方法调用了`story`方法，在测试运行的时候实际会执行你的Mock方法。
> 但在测试类里的方法，比如上面的`storyTest()`方法里，Mock是不会生效的。
> 
> 被测类的代码因为本身包含业务逻辑，为了在测试的时候能够不影响原本的代码的情况下，绕过一些无需测试的部分，才需要Mock置换。测试类里面如果要访问Mock方法，直接调用就可以了哦，不存在需要动态被换成Mock的情况。

**Comment by scxkd2016** [comment]
> 和[Issue-39](https://github.com/alibaba/testable-mock/issues/39)是同一个问题哈，你Mock的方法是`story`，在被测类里如果有其他方法调用了`story`方法，在测试运行的时候实际会执行你的Mock方法。
> 但在测试类里的方法，比如上面的`storyTest()`方法里，Mock是不会生效的。
> 
> 被测类的代码因为本身包含业务逻辑，为了在测试的时候能够不影响原本的代码的情况下，绕过一些无需测试的部分，才需要Mock置换。测试类里面如果要访问Mock方法，直接调用就可以了哦，不存在需要动态被换成Mock的情况。

**Comment by scxkd2016** [comment]
> 和[Issue-39](https://github.com/alibaba/testable-mock/issues/39)是同一个问题哈，你Mock的方法是`story`，在被测类里如果有其他方法调用了`story`方法，在测试运行的时候实际会执行你的Mock方法。
> 但在测试类里的方法，比如上面的`storyTest()`方法里，Mock是不会生效的。
> 
> 被测类的代码因为本身包含业务逻辑，为了在测试的时候能够不影响原本的代码的情况下，绕过一些无需测试的部分，才需要Mock置换。测试类里面如果要访问Mock方法，直接调用就可以了哦，不存在需要动态被换成Mock的情况。

按照您说的，改了之后还是没有mock成功

**Comment by linfan** [comment]
麻烦贴下改过后的代码哦

**Comment by scxkd2016** [comment]
> 麻烦贴下改过后的代码哦

就是在原代码上改的，写着新增

**Comment by linfan** [comment]
> > 麻烦贴下改过后的代码哦
> 
> 就是在原代码上改的，写着新增

只是这样描述的话没法查原因哦。
Mock不成功一般来说是用法问题，也有可能是工具的BUG，不论哪一种，需要具体代码才能分析。

**Comment by linfan** [comment]
这个Issue我先关闭，如果依然有问题可以Reopen或另起Issue提出
