### ISSUE TITLE
SpringBoot项目中Gradle没法引入

### ISSUE THREAD

**Issue by wolfchinaliu** [alibaba/testable-mock#47]
错误信息：
Could not find method testAnnotationProcessor() for arguments [com.alibaba.testable:testable-processor:0.4.9] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
环境版本：JDK1.8，Gradle 6.7 和IDEA自带的Gradle都尝试了。IDEA版本版本：2020.3.2版本
builder.gradle 配置信息如下（部分）：
buildscript {

    ext {
        springBootVersion = '2.0.3.RELEASE'
    }

    repositories {
        mavenLocal()
  
        maven { url "https://repo.spring.io/plugins-release" }
    }
    dependencies {
        classpath("io.spring.gradle:propdeps-plugin:0.0.8")
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        testImplementation('com.alibaba.testable:testable-all:0.4.9')
        testAnnotationProcessor('com.alibaba.testable:testable-processor:0.4.9')
    }
    test {
        jvmArgs "-javaagent:${classpath.find { it.name.contains("testable-agent") }.absolutePath}"
    }
}

**Comment by linfan** [comment]
`testAnnotationProcessor()`方法是Gradle原生提供的，这个错误看起来和使用SpringBoot以及TestableMock都没有关系。
检查一下项目里是否有用了Gradle Wrapper（即 gradlew 文件），如果使用了，应该是IDEA自动加载了这个Wrapper，可以检查一下他的版本`./gradlew -version`。在Gradle（以及Gradle Wrapper） ≥ 4.6 的版本里都应该支持`testAnnotationProcessor()`这个配置。

**Comment by wolfchinaliu** [comment]
按照上述所说，我改变了Gradle版本为4.7以后确实可以引入jar包，但是test {
    jvmArgs "-javaagent:${classpath.find { it.name.contains("testable-agent") }.absolutePath}"
}这个命令一旦引入就会抛出异常A problem occurred evaluating project ':cgp-base-order'.
> Cannot change dependencies of dependency configuration ':cgp-base-order:compile' after it has been included in dependency resolution. 经过我的测试在引入这个脚本之前不会报错，引入之后就报错，请问下，知道是什么原因吗？Google蛮久看到这个错误各种解释都有

**Comment by linfan** [comment]
看起来是引入的某些插件想要动态增加依赖导致的，可以参考这个解法 https://github.com/freefair/gradle-plugins/issues/41

具体来说，首先在`build.gradle`文件里增加一个`configuration`：

```groovy
configurations {
    testableMock
    testImplementation.extendsFrom(testableMock)
}
```

然后在`dependencies`里引入`TestableMock`依赖的方式改为：

```groovy
dependencies {
    testableMock('com.alibaba.testable:testable-all:0.4.9')
    testAnnotationProcessor('com.alibaba.testable:testable-processor:0.4.9')
}
```

最后用这个新的`configuration`查找`testable-agent`：

```groovy
test {
    jvmArgs "-javaagent:${configurations.testableMock.find { it.name.contains("testable-agent") }.absolutePath}"
}
```

**Comment by linfan** [comment]
以仓库`java-demo`示例代码为例，修改后的完整`build.gradle`如下：

```groovy
plugins {
    id 'java'
}

group = 'com.alibaba.testable'
version = '1.0.0-SNAPSHOT'
sourceCompatibility = '8'

repositories {
    mavenLocal()
    mavenCentral()
}

configurations {
    testableMock
    testImplementation.extendsFrom(testableMock)
}

dependencies {
    testImplementation('org.junit.jupiter:junit-jupiter:5.6.2')
    testableMock('com.alibaba.testable:testable-all:0.4.9')
    testAnnotationProcessor('com.alibaba.testable:testable-processor:0.4.9')
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

test {
    jvmArgs "-javaagent:${configurations.testableMock.find { it.name.contains("testable-agent") }.absolutePath}"
    useJUnitPlatform()
}
```

**Comment by wolfchinaliu** [comment]
非常棒，这个问题已经完美解决了！

**Comment by wolfchinaliu** [comment]
但是Mock 没有成功，没有效果
mock对象：
package com.qpp.cgp.util;

public class MockDemo {
    public String demo(){
        String name = "test mock name";
        String substring = name.substring(0, 5);
        return substring;
    }
}
mockTest对象：
package com.qpp.cgp.util;

import com.alibaba.testable.core.annotation.MockMethod;
import org.junit.jupiter.api.Test;

public class MockDemoTest {

    @MockMethod(targetClass = String.class)
    private String substring(int i, int j) {
        return "sub_string";
    }

    private MockDemo mockDemo = new MockDemo();

    @Test
    public void testDemo() {
        String demo = mockDemo.demo();
        System.out.println(demo);
    }
}

**Comment by wolfchinaliu** [comment]
运行结果：test ，本来预期的结果不是应该是sub_string

**Comment by linfan** [comment]
我在测试项目上验证Mock是正常的。

试一下执行`gradle clean test --info`，留意一下输出内容在`> Task :test`这行下面会有一行`Starting process`开头的输出，这行打印实际执行测试的命令行参数。看下参数里是否有有包含`testable-agent-0.4.9.jar`这个Jar文件。

**Comment by linfan** [comment]
这个Issue我先关闭了，如果依然有问题可以Reopen或另起Issue提出
