### ISSUE TITLE
byte[]导致initialization失败

### ISSUE THREAD

**Issue by VicDelacroix** [alibaba/testable-mock#48]
发生问题的case如下
Mono<byte[]> func(byte[] args)，没有具体验证是作为入参还是作为返回值时导致的
推测应该是作为泛型时会发生，byte[]直接作为返回值时没有问题

**Comment by linfan** [comment]
并非泛型导致，和`byte[]`类型参数有关，使用`Byte[]`的话正常，具有原因待查。
预计能在下个小版本里修复。

**Comment by linfan** [comment]
已在`0.4.11`版本中修复
