### ISSUE TITLE
[ERROR] Failed to find `this` reference in non-static method my/package/MyTestClass:substring

### ISSUE THREAD

**Issue by brucecui** [alibaba/testable-mock#49]
刚刚接触，在看文档做一些简单的验证。但是所有简单的method mock都在测试方法启动前，抛类似标题描述的错误.

加了@MockWith(diagnose = MockDiagnose.ENABLE)之后，在第一行[DIAGNOSE]... 之后就报错。每个mock method都报错，然后还是继续执行test method，只是都没有mock效果。

我的运行环境是Java8，Gradle 4.10。配置是按照文档里配的： https://alibaba.github.io/testable-mock/#/zh-cn/doc/setup

**Comment by linfan** [comment]
把`@Mock`的方法声明为`static`就可以了，和文档”特别说明“里提到的是同一个原因导致的：
https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock?id=特别说明

这个问题会在`0.5`版本里彻底解决，预计会在2月中旬春节之前发布哈

**Comment by brucecui** [comment]
添加static之后error确实都消失了，但是mock没有起作用。而且我mock的method是文档里的String的substring，应该不是静态方法。

**Comment by brucecui** [comment]
而且error虽然消失了，第一行[DIAGNOSE]之后就没有更多log了，没有[DIAGNOSE] Handling source class...以及后面这些

然后就是执行test method了。Mock method也没有生效。

我的mock method和文档是一样的

@MockMethod(targetClass = String.class)
private String substring(int i, int j) {
    return "sub_string";
}

加上static就是

@MockMethod(targetClass = String.class)
private static String substring(int i, int j) {
    return "sub_string";
}

**Comment by brucecui** [comment]
是因为路径原因吗？我的test class和source class包名是一样的，test class name也是source class + Test。但是gradle编译之后的class是放在两个路径下的。类似这样。
.../classes/java/test/my/package/MyClassTest.class
.../classes/java/main/my/package/MyClass.class

**Comment by linfan** [comment]
编译后的路径不影响，包名一样、类名符合就可以。
从日志输出的现象上看是只找到了测试类，没有识别到被测类，这个问题一般是包名或者类名不匹配的时候才会发生

**Comment by linfan** [comment]
> 添加static之后error确实都消失了，但是mock没有起作用。而且我mock的method是文档里的String的substring，应该不是静态方法。

将Mock方法声明为`static`并不是因为被Mock的方法是静态，而是复杂的Mock方法会在编译期生成额外的临时函数，默认生成的是非静态的，在当前版本会有问题。但这个Mock方法只是直接return一个值按说是无需改成`static`的，像是还有什么特别的地方。
可以加我的钉钉详细沟通 #9

**Comment by linfan** [comment]
这个Issue我先关闭，如果依然有问题可以Reopen或另起Issue提出
