### ISSUE TITLE
MockMethod无效，无法对方法进行mock

### ISSUE THREAD

**Issue by YIXIANG0234** [alibaba/testable-mock#50]
@EnablePrivateAccess
public class OrderServiceImplTestWithAlibaba {
    private OrderServiceImpl testInstance = new OrderServiceImpl();

    @MockMethod(targetClass = com.ctrip.car.customerservice.utils.QConfigUtils.class, targetMethod = "getValue")
    public String getValue(String key) {
        String json = "[{\"tagName\":\"\",\"key\":\"安心行\",\"type\":\"equal\",\"template\":\"<span>安心行说明文案安心行说明文案安心行说明文案111<a href='http://www.baidu.com' target='_blank'>查看conf</a></span>\"}]";
        return json;
    }
    @Test
    public void tetGetTagDescription(){
        List<String> tags = Lists.newArrayList("无忧租","安心行");
        PrivateAccessor.set(testInstance, "qConfigUtils" ,new com.ctrip.car.customerservice.utils.QConfigUtils());
        List<TagDescription> list = PrivateAccessor.invoke(testInstance, "getTagDescription", tags);
        assertNotNull(list);
    }
}

单测运行的时候，打了断点没有执行上面MockMethod的方法，而是执行了下面这个原有的实现
	public String getValue(String key) {
		return MapUtils.getString(paramsMap, key);
	}

**Comment by linfan** [comment]
应该是测试类命名的原因，目前版本要求测试类与被测类包名一致，且类名是"被测类+Test"
在文档”特别说明“里有提到：https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock?id=特别说明

**Comment by YIXIANG0234** [comment]
> 应该是测试类命名的原因，目前版本要求测试类与被测类包名一致，且类名是"被测类+Test"
> 在文档”特别说明“里有提到：[https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock?id=特别说明](https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock?id=%E7%89%B9%E5%88%AB%E8%AF%B4%E6%98%8E)
