### ISSUE TITLE
通过 @Reference引用Dubbo Facade怎么注入到被测试类中

### ISSUE THREAD

**Issue by ningtalk** [alibaba/testable-mock#51]
文档里有说明使用@Autowire注入的可用通过PrivateAccessor.set(被测对象, "私有字段名", 新的值)来注入。
 像引用外部Dubbo接口，Facade包里不会提供接口的实现类，所以接口没法new一个新的值，这种情况怎么处理。

如下，被测试类是CollectBizImpl： 

@Component
@Slf4j
public class CollectBizImpl implements CollectBiz {
	/**
	* 引用dubbo接口
	*
	*/
    @Reference
    private CollectRouterFacade collectRouterFacade;

    @Override
    public Result initiateCollect(CollectReqDTO reqDTO) {

    	// do something 

    	XxxResultDTO resultDTO = collectRouterFacade.collect(xxx,xxx);

    	// resolve resultDTO
    
    	return result; 
    }
 }

**Comment by linfan** [comment]
如果Facade里的接口不太多，可以new一个匿名类，比如：

```java
PrivateAccessor.set(collectBiz, "collectRouterFacade", new CollectRouterFacade() {
    ... // 这里覆写接口方法，可以根据测试需要来实现
});
```

用IDE辅助可以批量补齐需要覆写的方法

**Comment by npvip** [comment]
在这种情况下，使用PrivateAccessor.set覆写Facade的方法，实际上就已经完成了mock，不需要使用@MockMethod。
如果@Autowire直接引用的是类而不是接口，使用PrivateAccessor.set注入时，就要new一个对象，运行测试时，会调用这个new的对象，达不到mock这个对象的效果。

**Comment by npvip** [comment]
> 如果Facade里的接口不太多，可以new一个匿名类，比如：
> 
> ```java
> PrivateAccessor.set(collectBiz, "collectRouterFacade", new CollectRouterFacade() {
>     ... // 这里覆写接口方法，可以根据测试需要来实现
> });
> ```
> 
> 用IDE辅助可以批量补齐需要覆写的方法

**Comment by npvip** [comment]
@Component
public class AService {

    @Autowired
    private BComponent bComponent;


    public String createOrder(XxxReq req) {

        String orderNo = bComponent.getOrderNo();
        // do something

        return "";
    }
}

@Component
public class BComponent {

    @Autowired
    private CComponent cComponent;

    public String getOrderNo() {
        // do something
        String id = cComponent.makeDistibutedId();
        // do something
        return id;
    }
}

测试类为AService，针对这种情况怎么mock？
如果使用PrivateAccessor.set来设置bComponent，那么new BComponent()之后还要使用PrivateAccessor.set来设置cComponent吗

**Comment by npvip** [comment]
也就是针对@Autowire的情况，通过PrivateAccessor.set注入依赖后，怎么对调用此依赖的方法进行mock。

**Comment by npvip** [comment]
对于Mabatis的Mapper接口也是类似的处理方式吗？有没有其他方式

**Comment by linfan** [comment]
PrivateAccessor.set注入以后，如果被测的方法里用了set进去的对象，`@MockMethod`是可以在测试的时候把调用替换成Mock方法的。比如set进去的对象是`BComponent`，接下来可以用`@MockMethod(targetClass = BComponent.class)`去换要调用的方法。

需要澄清的一件事是单元测试一般不推荐跨类进行Mock。在比较规范的单元测试里，`AServiceTest`类应该只做`AService`代码逻辑的验证。比如上面的例子，把一个`BComponent`类型对象`bComponent`放到被测的`AService`对象里以后，可以把不想执行的`bComponent`对象方法调用Mock掉。但在`BComponent`类型的代码里再调用`CComponent`的逻辑应该在`BComponentTest`测试类去做，因此`AServiceTest`里用的`bComponent`对象里的`cComponent`为空对这个测试类应该不影响。

如果确实要做跨类（跨单元）的单元测试，其实也能实现，需要在`BComponent`的Mock类里写对`cComponent`对象的Mock，但在目前的TestableMock版本里这样写测试会导致可读性下降比较多，正在重构中的`0.5`版本对这种场景的支持会更好一些。

**Comment by lithStudy** [comment]
这样写有点复杂啊，尤其是接口比较多的类，这样实现起来虽然idea可以自动生成，但是代码一大堆

**Comment by linfan** [comment]
@lithStudy 确实比较大的临时类，可以在测试目录里单建文件来放，这样即不会让测试类变得很乱，又能在需要的时候进行复用

**Comment by linfan** [comment]
0.5.0版本已发布🚀
