### ISSUE TITLE
测试类使用调用使用了@Service和@Component注解的服务类的方法时，使用@Autowired无法注入该服务类

### ISSUE THREAD

**Issue by tufei3166** [alibaba/testable-mock#54]

**Comment by tufei3166** [comment]
/**
 * mock测试
 *
 */
public class DemoSelfTest {

    @Autowired
    ConfigService configService;

    @MockMethod(targetClass = ConfigService.class, targetMethod = "getByName")
    private ConfigVO getByName(ConfigService configService, StringXO stringXO) {
        return configService.getByName(stringXO);
    }

    @Test
    public void getByName() {
        StringXO stringXO = new StringXO();
        stringXO.setStr("SALE_TEACHER_LIST");
        ConfigVO byName = configService.getByName(stringXO);
        System.out.println(byName);
    }

}

**Comment by tufei3166** [comment]
@Slf4j
@Service
@AllArgsConstructor
@Component
public class ConfigService {

    private final IConfigService configService;

    /**
     * 根据名称查询配置
     *
     * @param
     * @return
     */
    public ConfigVO getByName(StringXO param) {

        if (StrUtil.isEmpty(param.getStr())) {
            return null;
        }

        Config config = configService.getOne(
            new LambdaQueryWrapper<Config>().eq(Config::getName, param.getStr()));

        return ObjectUtil.isEmpty(config) ? null : CloneUtils.clone(config, ConfigVO.class);
    }
}

**Comment by linfan** [comment]
感觉你是想Mock在`DemoSelfTest::getByName()`方法里的`getByName()`调用，测试类里的方法是不会被Mock替换的~

可以试下在`ConfigService`的某个方法里调用`getByName()`，在测试的时候会被动态替换成Mock方法。另外目前要求测试类名称是”被测类+Test“哦，所以测试类的名字应该是`ConfigServiceTest`

**Comment by weiwang00707** [comment]
请问 linfan，这样的如何测试呢？


@Service
public class VerificateTransactionServiceImpl implements VerificateTransactionService{
    @Autowired
    CustomDocRespository customDocRespository;

    @Autowired
    CustomerDocSerialNbrRespository customerDocSerialNbrRespository;

    @Override
    @Transactional(transactionManager = TransactionMangers.DEFAULT)
    public void updateCustomsVerifyInfo(Integer poNo, List<CustomsDoc> customsDocs, List<CustomsDocSerialNbr> customsDocSerialNbrs) {
      
        if(!ObjectUtil.isEmpty(updateCustomDocs)){
            customDocRespository.saveAll(updateCustomDocs);
        }

        if(!ObjectUtil.isEmpty(customsDocSerialNbrs)){
            customerDocSerialNbrRespository.saveAll(customsDocSerialNbrs);
        }

    }

customDocRespository 测试时候 为空 报错了

**Comment by tufei3166** [comment]
> 感觉你是想Mock在`DemoSelfTest::getByName()`方法里的`getByName()`调用，测试类里的方法是不会被Mock替换的~
> 
> 可以试下在`ConfigService`的某个方法里调用`getByName()`，在测试的时候会被动态替换成Mock方法。另外目前要求测试类名称是”被测类+Test“哦，所以测试类的名字应该是`ConfigServiceTest`

嗯嗯，目前测试类的名称是遵照规范的，之前的代码粘错了

**Comment by tufei3166** [comment]
> 感觉你是想Mock在`DemoSelfTest::getByName()`方法里的`getByName()`调用，测试类里的方法是不会被Mock替换的~
> 
> 可以试下在`ConfigService`的某个方法里调用`getByName()`，在测试的时候会被动态替换成Mock方法

这里我想做的是，ConfigService有一个getByName方法，ConfigServiceTest测试类想mock一下，但是在ConfigServiceTest通过
@Autowired注入ConfigService时，在
    @Test
    public void getByName{}，获取到的configService 是null

**Comment by linfan** [comment]
> customDocRespository 测试时候 为空 报错了
@weiwang00707 被测类里Autowire注入的私有成员，在测试里先用私有方法访问机制直接赋值一下

**Comment by linfan** [comment]
@tufei3166 `ConfigServiceTest`里`@Autowired`注入`ConfigService`为空是因为单元测试里Spring容器默认不会初始化，和使用哪种Mock工具没有关系。可以直接new一个ConfigService对象来测试，或者用`@RunWith(SpringRunner.class)`在测试运行的时候初始化Spring容器，后者会慢很多，一般直接new被测对象就行了。

**Comment by tufei3166** [comment]
> @tufei3166 `ConfigServiceTest`里`@Autowired`注入`ConfigService`为空是因为单元测试里Spring容器默认不会初始化，和使用哪种Mock工具没有关系。可以直接new一个ConfigService对象来测试，或者用`@RunWith(SpringRunner.class)`在测试运行的时候初始化Spring容器，后者会慢很多，一般直接new被测对象就行了。

ConfigService是这样的，没办法new
@slf4j
@service
@AllArgsConstructor
@component
public class ConfigService {

private final IConfigService configService;

/**
 * 根据名称查询配置
 *
 * @param
 * @return
 */
public ConfigVO getByName(StringXO param) {

    if (StrUtil.isEmpty(param.getStr())) {
        return null;
    }

    Config config = configService.getOne(
        new LambdaQueryWrapper<Config>().eq(Config::getName, param.getStr()));

    return ObjectUtil.isEmpty(config) ? null : CloneUtils.clone(config, ConfigVO.class);
}

**Comment by linfan** [comment]
支持在测试类里修改被测类的常量成员的哈。

在`ConfigServiceTest`的构造函数里，用例如`PrivateAccessor.set(<被测类对象>, "configService", new XxxConfigServiceImpl())`初始化就可以了。也可以给测试类加`@EnablePrivateAccess`注解，然后直接对私有常量赋值。
具体可以参考文档https://alibaba.github.io/testable-mock/#/zh-cn/doc/private-accessor

**Comment by linfan** [comment]
如果没有更多问题，这个Issue就先关闭了哦，后续讨论可以Reopen或者另开Issue
