### ISSUE TITLE
有交流群么~想加

### ISSUE THREAD

**Issue by FlyingPigHasDream** [alibaba/testable-mock#55]

**Comment by linfan** [comment]
目前没有足够精力来打理一个单独的群哈，有任何相关问题先在Github issue提出吧，确保24小时内回复处理

**Comment by FlyingPigHasDream** [comment]
可以志愿者运维 有社区发展会快一些

**Comment by linfan** [comment]
我们的主线业务是阿里云的整体产研平台，工具好用就行，现在不做过多运营哈，容易分心🤗
感谢提议~
