### ISSUE TITLE
mock  controller的方法，controller里面的service报空

### ISSUE THREAD

**Issue by Gauplus** [alibaba/testable-mock#57]
请问类似这种情况怎么mock, service会报空指针

class Controller{
        public object handle(String s){
               service.handle(s);
    }
}

测试方法
public class ControllerTest{
    @MockMethod(targetClass = CapabilityTransferController.class)
    public Object handle(String s) {
        return s;
    }
    CapabilityTransferController capabilityTransferController = new CapabilityTransferController();

    @Test
    public void controlTest(){
        String s = "123";
        capabilityTransferController.controlTransfer(s);

    }
}

**Comment by linfan** [comment]
和 #58 问题一样，先用`@EnablePrivateAccess`的或者`PrivateAccessor`工具类给`service`初始化一下

**Comment by Gauplus** [comment]
PrivateAccessor.set(Controller.class,"service",new serviceImpl());
报错没有该属性，而实际是有的

**Comment by linfan** [comment]
第一个参数应该传被测的具体对象，不是类型。比如：
` PrivateAccessor.set(controller, "service", new serviceImpl());`

**Comment by linfan** [comment]
如果没有更多问题，这个Issue就先关闭了哦
