### ISSUE TITLE
对于被测试类 又有注入的service 怎么测试呢？

### ISSUE THREAD

**Issue by weiwang00707** [alibaba/testable-mock#58]
![image](https://user-images.githubusercontent.com/6139048/106236273-71fc1000-6237-11eb-93ad-c17a7cde984c.png)

**Comment by linfan** [comment]
在测试用例里可以直接用`@EnablePrivateAccess`的功能或者`PrivateAccessor`工具类对私有字段赋值，不用绕弯哈

**Comment by weiwang00707** [comment]
thanks，试了下发现新的问题 提示找不到 字段

@Service
public class VerificateTransactionServiceImpl implements VerificateTransactionService{
    @Autowired
    CustomDocRespository customDocRespository;

    @Autowired
    CustomerDocSerialNbrRespository customerDocSerialNbrRespository;

    private  String name ="aaa";

}


PrivateAccessor.set(service,"name","bbb");

**Comment by linfan** [comment]
看起来没理由会报错啊...

上面的代码如果是`PrivateAccessor`访问非私有但是存在的字段，比如`customerDocSerialNbrRespository`倒是确实会报"not exist"的错误，这个问题已经在内部的SNAPSHOT版本里改成是报Warning了，在下个正式版里会包含。但这个`name`是private声明的，解释不通🤔

如果是稳定复现的话，看能否提供一个脱敏的可复现文件，具体查下原因。

**Comment by linfan** [comment]
我可能找到原因了，有个小BUG会导致新增成员变量和方法在下一次全量构建之前，在IDE直接进行构建的时候无法被识别到，这个问题在下个版本里会修掉。
目前有一个绕过办法是不用加`@EnablePrivateAccess`注解，这样既不会影响`PrivateAccessor`工具类的使用，同时也不会启用编译期的私有成员检查。

**Comment by linfan** [comment]
`0.4.11`版本已发布，可以试一下是否解决此问题

**Comment by linfan** [comment]
Issue先关闭了哈，如果在`0.4.11`及以后版本还有复现请Reopen或者另提Issue

**Comment by bqingAll** [comment]
> 看起来没理由会报错啊...
> 
> 上面的代码如果是`PrivateAccessor`访问非私有但是存在的字段，比如`customerDocSerialNbrRespository`倒是确实会报"not exist"的错误，这个问题已经在内部的SNAPSHOT版本里改成是报Warning了，在下个正式版里会包含。但这个`name`是private声明的，解释不通🤔
> 
> 如果是稳定复现的话，看能否提供一个脱敏的可复现文件，具体查下原因。

您好  跟这个issues类似 我们的 service 里也有类似customDocRespository的 dao层  但它是接口且没有实现类，我通过PrivateAccessor给service赋值后运行 会接着报错customDocRespository 空指针  这种怎么处理，只能手动临时创建一个dao实现类吗

**Comment by Zlatq5** [comment]
dao接口这种解决了吗
