### ISSUE TITLE
Mock 方法在不同类中能够隔离

### ISSUE THREAD

**Issue by subchen** [alibaba/testable-mock#59]
文档中提及
```
6. 当被Mock的方法被其它测试类间接调用时依然有效吗？
同样有效，Mock的作用范围是整个测试运行过程。

例如测试类AaaTest中Mock了Aaa类的某些私有方法（或者某些外部方法调用）；在另一个测试类BbbTest中测试Bbb类时，某些方法间接用到了Aaa类被Mock过的方法或调用，此时实际调用的同样会是AaaTest类中定义的Mock方法。
```

这个对于不同测试类是非常不友好的，而且没有办法还原被Mock的方法。建议修改字节码生成的mock方法，并增加reset功能。
比如：

对于每个Mock Method 生成的代码里面增加一个flag判断， 默认调用原始方法，只有在mock test class 里面才调用mock method.

```
Set<String> mock_method_set = new HashSet();
public void mockMethod(args) {
    if (mock_method_set.contain(method_name)) {
        call_original_method(method_name, args);
        return;
    }
    call_mock_method(method_name, args);
    return;
}

public void resetAllMockMethods() {
    mock_method_set.clear();
}
```

在 TestClass 里面利用 Junit 的 `@AfterClass` 加入 `resetAllMockMethods()` 调用

```
@AfterClass
public void clean() {
    TestableMock.resetAllMockMethods();
}
```

这样，每个 TestClass 就是一个干净的环境，不会被其他 TestClass 的 MockMethod 影响

**Comment by linfan** [comment]
这是一个非常好的提议。
我们确实已经收到不少关于Mock跨类生效导致意外问题的反馈，计划在将来的某个版本里统一来处理，目前有两个备选方案：
1. MockMethod注解增加一个（非必填的）标签选择参数，只对包含特定标签的用例生效
2. 默认Mock不跨类生效，可选择性的开启跨类（或者反过来）

开发时间预计要在当前正在进行的重构版本（0.5版本）之后，大约是`0.6`版本左右

**Comment by subchen** [comment]
感觉方案2更好

**Comment by linfan** [comment]
已支持方案2~
https://alibaba.github.io/testable-mock/#/zh-cn/doc/scope-of-mock
对需要隔离的方法加 scope = MockScope.ASSOCIATED 即可
