### ISSUE TITLE
公共方法、私有方法都无法mock

### ISSUE THREAD

**Issue by mjhgithub** [alibaba/testable-mock#6]
@Data
public class IcoHome {
    private String no;
    private String name;
    private Integer age;
}

public class IcoHomeMethod {
    public IcoHome pubMethod(String no) {
        return priMethod(no);
    }
    private IcoHome priMethod(String no) {
        return null;
    }
}

@Slf4j
public class IcoHomeServiceTests {

    private IcoHomeMethod method = new IcoHomeMethod();

    @MockMethod(targetMethod = "pubMethod")
    public IcoHome mockPubMethod(IcoHomeMethod self, String no) {
        IcoHome icoHome = new IcoHome();
        icoHome.setNo("1");
        icoHome.setName("mjh");
        icoHome.setAge(8);
        return icoHome;
    }

    @MockMethod(targetMethod = "priMethod")
    private IcoHome mockPriMethod(IcoHomeMethod self, String no) {
        IcoHome icoHome = new IcoHome();
        icoHome.setNo("2");
        icoHome.setName("mjh");
        icoHome.setAge(9);
        return icoHome;
    }

    @Test
    public void getByNoTest() {
        IcoHome byNo = method.pubMethod("3");
        log.info("{}", byNo);
        verify("mockPubMethod").withTimes(1);
        verify("mockPriMethod").withTimes(1);

    }
}

com.alibaba.testable.core.error.VerifyFailedError: 
Expected times: 1
  Actual times: 0

	at com.alibaba.testable.core.matcher.InvokeVerifier.withTimes(InvokeVerifier.java:98)

**Comment by linfan** [comment]
Mock的作用是替换被测类里包含外部调用或者无需被测的执行单元，因此是在**被测类**里的调用才有必要被换掉，测试用例里的调用是无需Mock的。

可以试试在`IcoHomeMethod`里的其他方法调用`pubMethod()`和`priMethod()`方法，在执行测试的时候，就会被自动换成调用Mock方法了哦~

**Comment by mjhgithub** [comment]
IcoHomeMethod中加了方法调用

    public void testMock(){
        pubMethod("u");
        priMethod("i");
    }
    
测试还是不成功

    @Test
    public void getByNoTest() {
        method.testMock();
        verify("mockPubMethod").withTimes(1);
        verify("mockPriMethod").withTimes(1);
    }
    
    另外确认下，verify的参数是mock时定义的方法名，而不是targetMethod的值是吧？
        @MockMethod(targetMethod = "pubMethod")
    public IcoHome mockPubMethod(IcoHomeMethod self, String no) {
        IcoHome icoHome = new IcoHome();
        icoHome.setNo("1");
        icoHome.setName("mjh");
        icoHome.setAge(8);
        return icoHome;
    }

**Comment by mjhgithub** [comment]
找到原因了，单元测试类名的格式必须是被mock类名+Test，否则无法mock
例如要测试的类是IcoHomeMethod，则单元测试的类名必须是IcoHomeMethodTest

如果确认有这样的命名规则，最好在文档中说明下，才能快速上手避免做无用功

**Comment by mjhgithub** [comment]
查看源码 
ConstPool 类，测试类后缀
public static final String TEST_POSTFIX = "Test";

TestableClassTransformer类，测试类后缀名检测方法
    private boolean shouldTransformAsTestClass(String className) {
        return className.endsWith(ConstPool.TEST_POSTFIX) && hasMockAnnotation(className);
    }
    
TestableClassTransformer  类transform方法调用 shouldTransformAsTestClass，确定原因就是我上一条所说

        try {
            if (shouldTransformAsSourceClass(className)) {
                // it's a source class with testable enabled
                LogUtil.diagnose("Handling source class %s", className);
                List<MethodInfo> injectMethods = getTestableMockMethods(ClassUtil.getTestClassName(className));
                bytes = new SourceClassHandler(injectMethods).getBytes(classFileBuffer);
                resetMockContext();
            } else if (shouldTransformAsTestClass(className)) {
                // it's a test class with testable enabled
                LogUtil.diagnose("Handling test class %s", className);
                bytes = new TestClassHandler().getBytes(classFileBuffer);
                resetMockContext();
            }
        } catch (IOException e) {
            LogUtil.warn("Failed to transform class " + className);
        }

**Comment by mjhgithub** [comment]
还有ClassUtil工具栏中有获取测试类和源类名称的方法

    /**
     * get test class name from source class name
     * @param sourceClassName source class name
     * @return test class name
     */
    public static String getTestClassName(String sourceClassName) {
        return sourceClassName + ConstPool.TEST_POSTFIX;
    }

    /**
     * get source class name from test class name
     * @param testClassName test class name
     * @return source class name
     */
    public static String getSourceClassName(String testClassName) {
        return testClassName.substring(0, testClassName.length() - ConstPool.TEST_POSTFIX.length());
    }

**Comment by linfan** [comment]
感谢反馈，这个约束我稍后补充到文档里，一般来说Java里的测试类都会符合这个惯例，但确实文档应该明确写出来。

**Comment by linfan** [comment]
在下一个大版本(v0.5.0)前，我们会评估一下能否放宽或者去掉这个约束。已创建[Issue-12](https://github.com/alibaba/testable-mock/issues/12)跟踪。

**Comment by linfan** [comment]
文档已更新
https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock

**Comment by liudaolunboluo** [comment]
除了类名一致，路径也需要一致，因为在transform的classname是com/XX/XX这种绝对路径，如果你的测试类也要是一样的com/XX/XX才行，这个感觉有点问题
