### ISSUE TITLE
对于Mabatis的Mapper接口，有什么解决方案，能不能给一个 demo

### ISSUE THREAD

**Issue by ZivYan** [alibaba/testable-mock#60]

**Comment by linfan** [comment]
Mapper接口只是实现类在编译期自动生成，和Mock普通接口的方法没有什么差别哈。

在`DemoInheritTest.java`示例里有一个`get_color_from_color()`方法Mock的目标就是接口类的方法，其实就当成普通方法调用一样写就可以了。

**Comment by linfan** [comment]
如果没有更多问题，这个Issue就先关闭了。若有其他相关问题，可以随时Reopen或另建Issue处理
