### ISSUE TITLE
参考issue#38，mock RedisTemplate的方法 未生效

### ISSUE THREAD

**Issue by Kate0000** [alibaba/testable-mock#61]
被mock方法： redisTemplate.opsForValue().setIfAbsent(K key, V value, long timeout, TimeUnit unit)

mock方法：
@MockMethod(targetMethod = "selfIfAbsent")
public <K,V> Boolean setIfAbsent(ValueOperations<K,V> self, K key, V value, long timeout, TimeUnit unit){
...
}

**Comment by linfan** [comment]
`targetMethod`参数的值拼错了，应该是"setIfAbsent"，其实可以直接把`targetMethod`这个参数去掉的 🤪

**Comment by Kate0000** [comment]
感谢指正，题目确实写错了， 实际代码里没有写错，为什么mock没有生效呢；
如果去掉targetMethod，mock的是setIfAbsent的方法还是整个ValueOperations类呢？

**Comment by Kate0000** [comment]
感谢指正， 问题描述的确写错了， 代码里是正确的， 不过因此仔细检查了mock代码， 发现是mock代码的判断写的有问题， 总之非常感谢。
