### ISSUE TITLE
InvokeVerifier  建议增加 doThrow

### ISSUE THREAD

**Issue by xuzhuocool** [alibaba/testable-mock#62]
应对方向内异常抛出校验。

**Comment by linfan** [comment]
为什么会需要验证Mock方法是否有抛出异常呢，可以举个具体使用场景吗？

`InvokeVerifier`目前主要用来检测Mock方法被调用时候的输入参数是否符合预期。Mock方法本身定义在测试类里，里面是否有抛异常应该一目了然，按我的理解，应该不太需要在测试用例里再进行断言。

**Comment by xuzhuocool** [comment]
比如需要单测的方法中，如果入参不合法，会抛出自定义的异常，抛出的异常是否符合预期的校验。

**Comment by linfan** [comment]
这个应该是单元测试框架的处理范畴哈，比如JUnit 4的`expected`参数和JUnit 5的`assertThrows`方法。对Mock工具来说主要关心的是Mock方法被调用时候的情况断言，这些断言单元测试框架本身提供不了，所以需要Mock工具来补充

**Comment by xuzhuocool** [comment]
嗯，不是提供校验mock工具么， 我说的类似 Mockito  doThrow()

**Comment by linfan** [comment]
doThrow()是用来定义Mock方法的语句哈，对TestableMock来说，直接在Mock方法里写throw语句就可以了~ 类似这样

```
@MockMethod
private int name() {
    throw new Exception();
}
```
