### ISSUE TITLE
难受!  为什么我mock什么都不生效

### ISSUE THREAD

**Issue by colagy** [alibaba/testable-mock#63]
![image](https://user-images.githubusercontent.com/37213080/106446119-d11d8700-64ba-11eb-8896-1cab9318ccaa.png)

**Comment by linfan** [comment]
Mock是针对被测类里的代码哈，对测试类自己的代码是不生效的。

可以试想一下为啥要用到Mock~~ 是因为被测的类里有些代码有业务逻辑，不能为了测试而修改，但是它又调用了外部依赖，在做单元测试时候就要把这部分调用跳过去。测试类里的代码不想要直接删就可以啦，不用Mock的。

**Comment by colagy** [comment]
好的 知道了 我就是想测试一下这个mock是不是可以这么用

**Comment by linfan** [comment]
好的，那么这个Issue我关闭了哦
