### ISSUE TITLE
mock失败

### ISSUE THREAD

**Issue by todaynie1** [alibaba/testable-mock#64]
首先非常感谢开源这么好的软件
我们在使用的过程中发现有一种情况会mock失败
假设ServiceA中有个方法testA，该方法会调用ServiceB的testB方法，testB方法又会调用ServiceB中的testB2，对testB2方法mock就会失败，如果mock testB方法是成功的，如果直接测试ServiceB的testB方法，同样mock testB2方法就能成功，不知道是不是我使用问题，还请指点，万分感谢

**Comment by linfan** [comment]
确实如此，TestableMock设计的基本思路是给每个被测类搭配一个Mock类，这个类中的Mock定义只对相应被测类中的代码生效。
在`ServiceA`的Test类里写的Mock方法只对`ServiceA`里的代码有效，而对`ServiceB`中的`testB`方法调用`testB2`无效；而在`ServiceB`的Test类里就可以Mock掉`testB`里的`testB2`方法调用。

对于比较规范的单元测试而言，Test类里的用例所测试的应该是被测单元内部的逻辑，而不应该去做跨单元的Mock，这一点与TestableMock的设计是一致的。

在正在开发中的`0.5`版本里，会支持Mock类和Test分离（在当前版本中，Mock类和Test类实际是同一个类），这种对应关系会表现得更清晰。

**Comment by todaynie1** [comment]
好的，感谢，我们来调整测试代码
