### ISSUE TITLE
通用mapper 带泛型的话找不到方法，mock不生效

### ISSUE THREAD

**Issue by yankun2** [alibaba/testable-mock#65]
![image](https://user-images.githubusercontent.com/37324363/106464871-35007980-64d4-11eb-92c3-e3fc160bb3c6.png)
![image](https://user-images.githubusercontent.com/37324363/106464944-4e092a80-64d4-11eb-8a39-e453a77d5d56.png)
![image](https://user-images.githubusercontent.com/37324363/106464987-59f4ec80-64d4-11eb-891c-cb09eee339b7.png)

**Comment by linfan** [comment]
Mock带泛型的方法应该是支持的。
从截图里看不出来 selectByPrimaryKey 方法的原始定义是什么，应该是 `<T> DateTest selectByPrimaryKey(T key)` ？

建议直接贴一下代码哈，便于做复现和排查，截图的代码拷贝不了。单从这几张截图上看确实应该要生效才对。

**Comment by yankun2** [comment]
![image](https://user-images.githubusercontent.com/37324363/106583315-ee685900-657f-11eb-8276-88f9bd67961c.png)
    T selectByPrimaryKey(Object key);

**Comment by linfan** [comment]
Mock方法需要和原方法声明一致哈，按这个方法定义的话，Mock声明应该是：

```
@MockMethod(targetClass = DateTestMapper.class)
private <T> T selectByPrimaryKey(Object key) {}
```

或者用Object代替泛型：

```
@MockMethod(targetClass = DateTestMapper.class)
private Object selectByPrimaryKey(Object key) {}
```

后面这种也能匹配是因为JVM的类型擦除机制，泛型在运行期等同于Object，但使用DateTest的话就匹配不上了

**Comment by linfan** [comment]
如果没有更多问题，这个Issue就先关闭了。若有其他相关问题，可以随时Reopen或另建Issue处理
