### ISSUE TITLE
链路流程mock

### ISSUE THREAD

**Issue by kris-J** [alibaba/testable-mock#66]
testable-mock看起来主攻的是开发阶段的单元测试，是否在测试联调阶段有对整个流程的关键点mock控制？
项目中利用较少的代码侵入性，接入mock管理平台，可进行灵活挡板控制？

**Comment by linfan** [comment]
TestableMock是针对单元测试的，多服务集成测试的Mock推荐试试[Moco](https://github.com/dreamhead/moco)

**Comment by linfan** [comment]
如果没有更多问题，这个Issue就先关闭了。若有其他相关问题，可以随时Reopen或另建Issue处理
