### ISSUE TITLE
Mock被测类中通过@Autowired @Resource初始化的字段提供依赖注入

### ISSUE THREAD

**Issue by Ryan-ff** [alibaba/testable-mock#68]
使用注解创建测试类成员变量实例，根据@Resource或者@Autowired 自动（byName）注入目标测试类成员变量
```
class DemoTest {

    @MockBean("demoService")
    private DemoService demoService;

    //或者
    @MockBean("demoService")
    private DemoService getDemoService() {
        return new DemoService();
    }

    @MockMethod(targetClass = DemoService.class)
    private void handle() {
        return "test_hello";
    }

}

//被测试类
class Demo {

    @Resource
    private DemoService demoService;

    public String handle() {
        return demoService.handle();
    }
}

class DemoService {

    public String handle() {
        return "hello";
    }
}
```

**Comment by colagy** [comment]
妙啊

**Comment by linfan** [comment]
写个方法来定义有些啰嗦，下面这种是可以考虑支持的

```
@MockBean("demoService")
private DemoService demoService;
```

不过直接在测试类的构造方法里用`PrivateAccessor.set(demo, "demoService", new DemoService())`把值放进去不好么，多一种注释，就会多增加一点理解成本🤔

**Comment by Ryan-ff** [comment]
`PrivateAccessor.set(demo, "demoService", new DemoService()) `确实这样更简洁。
至于增加注解增加理解的话，🤔 其实TestableMock本身api就很分散（注解、InvokeMatcher、InvokeVerifier等）不像Mockito一个门面囊括众多api
嵌套关系的注入用set的很麻烦，而且如果成员变量有jsr规范的注解，自动注入不香么
被测试类的成员应该注入mock实例，类似这样`DemoService demoService = TestableMock.mock(DemoService.class)` 而不是显示new出来的实例，这么set可能有歧义
不得不说TestableMock很优秀 解决了代理模式类mock框架解决不了的很多问题👍

**Comment by linfan** [comment]
可以暂定增加一个`@MockField`注解，支持注入任何私有字段（`Bean`是Spring特有的概念），结合其他代理模式工具生成的Mock类型或者直接new出来的对象使用。排到`0.6`版本里，感觉优先级不需要太高。

Testable最开始其实也是被作为Mockito的一种补充，两者是可以一起使用的，根据实际情况选最方便的用法即可。
