### ISSUE TITLE
jpaQueryFactory 怎么mock  service层直接写的动态sql

### ISSUE THREAD

**Issue by colagy** [alibaba/testable-mock#69]
jpaQueryFactory
![image](https://user-images.githubusercontent.com/37213080/106570485-e81eb080-6570-11eb-85d5-612e0cdda7e2.png)

**Comment by linfan** [comment]
应该是只用Mock `fetch()`这个方法就可以了，前面这串调用都不会实际触发对DB的访问

**Comment by linfan** [comment]
如果没有更多问题，这个Issue就先关闭了。若有其他相关问题，可以随时Reopen或另建Issue处理
