### ISSUE TITLE
多模块的工程，根build.gradle里添加jvmArgs后，出现错误

### ISSUE THREAD

**Issue by bobbybin** [alibaba/testable-mock#70]
添加jvmArgs "-javaagent:${classpath.find { it.name.contains("testable-agent") }.absolutePath}"后出错，大概是啥问题

![图片](https://user-images.githubusercontent.com/1538939/106574080-6aa96f00-6575-11eb-9e51-395db637ba0b.png)

**Comment by linfan** [comment]
多模块Gradle工程我们没有实际用过。

从错误来看和 #47 是一样的，可以试参考下这个解法
https://github.com/alibaba/testable-mock/issues/47#issuecomment-764198417

待抽空来做个验证

**Comment by bobbybin** [comment]
> 
> 
> 多模块Gradle工程我们没有实际用过。
> 
> 从错误来看和 #47 是一样的，可以试参考下这个解法
> [#47 (comment)](https://github.com/alibaba/testable-mock/issues/47#issuecomment-764198417)
> 
> 待抽空来做个验证

按47这样新增configurations后，build.gradle是没有问题了
不过在test里使用PrivateAccessor设置私有变量时时报错：Failed to set private field "host": java.lang.NoSuchFieldException: host
PrivateAccessor.set(testService, "host", "host");
![图片](https://user-images.githubusercontent.com/1538939/106703130-946d9f00-6624-11eb-8808-1dbede74cc3b.png)
testService是个有@Spy注解的对象
@Spy
    private TestServiceImpl testService;

**Comment by linfan** [comment]
有`@Spy`注解的对象在实际运行的时候会被初始化为一个Mock代理类，其中不会包含原始`TestServiceImpl`的私有成员，所以在运行期是无法找到该成员的
