### ISSUE TITLE
mock 工具类的静态方法

### ISSUE THREAD

**Issue by tianxx7** [alibaba/testable-mock#71]
我有个A#getXXX()方法里用到了工具类BUtils#createA()
ATest{
@MockMethod(targetClass = BUtils.class, targetMethod = "create")
    public static A createA(String a, String b){
        return new A();
    }
@Test
public void getXXX(){
    ATest a = new ATest();
    a.getXXX(); // getXXX中会用工具类的createA()
}}
打了断点没走到上面的MockMethod的方法里,
请问,这种情况下,要怎么mock呢,万分感谢

**Comment by linfan** [comment]
targetMethod = "create" 这个参数会让Mock的目标函数变成`create`，而不是`createA`，确认一下和这个有没有关系。

另外可以参照[自助问题排查](https://alibaba.github.io/testable-mock/#/zh-cn/doc/troubleshooting)文档先初步定位一下原因。

**Comment by linfan** [comment]
如果没有更多问题，这个Issue就先关闭了。若有其他相关问题，可以随时Reopen或另建Issue处理
