### ISSUE TITLE
被测类为interface，且在实现类里@Autowired ProcessTemplate, 在processTemplate.excute的时候报NP,求教怎么测试

### ISSUE THREAD

**Issue by momoamomo** [alibaba/testable-mock#72]
public class CheckoutFacadeTest extends BaseTest {
    private CheckoutFacade check = new CheckoutFacadeImpl();

    @MockMethod(targetClass = CheckoutService.class)
    private Result<PayPackDto> paySku(PaySkuDto paySkuDto, PlusUser plusUser){
        Result<PayPackDto> result = new Result<>();
        result.setSuccess(true);
        result.setMsg("成功");
        return result;
    }

    @MockMethod(targetClass = CheckoutFacadeImpl.class)
    private Result<PayPackDto> xdfPaySku(PaySkuDto paySkuDto, PlusUser plusUser){
        Result<PayPackDto> result = new Result<>();
        result.setSuccess(true);
        result.setMsg("成功");
        return result;
    }

    @MockMethod
    private  <T, R> R excute(ProcessTemplate self, Processor<T, R> processor, T t) {
        PaySkuDto paySkuDto1 = new PaySkuDto();
        paySkuDto1.setSkuId("22334455");
        paySkuDto1.setPayChannel(1);
        return (R)paySkuDto1;
    }
    @Test
    public void xdfPaySkuTest() {
        PaySkuDto paySkuDto = new PaySkuDto();
        paySkuDto.setSkuId("03912478");
        paySkuDto.setPayChannel(1);
        PlusUser plusUser = new PlusUser();
        plusUser.setUserPhone("157****6395");
        Assert.assertEquals("成功", check.xdfPaySku(paySkuDto, plusUser).getMsg());
    }
}

public interface CheckoutFacade {
    Result<PayPackDto> xdfPaySku(PaySkuDto paySkuDto, PlusUser plusUser);
}

public class CheckoutFacadeImpl implements CheckoutFacade {

    @Autowired
    private ProcessTemplate processTemplate;

    @Autowired
    private CheckoutService checkoutService;
    
    @Override
    public Result<PayPackDto> xdfPaySku(PaySkuDto paySkuDto, PlusUser plusUser) {
        return processTemplate.excute(new Processor<PaySkuDto, Result<PayPackDto>>() {
            @Override
            public void beforeProcessing(PaySkuDto paySkuDto) {
                ***
            }
            @Override
            public Result<PayPackDto> process(PaySkuDto paySkuDto) {
                ******
            }
            @Override
            public void afterProcessing(Result<PayPackDto> stringResult) {

            }
        }, paySkuDto);
    }

}

**Comment by linfan** [comment]
两个问题哈。
首先Mock方法替换只对被测类里的代码生效，因此在测试用例里面的`xdfPaySku()`调用是不会被替换成Mock的。
另外被测类里`@Autowired`注册的对象默认在测试运行时候就是空的，如果需要在测试前初始化，可以在测试类的构造方法里利用TestableMock的私有成员访问机制给这些变量赋值。

**Comment by momoamomo** [comment]
你好，还是再请教下哈
private CheckoutFacade check = new CheckoutFacadeImpl(); 
1.因为被测类是接口，在创建被测类对象时new了具体的对象，那么mock时xdfPaySku方法的targetClass 参数是 CheckoutFacade.class还是CheckoutFacadeImpl.class？
2.对于@Autowired注册的对象，用PrivateAccessor如何初始化赋值呢，看了demo里的例子，关于这种还是不太会使用，有没有类似的例子呢

**Comment by linfan** [comment]
问题1：以声明的类型为准，`check`对象的类型是`CheckoutFacade`
问题2：在测试类的构造函数里直接给被测类私有成员赋值即可，比如`PrivateAccessor.set(<被测类对象>, "checkoutService", new CheckoutService())`，这样原本需要注入进去的成员在测试运行的时候就不是null了
