### ISSUE TITLE
被测类的内部类中，mock的方法不生效

### ISSUE THREAD

**Issue by GodwinHub** [alibaba/testable-mock#74]
被测类有内部类，主要想测的也是其中的内部类，但是@MockMethod注释的方法在内部类中不生效，请问这个需要如何写测试类？

**Comment by linfan** [comment]
这是个好问题😀，目前版本还不能支持，但`0.5`版本会支持这种情况。

按照目前进度，预计新年之前的优化内容还只能进`0.4.12`版本（0.4.x的最后一个版本），年后`0.5`版本就会发出来了。

**Comment by GodwinHub** [comment]
好的，感谢😁，还有个问题，
像是Apollo这种自己写工具类调用的
Config config = ConfigService.getAppConfig();
String times = config.getProperty("times", "1.3");

测试类里这样写
@MockMethod(targetClass = ConfigService.class)
    private static Config getAppConfig() {
        return null;
    }

    @MockMethod(targetClass = Config.class)
    private String getProperty(String var1, String var2) {
        return "test";
    }

TestableMock为什么不用关注第一步mock的config返回的是什么，config返回null，后面的getProperty也不会报错，实现原理是什么呢？

**Comment by linfan** [comment]
`0.5.0`已发布。
测试内部类现在可以通过给内部类显式添加`@MockWith`注解实现，虽然稍美中不足的是要改动到业务代码。
相关文档见 https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock-with

第二个问题已在 #77 回复
