### ISSUE TITLE
什么时候能支持测试类和被测类的包路径不同

### ISSUE THREAD

**Issue by davidlwq** [alibaba/testable-mock#75]
被测类与测试类是否包路径相同，且名称为"被测类+Test"（0.4.x版本要求）

不知道这个什么时候能支持多模块开发，在其中A模块中引入B模块，且在A模块中写单测方法可以Mock  B模块中的类呢？

**Comment by linfan** [comment]
> 且在A模块中写单测方法可以Mock B模块中的类

我猜你是想问“在A测试类的Mock方法可以在B类的代码里生效”。Testable在Mock方面的顶层设计思路是“给每个类型配一个Mock类”，只要类里代码调用的方法与Mock类里声明的方法匹配，在测试时候就会用Mock类里的对应方法替换原始调用。从这个原理来说，在A的Mock类定义的Mock方法一定只对A类生效，需要MockB类代码里的调用，在B的Mock类里声明即可。这样不论是什么开发框架、测试框架，在Mock的使用上都能一致且不受限。

`0.4.x`版本里Mock类和Test类是同一个，因此有诸如包名和类名的限制，`0.5`版本会将支持将两者分开定义（从使用上差别不大，但底层实现会有比较大的变化），同时会支持基于继承来进行Mock方法的复用，在灵活性上会有比较大的提升。

**Comment by davidlwq** [comment]
目前我的项目结构是这样的

activity
  - dependency 模块
     com/demo/DelayJobDependency.java
  - controller模块
  - service模块
  - test模块
    com/demo/DelayJobDependencyTest.java

执行后出现了以下日志，但是没有看到有哪一行方法被替换，不知道这样写是不是不符合现在Testable规范？

**Comment by linfan** [comment]
Mock方法的声明没有问题。需要注意的是，写在`DelayJobDependencyTest`类里定义的Mock方法，只会对`DelayJobDependency`类型里的调用进行匹配，比如在`DelayJobDependency`类型里有代码调用了`submit()`方法，就会在测试的时候被换成对Mock方法的调用（原本在`DelayJobDependency`类里定义的`submit()`方法并不会变化，而且在Mock方法里还可以通过self.submit()来调用这个原本的方法，具体参考[文档](https://alibaba.github.io/testable-mock/#/zh-cn/doc/use-mock)）。

`DelayJobDependency`类型的Mock类是`DelayJobDependencyTest`（当前和Test类是同一个），并且换的是被测类里匹配到的调用，而不是被测类的方法定义，理解这个原理使用起来应该就没问题了~

**Comment by davidlwq** [comment]
> 只会对`DelayJobDependency`类型里的调用进行匹配

明白了，这句话最有用，目前已经解决，调试通了，多谢指导

**Comment by Nibbbbbbbb** [comment]
就是说 Test类里去mock类B方法，我如果在Test类里调用类A里的方法-间接调用到了类B，这样是mock不到的吗？

**Comment by linfan** [comment]
@Nibbbbbbbb 默认是会Mock到的，除非给`@MockMethod`注解加`scope = ASSOCIATED`参数，参考文档：https://alibaba.github.io/testable-mock/#/zh-cn/doc/scope-of-mock

关于前面提到的`TestableMock`的原理，也已经补充到正式文档里了：https://alibaba.github.io/testable-mock/#/zh-cn/doc/design-and-mechanism

如果对文档中内容有哪些写得不太容易理解的，也不妨提出来~

**Comment by linfan** [comment]
关于Mock生效范围这个问题，我们近期再补充一个示例到代码里，这样可能会更清晰一些

**Comment by Nibbbbbbbb** [comment]
> 关于Mock生效范围这个问题，我们近期再补充一个示例到代码里，这样可能会更清晰一些

即使跨模块也可以mock吗

我在**模块A**的单元测试中mock一个普通返回String方法，是正常mock的
而在**主模块**的集成测试中，也mock了**模块A**的某个普通返回String方法，但是调用模块A的其他方法间接调用到被mock的方法，却无法mock

```java
	@MockDiagnose
    public static class Mock {
        @MockMethod(targetClass = UploadManager.class, scope = MockScope.GLOBAL)
        private String getPath(String fileName, String path) {
            return "测试用例";
        }
    }
```

**Comment by linfan** [comment]
跨模块不行哈，模块之间是Jar包依赖引用，打Jar包的时候`src/test/java`目录下面的Mock容器类（和其他测试类都）不会带进去，这样测试运行的时候是找不到对应类型的Mock容器类的。

这场景真是我们完全没想到的🤣。从原理上来说，应该可以在主模块的`src/test/java`目录下面创建和要Mock的业务类同包路径的目录，然后在这个目录下面放`业务类+Mock`的类，作为主模块集成测试时候子模块业务类的Mock容器类（Mock的方法和内容和子模块里的不一定要一样），这样在测试运行的时候会匹配到Mock容器。

如果要比较优雅的解决这个问题，一种可取的办法是支持全局参数配置额外的Mock容器关联，这样虽然在主模块里的还是需要为子模块业务类单独创建Mock容器类，但这些容器类可以放到任意位置。另建了一个Issue #105 来跟踪这个需求。
