### ISSUE TITLE
像是Apollo这种先获取config，再使用config调用的，@MockMethod里不需要关心第一步返回的是什么，这是为什么？

### ISSUE THREAD

**Issue by GodwinHub** [alibaba/testable-mock#77]
像是Apollo这种调用的
Config config = ConfigService.getAppConfig();
String times = config.getProperty("times", "1.3");

测试类里这样写

    @MockMethod(targetClass = ConfigService.class)
    private static Config getAppConfig() {
        return null;
    }

    @MockMethod(targetClass = Config.class)
    private String getProperty(String var1, String var2) {
        return "test";
    }
TestableMock为什么不用关注第一步mock的config返回的是什么，config返回null，后面的getProperty也不会报错，实现原理是什么呢？

**Comment by linfan** [comment]
被测类里的`config.getProperty("times", "1.3")`在测试运行时因为匹配到Mock方法声明，会在测试运行的时候被动态替换成对测试类的`getAppConfig()`方法的调用。因此测试的时候实际上不会调到config的`getAppConfig()`方法，这个变量是否为null就无所谓了。
