### ISSUE TITLE
Springboot项目，@MockeMethod的方法声明为public，会报错“java.lang.IncompatibleClassChangeError: Expecting non-static method”

### ISSUE THREAD

**Issue by BabysBreath799** [alibaba/testable-mock#79]
`    @MockMethod(targetClass = RespEntity.class)
    public RespEntity<ApplicationDTO> insert(ApplicationDTO application) {
        ApplicationDTO applicationDTO = new ApplicationDTO();
        applicationDTO.setApplicationId(333L);
        return RespEntity.ok(applicationDTO);
    }

    @Test
    public void testInsert_basic() {
        // 正常插入
        ApplicationDTO copy = CommonTestUtil.arrayToEntity(rightData, ApplicationDTO.class);
        copy.setVersion(1);
        Long applicationId = FeignUtil.get(insert(copy)).getApplicationId();
        copy.setApplicationId(applicationId);
        Application application = MapperUtil.map(copy, Application.class);
        curdMapper.insert(application);
        Assert.assertNotNull(applicationMapper.selectByPrimaryKey(application));
    }`

报错信息为：java.lang.IncompatibleClassChangeError: Expecting non-static method com.wejoyclass.open.service.impl.ApplicationServiceImplTest.insert

**Comment by linfan** [comment]
`non-static method`相关错误先按[常见问题](https://alibaba.github.io/testable-mock/#/zh-cn/doc/frequently-asked-questions)第8项处理，把Mock方法声明为`static`的：`public static RespEntity insert(ApplicationDTO application)`

这个问题在`0.5`版本里会统一修复

**Comment by BabysBreath799** [comment]
已解决
