### ISSUE TITLE
开启"Delegate IDE build/run actions to maven"选项后，提示Class not found

### ISSUE THREAD

**Issue by 100Continue** [alibaba/testable-mock#8]
开启"Delegate IDE build/run actions to maven"选项后，提示Class not found

**Comment by zhulingao** [comment]
![image](https://user-images.githubusercontent.com/32088390/102898345-579a7e00-44a4-11eb-9673-e221415f281c.png)
刚开始运行java-demo下的test也是报class not found, 如图这样配置就不报错了，你可以试试

**Comment by 100Continue** [comment]
> https://www.freesion.com/article/1264909741/
> 刚开始运行java-demo下的test也是报class not found, 按照上面链接这样配置就不报错了，你可以试试

在"虚拟机参数"属性值末尾添加JavaAgent启动参数：-javaagent:${HOME}/.m2/repository/com/alibaba/testable/testable-agent/x.y.z/testable-agent-x.y.z.jar 就可以了
