### ISSUE TITLE
对junit4是不支持吗

### ISSUE THREAD

**Issue by hugo666-code** [alibaba/testable-mock#80]

**Comment by linfan** [comment]
支持的，原理上不依赖任何开发框架、测试框架，通用

**Comment by hugo666-code** [comment]
![image](https://user-images.githubusercontent.com/58542475/107002061-a8043b80-67c5-11eb-9b8c-16a58f0014ec.png)
@Test
    public void should_able_to_access_private_method() {
        List<String> list = new ArrayList<String>() {{ add("a"); add("b"); add("c"); }};
        //assertEquals("member", demoPrivateAccess.privateFunc());
        assertEquals("member", PrivateAccessor.invoke(demoPrivateAccess, "privateFunc"));
       // assertEquals("abc + hello + 1", demoPrivateAccess.privateFuncWithArgs(list, "hello", 1));
        assertEquals("abc + hello + 1", PrivateAccessor.invoke(demoPrivateAccess, "privateFuncWithArgs", list, "hello", 1));
    }

Error:java: com.alibaba.testable.processor.exception.MemberNotExistException: Method "privateFunc" with 0 parameter not exist in class "DemoPrivateAccess"
跑demo用junit4 变异直接就报错了.  junit5正常

**Comment by hugo666-code** [comment]
抱歉:  版本用的0.4.11  改为0.4.5 没问题了

**Comment by linfan** [comment]
是在Windows系统是使用吗？
看起来是`0.4.9`增加的[私有方法访问目标检测功能](https://github.com/alibaba/testable-mock/issues/21)在IDEA里运行的问题，JUnit 4我们内部项目有在用，包括Testable的回归测试项目也是用的JUnit 4。我们周末试下Windows环境的验证。

**Comment by hugo666-code** [comment]
Windows

**Comment by linfan** [comment]
我先标为BUG，可能是系统兼容性问题，先做下验证

**Comment by linfan** [comment]
在Windows下分别对Maven和Gradle方式导入项目到IntelliJ，然后在IntelliJ中以及控制台中运行测试的场景都进行了测试（共4种情况：Maven导入IntelliJ中运行，Gradle导入IntelliJ中运行，Maven在命令行运行，Gradle在cmd命令行运行），Testable版本`0.4.11`，目前没有复现出问题。

验证使用的代码在仓库的`junit4`分支：
https://github.com/alibaba/testable-mock/tree/junit4/demo/java-demo

**Comment by linfan** [comment]
作为临时方案，在下个版本里我们增加一个可选开关配置来关闭访问目标的编译期检查。

如果有其他能复现问题的线索或实例项目，也欢迎提供。

**Comment by linfan** [comment]
`0.4.12`版本已增加控制开关
https://alibaba.github.io/testable-mock/#/zh-cn/doc/private-accessor?id=私有成员编译期校验
