### ISSUE TITLE
[WARN] Failed to transform class 

### ISSUE THREAD

**Issue by shc-000** [alibaba/testable-mock#81]
[WARN] Failed to transform class ...
[DIAGNOSE] java.lang.ArrayIndexOutOfBoundsException: 0

你好，请问这个无法转换的问题是什么原因导致的？

**Comment by linfan** [comment]
和 #52 应该是同一个问题，修复已经提交到主干，会包含在`0.4.12`版本里

**Comment by linfan** [comment]
`0.4.12`版本已发
