### ISSUE TITLE
访问私有成员变量出错

### ISSUE THREAD

**Issue by becomeownsun** [alibaba/testable-mock#83]
出错信息：java: java.lang.ExceptionInInitializerError
pcloud_subapp_name can't not be found in System properties or pcloud_subapp_name cant be fount in System env

**Comment by becomeownsun** [comment]
加@EnablePrivateAccess注解，就报以上错误，麻烦问下这是怎么回事呀

**Comment by linfan** [comment]
应该是BUG，但单从这个错误提示来看，目前还无法定位确切原因。能否提供一些更详细的上下文信息，比如项目中是否使用了`pcloud_subapp_name`这样一个参数，是如何使用的？以及是否使用了与`pcloud`哪些的依赖，或其他有助于复现问题的线索？

**Comment by linfan** [comment]
暂无更多可用信息，Issue先关闭。
如相关问题依然存在，需Reopen此Issue或创建新的Issue。
