### ISSUE TITLE
请问Issue#82中的问题有什么办法可以避免吗？

### ISSUE THREAD

**Issue by GodwinHub** [alibaba/testable-mock#84]
在Issue#82的回答中您提到TestableMock是单独Mock被测类中的特定方法调用，那么该如何避免由于没有mock替换个别方法，导致上线过程中执行测试用例影响而到真实数据呢？例如insert或者update类似会影响到数据库或是其他真实数据的操作，目前有什么办法可以避免吗？

**Comment by linfan** [comment]
针对Mock整个对象的这种场景，我们内部再次评估过后还是认为Mockito使用的基于动态代理的Mock机制是最合适的。鉴于这方面的轮子已经很多，无需再造，TestableMock定位是单元测试辅助工具，也可以作为Mockito能力的额外补充。

其实单元测试本质是一种开发者自己来写白盒测试，被测方法里有需要测试哪些链路、哪些无关调用需要进行Mock应当是写单元测试时候需要十分明确的事情。一次性把所有方法自动变成Mock，全部自动返回null或随机值通常来说也不能满足实际测试路径的需要，作用并不太大（除了真的让测试直连线上数据库的时候避免漏写Mock误改线上数据以外）。
