### ISSUE TITLE
关于mock替换Feign接口中的方法问题

### ISSUE THREAD

**Issue by BabysBreath799** [alibaba/testable-mock#85]
被测类中调用了feign接口中的方法，在替换时规定“targetClass = XXXService.class”,但依然会报错“java.lang.IllegalStateException: Failed to load ApplicationContext”。

我目前的解决方案是：将调用该Feign接口的代码提出并封装成一个私有方法，然后mock该私有方法。（具体到我的项目里是在serviceImpl将feign接口封装成private）。

请教一下：是否有更好的解决方案

**Comment by linfan** [comment]
试着理解了一下，还是没有Get到你是怎么写的，能用代码举一下例子吗？
原先是怎样写的Mock方法会报错，然后封装成私有方法具体是怎样封装的，多谢

**Comment by BabysBreath799** [comment]
这是成功mock的写法：
   public void insert(ApplicationDTO application) {
        // 设置应用所属人ID和姓名
        application.setOwner(SecurityUtil.getUserId());
        application.setOwnerName(SecurityUtil.getFullName());

        // 设置加密后appSecret
        application.setAppSecretAfter(encrypt(application.getAppSecret()));

        // 设置应用状态
        // 状态：待审核
        application.setStatus(ApplicationStatus.PREPARE.getValue());

        // call feign
        ApplicationDTO origin = insertByFeign(application);

        // 保存至本地应用表
        Application app = MapperUtil.copy(application, Application.class);
        app.setApplicationId(origin.getId());
        app.setRequestDate(new Date());
        app.setVersion(1);

        insert(app);

        // 插入oauth_client_details表
        ClientDetail clientDetail = new ClientDetail();
        clientDetail.setClientId(app.getAppId());
        clientDetail.setClientSecret(app.getAppSecretAfter());
        clientDetail.setClientSecretOrigin(app.getAppSecret());
        clientDetail.setScope("basic_info");
        clientDetail.setAuthorizedGrantTypes("client_credentials");
        clientDetail.setWebServerRedirectUri("");
        clientDetail.setAuthorities("ROLE_DEFAULT");
        clientDetail.setAccessTokenValidity(7200);
        clientDetail.setRefreshTokenValidity(2592000);
        clientDetail.setAutoapprove("true");
        oauthClientDetailsMapper.insert(clientDetail);
    }

其中call feign中的insertByFeign方法如下：
  private ApplicationDTO insertByFeign(ApplicationDTO application) {
        // 调用统一认证feign接口保存
        RespEntity<ApplicationDTO> respEntity = unionAuthService.insert(application);
        return FeignUtil.get(respEntity);
    }

如果将insertByFeign方法的方法体直接写在insert方法中，则会报以上错误。(实际上insertByFeign方法只有一行，原来的写法就是在insert方法中直接执行，而不是写在private方法中再调用)

**Comment by linfan** [comment]
收到，看现象应该是之前的Mock定义没匹配到调用，所以没有成功置换，我找个包含feign接口的代码试试看是否有什么特别的地方。
你也可以参考自助排查文档打开`VERBOSE`级别的日志，查看一下这行调用在运行时的方法签名是怎样的，和Mock方法的签名是否有什么不同。https://alibaba.github.io/testable-mock/#/zh-cn/doc/troubleshooting

**Comment by BabysBreath799** [comment]
感谢作者！我再次写了demo测试后都没有复现该问题，应当是我Mock代码编写错误，打印了日之后初步判断是由于Mock的方法返回值或者参数与原方法不一直导致Mock方法没有被调用。

**Comment by BabysBreath799** [comment]
感谢作者！我再次写了demo测试后都没有复现该问题，应当是我Mock代码编写错误，打印了日之后初步判断是由于Mock的方法返回值或者参数与原方法不一直导致Mock方法没有被调用。
