### ISSUE TITLE
MOCK作用于整个test生命周期导致易用性极度下降

### ISSUE THREAD

**Issue by yinfucheng** [alibaba/testable-mock#87]
在一个测试类中对某个方法进行mock，即便使用了private修饰符，仍然会作用到其他测试类中。如示例demo代码中的：DemoMockTest
`    @MockConstructor
    private BlackBox createBlackBox(String text) {
        return new BlackBox("mock_" + text);
    }`
这个mock，在我新建了另一个测试类后去测试demoMock.newFunc()时，mock仍然是生效的。

在最近的使用中这个机制给我们造成了极大的困惑和不便。
1.某个类在被调用的过程中属于外部依赖，而这个类是别人写的，我不想关注这个类的内部逻辑，此时就需要被mock；但在对该类做测试时，很多方法就不需要被mock。
2.不同的开发人员互相不知道别人都做过哪些mock，编写的测试类莫名其妙失败，堪比车祸现场。
3.如需规避以上问题就需要对同一个类的mock做统一管理，例如将A.java中的所有mock写在AMock.java中，但是这样每次mock一个类就要增加管理该类的mock类，导致工程文件数激增。且在demo中的mock我看都是在对应的测试类中实现的，并没有采用单独管理。是否作者的初衷就是mock的生命周期为当前test类，而不是整个测试执行的周期呢？

**Comment by linfan** [comment]
从设计的初衷来说，核心的逻辑其实就是给每个被测类搭配一个Mock类，比如说测试`Demo.java`，测试代码在`DemoTest.java`文件，Mock代码在`DemoMock.java`文件。在运行`DemoTest`的单元测试时，一旦执行到与`DemoMock`里声明方法匹配的Mock方法，就直接执行Mock类里的方法，这样对开发者来说Mock的编写成本会很低。

实际的实现没有一开始就用独立Mock类的方式，而是让Mock类和Test类共用，这样上述逻辑就进一步简化成了在Test类里直接写Mock方法。但在当前的版本里确实存在两个比较明显的问题：
1. 为了复用Test类，采用了自动把Mock方法改为`static`声明的做法，导致在文档常见问题里提到的`non-static access`错误
2. 默认的Mock方法作用范围是所有单元测试用例，就是你遇到的这个情况

按照接下来的开发计划，这两个问题分别要在`0.5`和`0.6`版本里解决（见项目Readme的"版本计划"）。其中`0.5`版本已经在开发中，预计在2月底之前能完成测试验收并发布，`0.6`版本争取在3月底前发布，有更详细的时间点我们也会及时更新到项目Readme里

**Comment by linfan** [comment]
@yinfucheng Mock作用范围的问题这两天提前处理好了，预计可以合并到`0.5`版本一起在2月份就发布哈

**Comment by yinfucheng** [comment]
> @yinfucheng Mock作用范围的问题这两天提前处理好了，预计可以合并到`0.5`版本一起在2月份就发布哈

非常感谢你的贡献和答复，后续我们持续关注testablemock框架的更新。

**Comment by linfan** [comment]
`0.5.0`版本已发布~
Mock范围控制可参考文档：https://alibaba.github.io/testable-mock/#/zh-cn/doc/scope-of-mock
