### ISSUE TITLE
Java demo 测试报错

### ISSUE THREAD

**Issue by workswan** [alibaba/testable-mock#89]
Connected to the target VM, address: '127.0.0.1:2653', transport: 'socket'
Disconnected from the target VM, address: '127.0.0.1:2653', transport: 'socket'
����: �Ҳ������޷��������� @{argLine}

**Comment by linfan** [comment]
能稍微描述一下你是怎样运行Demo的么？单看这个信息不太好判断原因。

感觉像是使用了远程调试，正常运行应该不会有这个输出。
