### ISSUE TITLE
开个钉钉群吧。提issue沟通，太低效了

### ISSUE THREAD

**Issue by 100Continue** [alibaba/testable-mock#9]
开个钉钉群吧。提issue沟通，太低效了

**Comment by linfan** [comment]
先直接加我钉钉吧，暂时不拉群，消息太多处理不过来~
![IMG_0278](https://user-images.githubusercontent.com/1113435/102889253-439b5000-4495-11eb-9553-3b77c3e3b8df.png)

**Comment by 100Continue** [comment]
图片看不到~~

**Comment by 100Continue** [comment]
图片看不到~~

> 先直接加我钉钉吧，暂时不拉群，消息太多处理不过来~
> ![IMG_0278](https://user-images.githubusercontent.com/1113435/102889253-439b5000-4495-11eb-9553-3b77c3e3b8df.png)

图片打不开

**Comment by linfan** [comment]
Github自动把图片地址转到了githubusercontent.com了，如果看不到可以直接用这个链接
https://testable-code.oss-cn-beijing.aliyuncs.com/linfan-ding-code.png
