### ISSUE TITLE
子类中修改父类的变量报错

### ISSUE THREAD

**Issue by hugo666-code** [alibaba/testable-mock#91]
PrivateAccessor.set(new ReceiveBillManagerImpl(), "mongoOperations", MongoTestUtils.getMongoOperations());

ReceiveBillManagerImpl的父类里有一个protected修饰的变量mongoOperations   想使用PrivateAccessor进行赋值,但是编译期报错Error:java: com.alibaba.testable.processor.exception.MemberNotExistException: Field "mongoOperations" not exist in class "ReceiveBillManagerImpl"

是不是TestableMock只能对private 修饰的变量进行修改,protected修饰的不行

**Comment by linfan** [comment]
问题收到，当前的编译期检查功能确实对父类成员没做好适配，下个版本里会提供一个绕过方案，预计在`0.5.1`版本做正式修复

**Comment by linfan** [comment]
@hugo666-code 刚发现绕过方案在`0.4.12`版本已经发了😆，把`@EnablePrivateAccess`注解的`verifyTargetOnCompile`参数值设置成`false`就行：
https://alibaba.github.io/testable-mock/#/zh-cn/doc/private-accessor?id=私有成员编译期校验

如果只是用`PrivateAccessor`工具类的话，也可以直接把`@EnablePrivateAccess`注解去掉，也会禁用编译期校验

**Comment by linfan** [comment]
正式修复将包含在`0.5.2`版本中

**Comment by linfan** [comment]
`0.5.2`版本已发布
