### ISSUE TITLE
0.5版本升级指南404not found

### ISSUE THREAD

**Issue by chenyh017** [alibaba/testable-mock#94]
RT，0.5版本升级指南返回404 not found，请问怎么升级到0.5版本？
https://alibaba.github.io/testable-mock/#/zh-cn/doc/upgrade-to-v05

**Comment by linfan** [comment]
`0.5.0`还未正式发布（不要被0.5分支的README欺骗哈...👻），但目前中文文档已经基本就绪了，可以先在0.5分支的docs目录下面找到相关文档的源文件：
https://github.com/alibaba/testable-mock/blob/0.5/docs/zh-cn/doc/

**Comment by linfan** [comment]
正式版本在最近这一两天完成英文文档和相关示例的补充之后就会发布出来

**Comment by linfan** [comment]
发布啦~
现在可以直接打开这个链接了 https://alibaba.github.io/testable-mock/#/zh-cn/doc/upgrade-to-v05
