### ISSUE TITLE
Static variable Not followed the naming convention

### ISSUE THREAD

**Issue by HelloThisWorld** [alibaba/testable-mock#95]
https://github.com/alibaba/testable-mock/blob/f660ccb88fb18b0dc30649a1b35aad9bbb43e73f/testable-agent/src/main/java/com/alibaba/testable/agent/PreMain.java#L21

Static variable Not followed the naming convention, please address it.

**Comment by linfan** [comment]
As I know, final variable usually prone to be defined in underscored-uppercase letters, is there a naming convention for static variable ?

**Comment by linfan** [comment]
looks good according to:
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html
