### ISSUE TITLE
No null check for input params

### ISSUE THREAD

**Issue by HelloThisWorld** [alibaba/testable-mock#96]
https://github.com/alibaba/testable-mock/blob/f64b07e9da0e0644108ba6145eee7ed343c325bf/testable-core/src/main/java/com/alibaba/testable/core/accessor/PrivateAccessor.java#L22-L30

**Comment by linfan** [comment]
Not actually needed. For private accessor, if user ask to access a field of `null` or from a `null` instance, just let the NullPointerException goes, that's what should happen : )
