### ISSUE TITLE
Don't use general Exception

### ISSUE THREAD

**Issue by HelloThisWorld** [alibaba/testable-mock#97]
https://github.com/alibaba/testable-mock/blob/f64b07e9da0e0644108ba6145eee7ed343c325bf/testable-core/src/main/java/com/alibaba/testable/core/accessor/PrivateAccessor.java#L27

**Comment by linfan** [comment]
That's a good one, will narrow it 👍

**Comment by linfan** [comment]
It was using `Exception` because of JDK 6 compatibility.

There are 2 kinds of exception goes here without shared parent class, so the code goes like this:

```
} catch (IllegalAccessException e) {
    throw new MemberAccessException("Failed to get private field \"" + field + "\"", e);
} catch (NoSuchFieldException e) {
    throw new MemberAccessException("Failed to get private field \"" + field + "\"", e);
}
```

JDK 6 not allow syntax like `IllegalAccessException | NoSuchFieldException` , so `Exception` is used for simplicity.

**Comment by linfan** [comment]
Fixed in `master`
