### ISSUE TITLE
MOCK_CONTEXT报java.lang.NullPointerException

### ISSUE THREAD

**Issue by CZ-2020** [alibaba/testable-mock#98]

**Comment by linfan** [comment]
如果异常信息里有打印出错误堆栈，可以贴一下哦~

**Comment by CZ-2020** [comment]
没有其他信息，就报了个空指针异常

**Comment by linfan** [comment]
是在什么地方使用了`MOCK_CONTEXT`呢，能否稍微详细描述一下？
Review了代码，`MOCK_CONTEXT`本身应该不能够造成空指针，目前也没有复现出这个问题

**Comment by CZ-2020** [comment]
我调试了一下在TestableClassTransformer类46行的transform方法出现的java/lang/reflect/InvocationTargetException
是junit-platform-commons-1.7.0.jar的ReflectionUtils类中invokeMethod方法在357行((Method)makeAccessible(method)).invoke(target, args)这里抛的异常

**Comment by CZ-2020** [comment]
下面这个代码就出现了，是用法改了吗？
class BugRecoverTest {
    @Test
    void getStatus() {
        MOCK_CONTEXT.put("testName", "test1");
    }
}

**Comment by linfan** [comment]
在没有关联Mock容器的测试类里使用`MOCK_CONTEXT`确实不行，因为这个类不会被`TestableMock`做预处理，实际场景来说，未关联Mock容器使用`MOCK_CONTEXT`也没有什么意义。参数化测试的问题是个BUG，我们会在近期版本修复。

感谢详细的代码例子👍

**Comment by yinfucheng** [comment]
在使用mockito的自动注入注解@Mock和@Injectable也会出现该npe的问题。

**Comment by linfan** [comment]
mockito的自动注入注解导致NPE可以贴一个大概的示例吗，直接代码理解起来会直观一点

**Comment by linfan** [comment]
参数化测试在`v0.5.1`已支持
